// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__f32toa = 16
)

const (
    _stack__f32toa = 64
)

const (
    _size__f32toa = 3696
)

var (
    _pcsp__f32toa = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {3638, 64},
        {3642, 48},
        {3643, 40},
        {3645, 32},
        {3647, 24},
        {3649, 16},
        {3651, 8},
        {3652, 0},
        {3682, 64},
    }
)

var _cfunc_f32toa = []loader.CFunc{
    {"_f32toa_entry", 0,  _entry__f32toa, 0, nil},
    {"_f32toa", _entry__f32toa, _size__f32toa, _stack__f32toa, _pcsp__f32toa},
}
