// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __native_entry__() uintptr

var (
    _subr__atof_native = __native_entry__() + 9350
    _subr__f64toa      = __native_entry__() + 570
    _subr__i64toa      = __native_entry__() + 3653
    _subr__lspace      = __native_entry__() + 251
    _subr__lzero       = __native_entry__() + 13
    _subr__quote       = __native_entry__() + 4970
    _subr__skip_array  = __native_entry__() + 16213
    _subr__skip_object = __native_entry__() + 16248
    _subr__skip_one    = __native_entry__() + 14416
    _subr__u64toa      = __native_entry__() + 3748
    _subr__unquote     = __native_entry__() + 6022
    _subr__value       = __native_entry__() + 9831
    _subr__vnumber     = __native_entry__() + 12610
    _subr__vsigned     = __native_entry__() + 13860
    _subr__vstring     = __native_entry__() + 11563
    _subr__vunsigned   = __native_entry__() + 14140
)

var (
    _ = _subr__atof_native
    _ = _subr__f64toa
    _ = _subr__i64toa
    _ = _subr__lspace
    _ = _subr__lzero
    _ = _subr__quote
    _ = _subr__skip_array
    _ = _subr__skip_object
    _ = _subr__skip_one
    _ = _subr__u64toa
    _ = _subr__unquote
    _ = _subr__value
    _ = _subr__vnumber
    _ = _subr__vsigned
    _ = _subr__vstring
    _ = _subr__vunsigned
)
