// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __native_entry__() uintptr

var (
    _subr__f64toa      = __native_entry__() + 630
    _subr__i64toa      = __native_entry__() + 3642
    _subr__lspace      = __native_entry__() + 301
    _subr__lzero       = __native_entry__() + 13
    _subr__quote       = __native_entry__() + 4955
    _subr__skip_array  = __native_entry__() + 17298
    _subr__skip_object = __native_entry__() + 17333
    _subr__skip_one    = __native_entry__() + 15505
    _subr__u64toa      = __native_entry__() + 3735
    _subr__unquote     = __native_entry__() + 5888
    _subr__value       = __native_entry__() + 10928
    _subr__vnumber     = __native_entry__() + 13704
    _subr__vsigned     = __native_entry__() + 14977
    _subr__vstring     = __native_entry__() + 12691
    _subr__vunsigned   = __native_entry__() + 15236
)

var (
    _ = _subr__f64toa
    _ = _subr__i64toa
    _ = _subr__lspace
    _ = _subr__lzero
    _ = _subr__quote
    _ = _subr__skip_array
    _ = _subr__skip_object
    _ = _subr__skip_one
    _ = _subr__u64toa
    _ = _subr__unquote
    _ = _subr__value
    _ = _subr__vnumber
    _ = _subr__vsigned
    _ = _subr__vstring
    _ = _subr__vunsigned
)
