// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__parse_with_padding = 320
)

const (
    _stack__parse_with_padding = 176
)

const (
    _size__parse_with_padding = 49340
)

var (
    _pcsp__parse_with_padding = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {8192, 176},
        {8199, 48},
        {8200, 40},
        {8202, 32},
        {8204, 24},
        {8206, 16},
        {8208, 8},
        {8209, 0},
        {49340, 176},
    }
)

var _cfunc_parse_with_padding = []loader.CFunc{
    {"_parse_with_padding_entry", 0,  _entry__parse_with_padding, 0, nil},
    {"_parse_with_padding", _entry__parse_with_padding, _size__parse_with_padding, _stack__parse_with_padding, _pcsp__parse_with_padding},
}
