// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__u64toa = 80
)

const (
    _stack__u64toa = 8
)

const (
    _size__u64toa = 1232
)

var (
    _pcsp__u64toa = [][2]uint32{
        {1, 0},
        {164, 8},
        {165, 0},
        {462, 8},
        {463, 0},
        {774, 8},
        {775, 0},
        {1230, 8},
        {1232, 0},
    }
)

var _cfunc_u64toa = []loader.CFunc{
    {"_u64toa_entry", 0,  _entry__u64toa, 0, nil},
    {"_u64toa", _entry__u64toa, _size__u64toa, _stack__u64toa, _pcsp__u64toa},
}
