// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__get_by_path = 640
)

const (
    _stack__get_by_path = 208
)

const (
    _size__get_by_path = 22008
)

var (
    _pcsp__get_by_path = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x14, 48},
        {0x4bcc, 208},
        {0x4bcd, 48},
        {0x4bcf, 40},
        {0x4bd1, 32},
        {0x4bd3, 24},
        {0x4bd5, 16},
        {0x4bd6, 8},
        {0x4bda, 0},
        {0x55f8, 208},
    }
)

var _cfunc_get_by_path = []loader.CFunc{
    {"_get_by_path_entry", 0,  _entry__get_by_path, 0, nil},
    {"_get_by_path", _entry__get_by_path, _size__get_by_path, _stack__get_by_path, _pcsp__get_by_path},
}
