// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__f32toa = 80
    _entry__f64toa = 3792
    _entry__get_by_path = 8944
    _entry__fsm_exec_1 = 24496
    _entry__skip_string_1 = 52288
    _entry__skip_one_fast_1 = 15312
    _entry__html_escape = 18848
    _entry__i64toa = 20864
    _entry__u64toa_1 = 32432
    _entry__lspace = 20960
    _entry__quote = 21360
    _entry__skip_array = 24064
    _entry__skip_number = 30256
    _entry__skip_number_1 = 30640
    _entry__skip_object = 32224
    _entry__skip_one = 32288
    _entry__skip_one_fast = 32336
    _entry__u64toa = 32352
    _entry__unquote = 33680
    _entry__validate_one = 35776
    _entry__validate_utf8 = 35824
    _entry__validate_utf8_fast = 36784
    _entry__value = 39488
    _entry__vstring_1 = 41344
    _entry__vnumber_1 = 43296
    _entry__atof_eisel_lemire64_1 = 54048
    _entry__vnumber = 43152
    _entry__vsigned = 51472
    _entry__vstring = 51824
    _entry__vunsigned = 51840
)

const (
    _stack__f32toa = 56
    _stack__f64toa = 72
    _stack__get_by_path = 312
    _stack__fsm_exec_1 = 152
    _stack__skip_string_1 = 48
    _stack__skip_one_fast_1 = 176
    _stack__html_escape = 72
    _stack__i64toa = 16
    _stack__u64toa_1 = 8
    _stack__lspace = 8
    _stack__quote = 72
    _stack__skip_array = 160
    _stack__skip_number = 88
    _stack__skip_number_1 = 80
    _stack__skip_object = 160
    _stack__skip_one = 160
    _stack__skip_one_fast = 184
    _stack__u64toa = 16
    _stack__unquote = 80
    _stack__validate_one = 160
    _stack__validate_utf8 = 48
    _stack__validate_utf8_fast = 176
    _stack__value = 224
    _stack__vstring_1 = 72
    _stack__vnumber_1 = 168
    _stack__atof_eisel_lemire64_1 = 32
    _stack__vnumber = 176
    _stack__vsigned = 16
    _stack__vstring = 80
    _stack__vunsigned = 24
)

const (
    _size__f32toa = 3664
    _size__f64toa = 5040
    _size__get_by_path = 6032
    _size__fsm_exec_1 = 5020
    _size__skip_string_1 = 1760
    _size__skip_one_fast_1 = 2836
    _size__html_escape = 2016
    _size__i64toa = 64
    _size__u64toa_1 = 1200
    _size__lspace = 256
    _size__quote = 2688
    _size__skip_array = 64
    _size__skip_number = 48
    _size__skip_number_1 = 1460
    _size__skip_object = 48
    _size__skip_one = 48
    _size__skip_one_fast = 16
    _size__u64toa = 16
    _size__unquote = 2080
    _size__validate_one = 48
    _size__validate_utf8 = 688
    _size__validate_utf8_fast = 2672
    _size__value = 1228
    _size__vstring_1 = 1808
    _size__vnumber_1 = 8176
    _size__atof_eisel_lemire64_1 = 372
    _size__vnumber = 32
    _size__vsigned = 352
    _size__vstring = 16
    _size__vunsigned = 352
)

var (
    _pcsp__f32toa = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {3620, 56},
        {3624, 48},
        {3625, 40},
        {3627, 32},
        {3629, 24},
        {3631, 16},
        {3633, 8},
        {3637, 0},
        {3663, 56},
    }
    _pcsp__f64toa = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {4935, 72},
        {4939, 48},
        {4940, 40},
        {4942, 32},
        {4944, 24},
        {4946, 16},
        {4948, 8},
        {4952, 0},
        {5030, 72},
    }
    _pcsp__get_by_path = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {5926, 136},
        {5930, 48},
        {5931, 40},
        {5933, 32},
        {5935, 24},
        {5937, 16},
        {5939, 8},
        {5943, 0},
        {6019, 136},
    }
    _pcsp__fsm_exec_1 = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {4643, 104},
        {4647, 48},
        {4648, 40},
        {4650, 32},
        {4652, 24},
        {4654, 16},
        {4656, 8},
        {4660, 0},
        {5020, 104},
    }
    _pcsp__skip_string_1 = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {741, 48},
        {742, 40},
        {744, 32},
        {746, 24},
        {748, 16},
        {750, 8},
        {754, 0},
        {1751, 48},
    }
    _pcsp__skip_one_fast_1 = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {827, 176},
        {828, 168},
        {830, 160},
        {832, 152},
        {834, 144},
        {836, 136},
        {840, 128},
        {2836, 176},
    }
    _pcsp__html_escape = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {1998, 72},
        {2002, 48},
        {2003, 40},
        {2005, 32},
        {2007, 24},
        {2009, 16},
        {2011, 8},
        {2016, 0},
    }
    _pcsp__i64toa = [][2]uint32{
        {14, 0},
        {34, 8},
        {36, 0},
    }
    _pcsp__u64toa_1 = [][2]uint32{
        {1, 0},
        {161, 8},
        {162, 0},
        {424, 8},
        {425, 0},
        {722, 8},
        {723, 0},
        {1168, 8},
        {1170, 0},
    }
    _pcsp__lspace = [][2]uint32{
        {1, 0},
        {185, 8},
        {189, 0},
        {206, 8},
        {210, 0},
        {217, 8},
        {221, 0},
        {239, 8},
    }
    _pcsp__quote = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {2630, 72},
        {2634, 48},
        {2635, 40},
        {2637, 32},
        {2639, 24},
        {2641, 16},
        {2643, 8},
        {2647, 0},
        {2678, 72},
    }
    _pcsp__skip_array = [][2]uint32{
        {1, 0},
        {28, 8},
        {34, 0},
    }
    _pcsp__skip_number = [][2]uint32{
        {1, 0},
        {17, 8},
        {23, 0},
    }
    _pcsp__skip_number_1 = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {1398, 80},
        {1402, 48},
        {1403, 40},
        {1405, 32},
        {1407, 24},
        {1409, 16},
        {1411, 8},
        {1415, 0},
        {1460, 80},
    }
    _pcsp__skip_object = [][2]uint32{
        {1, 0},
        {28, 8},
        {34, 0},
    }
    _pcsp__skip_one = [][2]uint32{
        {1, 0},
        {28, 8},
        {34, 0},
    }
    _pcsp__skip_one_fast = [][2]uint32{
        {1, 0},
        {4, 8},
        {10, 0},
    }
    _pcsp__u64toa = [][2]uint32{
        {1, 0},
        {4, 8},
        {10, 0},
    }
    _pcsp__unquote = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {1519, 80},
        {1523, 48},
        {1524, 40},
        {1526, 32},
        {1528, 24},
        {1530, 16},
        {1532, 8},
        {1536, 0},
        {2079, 80},
    }
    _pcsp__validate_one = [][2]uint32{
        {1, 0},
        {33, 8},
        {39, 0},
    }
    _pcsp__validate_utf8 = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {11, 40},
        {623, 48},
        {627, 40},
        {628, 32},
        {630, 24},
        {632, 16},
        {634, 8},
        {635, 0},
        {666, 48},
    }
    _pcsp__validate_utf8_fast = [][2]uint32{
        {1, 0},
        {4, 8},
        {5, 16},
        {2058, 176},
        {2059, 168},
        {2063, 160},
        {2355, 176},
        {2356, 168},
        {2360, 160},
        {2650, 176},
    }
    _pcsp__value = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {7, 24},
        {1182, 56},
        {1186, 24},
        {1187, 16},
        {1189, 8},
        {1193, 0},
        {1228, 56},
    }
    _pcsp__vstring_1 = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {1623, 72},
        {1627, 48},
        {1628, 40},
        {1630, 32},
        {1632, 24},
        {1634, 16},
        {1636, 8},
        {1640, 0},
        {1796, 72},
    }
    _pcsp__vnumber_1 = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {790, 136},
        {794, 48},
        {795, 40},
        {797, 32},
        {799, 24},
        {801, 16},
        {803, 8},
        {807, 0},
        {8168, 136},
    }
    _pcsp__atof_eisel_lemire64_1 = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {302, 32},
        {303, 24},
        {305, 16},
        {307, 8},
        {308, 0},
        {372, 32},
    }
    _pcsp__vnumber = [][2]uint32{
        {1, 0},
        {20, 8},
        {26, 0},
    }
    _pcsp__vsigned = [][2]uint32{
        {1, 0},
        {4, 8},
        {112, 16},
        {113, 8},
        {114, 0},
        {125, 16},
        {126, 8},
        {127, 0},
        {276, 16},
        {277, 8},
        {278, 0},
        {282, 16},
        {283, 8},
        {284, 0},
        {322, 16},
        {323, 8},
        {324, 0},
        {335, 16},
        {336, 8},
        {338, 0},
    }
    _pcsp__vstring = [][2]uint32{
        {1, 0},
        {4, 8},
        {10, 0},
    }
    _pcsp__vunsigned = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {74, 24},
        {75, 16},
        {77, 8},
        {78, 0},
        {89, 24},
        {90, 16},
        {92, 8},
        {93, 0},
        {116, 24},
        {117, 16},
        {119, 8},
        {120, 0},
        {279, 24},
        {280, 16},
        {282, 8},
        {283, 0},
        {321, 24},
        {322, 16},
        {324, 8},
        {325, 0},
        {332, 24},
        {333, 16},
        {335, 8},
        {337, 0},
    }
)

var Funcs = []loader.CFunc{
    {"__native_entry__", 0, 67, 0, nil},
    {"_f32toa", _entry__f32toa, _size__f32toa, _stack__f32toa, _pcsp__f32toa},
    {"_f64toa", _entry__f64toa, _size__f64toa, _stack__f64toa, _pcsp__f64toa},
    {"_get_by_path", _entry__get_by_path, _size__get_by_path, _stack__get_by_path, _pcsp__get_by_path},
    {"_fsm_exec_1", _entry__fsm_exec_1, _size__fsm_exec_1, _stack__fsm_exec_1, _pcsp__fsm_exec_1},
    {"_skip_string_1", _entry__skip_string_1, _size__skip_string_1, _stack__skip_string_1, _pcsp__skip_string_1},
    {"_skip_one_fast_1", _entry__skip_one_fast_1, _size__skip_one_fast_1, _stack__skip_one_fast_1, _pcsp__skip_one_fast_1},
    {"_html_escape", _entry__html_escape, _size__html_escape, _stack__html_escape, _pcsp__html_escape},
    {"_i64toa", _entry__i64toa, _size__i64toa, _stack__i64toa, _pcsp__i64toa},
    {"_u64toa_1", _entry__u64toa_1, _size__u64toa_1, _stack__u64toa_1, _pcsp__u64toa_1},
    {"_lspace", _entry__lspace, _size__lspace, _stack__lspace, _pcsp__lspace},
    {"_quote", _entry__quote, _size__quote, _stack__quote, _pcsp__quote},
    {"_skip_array", _entry__skip_array, _size__skip_array, _stack__skip_array, _pcsp__skip_array},
    {"_skip_number", _entry__skip_number, _size__skip_number, _stack__skip_number, _pcsp__skip_number},
    {"_skip_number_1", _entry__skip_number_1, _size__skip_number_1, _stack__skip_number_1, _pcsp__skip_number_1},
    {"_skip_object", _entry__skip_object, _size__skip_object, _stack__skip_object, _pcsp__skip_object},
    {"_skip_one", _entry__skip_one, _size__skip_one, _stack__skip_one, _pcsp__skip_one},
    {"_skip_one_fast", _entry__skip_one_fast, _size__skip_one_fast, _stack__skip_one_fast, _pcsp__skip_one_fast},
    {"_u64toa", _entry__u64toa, _size__u64toa, _stack__u64toa, _pcsp__u64toa},
    {"_unquote", _entry__unquote, _size__unquote, _stack__unquote, _pcsp__unquote},
    {"_validate_one", _entry__validate_one, _size__validate_one, _stack__validate_one, _pcsp__validate_one},
    {"_validate_utf8", _entry__validate_utf8, _size__validate_utf8, _stack__validate_utf8, _pcsp__validate_utf8},
    {"_validate_utf8_fast", _entry__validate_utf8_fast, _size__validate_utf8_fast, _stack__validate_utf8_fast, _pcsp__validate_utf8_fast},
    {"_value", _entry__value, _size__value, _stack__value, _pcsp__value},
    {"_vstring_1", _entry__vstring_1, _size__vstring_1, _stack__vstring_1, _pcsp__vstring_1},
    {"_vnumber_1", _entry__vnumber_1, _size__vnumber_1, _stack__vnumber_1, _pcsp__vnumber_1},
    {"_atof_eisel_lemire64_1", _entry__atof_eisel_lemire64_1, _size__atof_eisel_lemire64_1, _stack__atof_eisel_lemire64_1, _pcsp__atof_eisel_lemire64_1},
    {"_vnumber", _entry__vnumber, _size__vnumber, _stack__vnumber, _pcsp__vnumber},
    {"_vsigned", _entry__vsigned, _size__vsigned, _stack__vsigned, _pcsp__vsigned},
    {"_vstring", _entry__vstring, _size__vstring, _stack__vstring, _pcsp__vstring},
    {"_vunsigned", _entry__vunsigned, _size__vunsigned, _stack__vunsigned, _pcsp__vunsigned},
}
