// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__skip_number = 336
)

const (
    _stack__skip_number = 88
)

const (
    _size__skip_number = 1528
)

var (
    _pcsp__skip_number = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {1463, 88},
        {1467, 48},
        {1468, 40},
        {1470, 32},
        {1472, 24},
        {1474, 16},
        {1476, 8},
        {1480, 0},
        {1528, 88},
    }
)

var _cfunc_skip_number = []loader.CFunc{
    {"_skip_number_entry", 0,  _entry__skip_number, 0, nil},
    {"_skip_number", _entry__skip_number, _size__skip_number, _stack__skip_number, _pcsp__skip_number},
}
