// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__skip_one = 480
)

const (
    _stack__skip_one = 96
)

const (
    _size__skip_one = 10056
)

var (
    _pcsp__skip_one = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x2529, 96},
        {0x252a, 48},
        {0x252c, 40},
        {0x252e, 32},
        {0x2530, 24},
        {0x2532, 16},
        {0x2533, 8},
        {0x2537, 0},
        {0x2748, 96},
    }
)

var _cfunc_skip_one = []loader.CFunc{
    {"_skip_one_entry", 0,  _entry__skip_one, 0, nil},
    {"_skip_one", _entry__skip_one, _size__skip_one, _stack__skip_one, _pcsp__skip_one},
}
