// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__unquote = 48
)

const (
    _stack__unquote = 72
)

const (
    _size__unquote = 3280
)

var (
    _pcsp__unquote = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x9c5, 72},
        {0x9c6, 48},
        {0x9c8, 40},
        {0x9ca, 32},
        {0x9cc, 24},
        {0x9ce, 16},
        {0x9cf, 8},
        {0x9d3, 0},
        {0xcd0, 72},
    }
)

var _cfunc_unquote = []loader.CFunc{
    {"_unquote_entry", 0,  _entry__unquote, 0, nil},
    {"_unquote", _entry__unquote, _size__unquote, _stack__unquote, _pcsp__unquote},
}
