// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__value = 576
)

const (
    _stack__value = 128
)

const (
    _size__value = 12424
)

var (
    _pcsp__value = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x10e6, 128},
        {0x10e7, 48},
        {0x10e9, 40},
        {0x10eb, 32},
        {0x10ed, 24},
        {0x10ef, 16},
        {0x10f0, 8},
        {0x10f4, 0},
        {0x3088, 128},
    }
)

var _cfunc_value = []loader.CFunc{
    {"_value_entry", 0,  _entry__value, 0, nil},
    {"_value", _entry__value, _size__value, _stack__value, _pcsp__value},
}
