// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__vnumber = 128
)

const (
    _stack__vnumber = 136
)

const (
    _size__vnumber = 8496
)

var (
    _pcsp__vnumber = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {8475, 136},
        {8479, 48},
        {8480, 40},
        {8482, 32},
        {8484, 24},
        {8486, 16},
        {8488, 8},
        {8496, 0},
    }
)

var _cfunc_vnumber = []loader.CFunc{
    {"_vnumber_entry", 0,  _entry__vnumber, 0, nil},
    {"_vnumber", _entry__vnumber, _size__vnumber, _stack__vnumber, _pcsp__vnumber},
}
