// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__vstring = 96
)

const (
    _stack__vstring = 72
)

const (
    _size__vstring = 1832
)

var (
    _pcsp__vstring = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x677, 72},
        {0x678, 48},
        {0x67a, 40},
        {0x67c, 32},
        {0x67e, 24},
        {0x680, 16},
        {0x681, 8},
        {0x685, 0},
        {0x728, 72},
    }
)

var _cfunc_vstring = []loader.CFunc{
    {"_vstring_entry", 0,  _entry__vstring, 0, nil},
    {"_vstring", _entry__vstring, _size__vstring, _stack__vstring, _pcsp__vstring},
}
