// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sve_wrapgoc

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__f64toa = 0
)

const (
    _stack__f64toa = 32
)

const (
    _size__f64toa = 14184
)

var (
    _pcsp__f64toa = [][2]uint32{
        {0x1, 0},
        {0x200, 32},
        {0x204, 0},
        {0x594, 32},
        {0x598, 0},
        {0x5ac, 32},
        {0x5b0, 0},
        {0x8a8, 32},
        {0x8ac, 0},
        {0xa78, 32},
        {0xa7c, 0},
        {0xaa4, 32},
        {0xaa8, 0},
        {0xac0, 32},
        {0xac4, 0},
        {0xf24, 32},
        {0xf28, 0},
        {0xf98, 32},
        {0xf9c, 0},
        {0x3768, 32},
    }
)

var _cfunc_f64toa = []loader.CFunc{
    {"_f64toa_entry", 0,  _entry__f64toa, 0, nil},
    {"_f64toa", _entry__f64toa, _size__f64toa, _stack__f64toa, _pcsp__f64toa},
}
