//go:build !noasm || !appengine
// +build !noasm !appengine

// Code generated by asm2asm_tool, DO NOT EDIT.

package sve_wrapgoc

import (
	"github.com/bytedance/sonic/loader"
)

const (
	_entry__quote = 0
)

const (
	_stack__quote = 80
)

const (
	_size__quote = 10624
)

var (
	_pcsp__quote = [][2]uint32{
		{0x1, 0},
		{0xc, 32},
		{0x10, 64},
		{0x834, 80},
		{0x838, 64},
		{0x840, 32},
		{0x844, 0},
		{0x2980, 80},
	}
)

var _cfunc_quote = []loader.CFunc{
	{"_quote_entry", 0, _entry__quote, 0, nil},
	{"_quote", _entry__quote, _size__quote, _stack__quote, _pcsp__quote},
}
