name: Go Latest Linux-X64

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [arm, X64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clear repository
        run: sudo rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE

      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: build go
        run: sh ./scripts/go_latest.sh go1.23
        continue-on-error: true

      - name: test
        run: |
          PWD=$(pwd)
          export GOROOT=$PWD/go1.23
          export PATH=$GOROOT/bin:$PATH
          go version
          GOMAXPROCS=4 go test -v -race .
          GOMAXPROCS=4 go test -v -race github.com/bytedance/sonic/ast
          GOMAXPROCS=4 go test -v -race github.com/bytedance/sonic/encoder
          GOMAXPROCS=4 go test -v -race github.com/bytedance/sonic/decoder
          GOMAXPROCS=4 go test -v -race github.com/bytedance/sonic/issue_test


