// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__f32toa = 16
)

const (
    _stack__f32toa = 64
)

const (
    _size__f32toa = 3632
)

var (
    _pcsp__f32toa = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x92a, 64},
        {0x92b, 48},
        {0x92d, 40},
        {0x92f, 32},
        {0x931, 24},
        {0x933, 16},
        {0x934, 8},
        {0x935, 0},
        {0xe30, 64},
    }
)

var _cfunc_f32toa = []loader.CFunc{
    {"_f32toa_entry", 0,  _entry__f32toa, 0, nil},
    {"_f32toa", _entry__f32toa, _size__f32toa, _stack__f32toa, _pcsp__f32toa},
}
