// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

//go:nosplit
//go:noescape
//goland:noinspection ALL
func _f32toa_entry() uintptr

var (
    _subr__f32toa uintptr = _f32toa_entry() + 32
)

const (
    _stack__f32toa = 56
)

var (
    _ = _subr__f32toa
)

const (
    _ = _stack__f32toa
)
