// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__get_by_path = 240
)

const (
    _stack__get_by_path = 200
)

const (
    _size__get_by_path = 22052
)

var (
    _pcsp__get_by_path = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x14, 48},
        {0x3069, 200},
        {0x306a, 48},
        {0x306c, 40},
        {0x306e, 32},
        {0x3070, 24},
        {0x3072, 16},
        {0x3073, 8},
        {0x3074, 0},
        {0x5624, 200},
    }
)

var _cfunc_get_by_path = []loader.CFunc{
    {"_get_by_path_entry", 0,  _entry__get_by_path, 0, nil},
    {"_get_by_path", _entry__get_by_path, _size__get_by_path, _stack__get_by_path, _pcsp__get_by_path},
}
