// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __get_by_path_entry() uintptr

var (
    _subr__get_by_path uintptr = __get_by_path_entry() + 272
)

const (
    _stack__get_by_path = 216
)

var (
    _ = _subr__get_by_path
)

const (
    _ = _stack__get_by_path
)
