// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __i64toa_entry() uintptr

var (
    _subr__i64toa uintptr = __i64toa_entry() + 112
)

const (
    _stack__i64toa = 8
)

var (
    _ = _subr__i64toa
)

const (
    _ = _stack__i64toa
)
