// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

import (
`github.com/bytedance/sonic/internal/rt`
)

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __lspace_entry() uintptr

var (
    _subr__lspace uintptr = rt.GetFuncPC(__lspace_entry) + 16
)

const (
    _stack__lspace = 8
)

var (
    _ = _subr__lspace
)

const (
    _ = _stack__lspace
)
