// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__skip_one = 256
)

const (
    _stack__skip_one = 216
)

const (
    _size__skip_one = 13784
)

var (
    _pcsp__skip_one = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x14, 48},
        {0x33d5, 216},
        {0x33d6, 48},
        {0x33d8, 40},
        {0x33da, 32},
        {0x33dc, 24},
        {0x33de, 16},
        {0x33df, 8},
        {0x33e0, 0},
        {0x35d8, 216},
    }
)

var _cfunc_skip_one = []loader.CFunc{
    {"_skip_one_entry", 0,  _entry__skip_one, 0, nil},
    {"_skip_one", _entry__skip_one, _size__skip_one, _stack__skip_one, _pcsp__skip_one},
}
