// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __skip_one_entry() uintptr

var (
    _subr__skip_one uintptr = __skip_one_entry() + 192
)

const (
    _stack__skip_one = 160
)

var (
    _ = _subr__skip_one
)

const (
    _ = _stack__skip_one
)
