// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__unquote = 16
)

const (
    _stack__unquote = 72
)

const (
    _size__unquote = 3120
)

var (
    _pcsp__unquote = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x8, 16},
        {0xa, 24},
        {0xc, 32},
        {0xd, 40},
        {0x11, 48},
        {0x982, 72},
        {0x983, 48},
        {0x985, 40},
        {0x987, 32},
        {0x989, 24},
        {0x98b, 16},
        {0x98c, 8},
        {0x98d, 0},
        {0xc30, 72},
    }
)

var _cfunc_unquote = []loader.CFunc{
    {"_unquote_entry", 0,  _entry__unquote, 0, nil},
    {"_unquote", _entry__unquote, _size__unquote, _stack__unquote, _pcsp__unquote},
}
