// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __vnumber_entry() uintptr

var (
    _subr__vnumber uintptr = __vnumber_entry() + 80
)

const (
    _stack__vnumber = 112
)

var (
    _ = _subr__vnumber
)

const (
    _ = _stack__vnumber
)
