// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__vunsigned = 0
)

const (
    _stack__vunsigned = 24
)

const (
    _size__vunsigned = 340
)

var (
    _pcsp__vunsigned = [][2]uint32{
        {0x1, 0},
        {0x6, 8},
        {0x7, 16},
        {0x49, 24},
        {0x4b, 16},
        {0x4c, 8},
        {0x4d, 0},
        {0x58, 24},
        {0x5a, 16},
        {0x5b, 8},
        {0x5c, 0},
        {0x73, 24},
        {0x75, 16},
        {0x76, 8},
        {0x77, 0},
        {0x11a, 24},
        {0x11c, 16},
        {0x11d, 8},
        {0x11e, 0},
        {0x144, 24},
        {0x146, 16},
        {0x147, 8},
        {0x148, 0},
        {0x150, 24},
        {0x152, 16},
        {0x153, 8},
        {0x154, 0},
    }
)

var _cfunc_vunsigned = []loader.CFunc{
    {"_vunsigned_entry", 0,  _entry__vunsigned, 0, nil},
    {"_vunsigned", _entry__vunsigned, _size__vunsigned, _stack__vunsigned, _pcsp__vunsigned},
}
