// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

import (
`github.com/bytedance/sonic/internal/rt`
)

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __vunsigned_entry() uintptr

var (
    _subr__vunsigned uintptr = rt.GetFuncPC(__vunsigned_entry) + 30
)

const (
    _stack__vunsigned = 8
)

var (
    _ = _subr__vunsigned
)

const (
    _ = _stack__vunsigned
)
