// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package sse

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __vunsigned_entry() uintptr

var (
    _subr__vunsigned uintptr = __vunsigned_entry() + 32
)

const (
    _stack__vunsigned = 8
)

var (
    _ = _subr__vunsigned
)

const (
    _ = _stack__vunsigned
)
