//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__get_by_path_entry__(SB), NOSPLIT, $208
        NO_LOCAL_POINTERS
        WORD $0x100000a0 // adr x0, .+20
        MOVD R0, ret(FP)
        RET
          // .p2align 4, 0x00

LCPI0_0:
    WORD $0x08040201
    WORD $0x80402010
    WORD $0x08040201
    WORD $0x80402010
LCPI0_1:
    WORD $0x09010800
    WORD $0x0b030a02
    WORD $0x0d050c04
    WORD $0x0f070e06
LCPI0_2:
    WORD $0x11111111; WORD $0x11111111
    WORD $0x22222222; WORD $0x22222222
LCPI0_3:
    WORD $0x22222222; WORD $0x22222222
    WORD $0x88888888; WORD $0x88888888
LCPI0_4:
    WORD $0x22222222; WORD $0x22222222
    WORD $0x11111111; WORD $0x11111111
LCPI0_5:
    WORD $0x11111111; WORD $0x11111111
    WORD $0x88888888; WORD $0x08888888
LCPI0_6:
    WORD $0x88888888; WORD $0x08888888
    WORD $0x44444444; WORD $0x04444444
LCPI0_7:
    WORD $0x88888888; WORD $0x08888888
    WORD $0x11111111; WORD $0x11111111
LCPI0_8:
    WORD $0x44444444; WORD $0x04444444
    WORD $0x22222222; WORD $0x02222222
LCPI0_9:
    WORD $0x44444444; WORD $0x44444444
    WORD $0x88888888; WORD $0x88888888
LCPI0_10:
    WORD $0x00000001; WORD $0x00000000
    WORD $0x00000000; WORD $0x00000000
get_by_path:
    WORD $0xd10303ff // sub    sp, sp, #192
    WORD $0xf940044a // ldr    x10, [x2, #8]
    WORD $0xfd0023ec // str    d12, [sp, #64]
    WORD $0x6d04abeb // stp    d11, d10, [sp, #72]
    WORD $0x6d05a3e9 // stp    d9, d8, [sp, #88]
    WORD $0xf90037fd // str    x29, [sp, #104]
    WORD $0xa9076ffe // stp    x30, x27, [sp, #112]
    WORD $0xa90867fa // stp    x26, x25, [sp, #128]
    WORD $0xa9095ff8 // stp    x24, x23, [sp, #144]
    WORD $0xa90a57f6 // stp    x22, x21, [sp, #160]
    WORD $0xa90b4ff4 // stp    x20, x19, [sp, #176]
    CMP $0, R10
    BEQ LBB0_482
    ADR LCPI0_1, R14
    ADR LCPI0_0, R13
    ADR LCPI0_4, R15
    WORD $0xf9400048 // ldr    x8, [x2]
    ADR LCPI0_8, R17
    WORD $0x910003e9 // mov    x9, sp
    WORD $0x3dc001c2 // ldr    q2, [x14, :lo12:.LCPI0_1]
    ADR LCPI0_3, R14
    WORD $0x3dc001a0 // ldr    q0, [x13, :lo12:.LCPI0_0]
    ADR LCPI0_2, R13
    WORD $0x3dc001f1 // ldr    q17, [x15, :lo12:.LCPI0_4]
    ADR LCPI0_7, R15
    WORD $0x3dc001d0 // ldr    q16, [x14, :lo12:.LCPI0_3]
    ADR LCPI0_6, R14
    WORD $0x3dc001a7 // ldr    q7, [x13, :lo12:.LCPI0_2]
    ADR LCPI0_5, R13
    WORD $0xd284c00c // mov    x12, #9728
    WORD $0xf9400010 // ldr    x16, [x0]
    WORD $0x3dc001d3 // ldr    q19, [x14, :lo12:.LCPI0_6]
    ADR LCPI0_9, R14
    WORD $0x4f01e441 // movi    v1.16b, #34
    WORD $0x3dc001b2 // ldr    q18, [x13, :lo12:.LCPI0_5]
    WORD $0x4f02e783 // movi    v3.16b, #92
    WORD $0xd284c00d // mov    x13, #9728
    WORD $0x4f01e584 // movi    v4.16b, #44
    WORD $0xf9400032 // ldr    x18, [x1]
    WORD $0x4f06e7e5 // movi    v5.16b, #223
    WORD $0x91008129 // add    x9, x9, #32
    WORD $0x4f02e7a6 // movi    v6.16b, #93
    WORD $0x8b0a110a // add    x10, x8, x10, lsl #4
    WORD $0x4f02e494 // movi    v20.16b, #68
    WORD $0x5280002b // mov    w11, #1
    WORD $0x4f02e777 // movi    v23.16b, #91
    WORD $0xf2c0002c // movk    x12, #1, lsl #32
    WORD $0x6f00e418 // movi    v24.2d, #0000000000000000
    WORD $0xf2c2002d // movk    x13, #4097, lsl #32
    WORD $0x4f03e779 // movi    v25.16b, #123
    WORD $0x3dc001f5 // ldr    q21, [x15, :lo12:.LCPI0_7]
    WORD $0x4f03e7ba // movi    v26.16b, #125
    WORD $0x3dc00236 // ldr    q22, [x17, :lo12:.LCPI0_8]
    WORD $0x3dc001db // ldr    q27, [x14, :lo12:.LCPI0_9]
    WORD $0x529fffee // mov    w14, #65535
    ADR _UnquoteTab, R15
    WORD $0x910001ef // add    x15, x15, :lo12:_UnquoteTab
    WORD $0x25d8e040 // ptrue    p0.d, vl2
LBB0_2:
    WORD $0xf9400411 // ldr    x17, [x0, #8]
    WORD $0xeb11025f // cmp    x18, x17
    BHS LBB0_7
    WORD $0x38726a02 // ldrb    w2, [x16, x18]
    WORD $0x7100345f // cmp    w2, #13
    BEQ LBB0_7
    WORD $0x7100805f // cmp    w2, #32
    BEQ LBB0_7
    WORD $0x51002c42 // sub    w2, w2, #11
    WORD $0x3100085f // cmn    w2, #2
    BHS LBB0_7
    WORD $0xaa1203e4 // mov    x4, x18
    B LBB0_25
LBB0_7:
    WORD $0x91000644 // add    x4, x18, #1
    WORD $0xeb11009f // cmp    x4, x17
    BHS LBB0_11
    WORD $0x38646a02 // ldrb    w2, [x16, x4]
    WORD $0x7100345f // cmp    w2, #13
    BEQ LBB0_11
    WORD $0x7100805f // cmp    w2, #32
    BEQ LBB0_11
    WORD $0x51002c42 // sub    w2, w2, #11
    WORD $0x3100085f // cmn    w2, #2
    BLO LBB0_25
LBB0_11:
    WORD $0x91000a44 // add    x4, x18, #2
    WORD $0xeb11009f // cmp    x4, x17
    BHS LBB0_15
    WORD $0x38646a02 // ldrb    w2, [x16, x4]
    WORD $0x7100345f // cmp    w2, #13
    BEQ LBB0_15
    WORD $0x7100805f // cmp    w2, #32
    BEQ LBB0_15
    WORD $0x51002c42 // sub    w2, w2, #11
    WORD $0x3100085f // cmn    w2, #2
    BLO LBB0_25
LBB0_15:
    WORD $0x91000e44 // add    x4, x18, #3
    WORD $0xeb11009f // cmp    x4, x17
    BHS LBB0_19
    WORD $0x38646a02 // ldrb    w2, [x16, x4]
    WORD $0x7100345f // cmp    w2, #13
    BEQ LBB0_19
    WORD $0x7100805f // cmp    w2, #32
    BEQ LBB0_19
    WORD $0x51002c42 // sub    w2, w2, #11
    WORD $0x3100085f // cmn    w2, #2
    BLO LBB0_25
LBB0_19:
    WORD $0x91001244 // add    x4, x18, #4
    WORD $0xeb11009f // cmp    x4, x17
    BHS LBB0_23
LBB0_20:
    WORD $0x38646a02 // ldrb    w2, [x16, x4]
    WORD $0x9ac22165 // lsl    x5, x11, x2
    WORD $0x7100805f // cmp    w2, #32
    WORD $0x8a0c00a2 // and    x2, x5, x12
    WORD $0xfa409844 // ccmp    x2, #0, #4, ls
    BEQ LBB0_24
    WORD $0x91000484 // add    x4, x4, #1
    WORD $0xeb04023f // cmp    x17, x4
    BNE LBB0_20
LBB0_22:
    WORD $0x2a1f03f1 // mov    w17, wzr
    B LBB0_26
LBB0_23:
    WORD $0x2a1f03f1 // mov    w17, wzr
    WORD $0xf9000024 // str    x4, [x1]
    B LBB0_27
LBB0_24:
    WORD $0xeb11009f // cmp    x4, x17
    BHS LBB0_22
LBB0_25:
    WORD $0x91000492 // add    x18, x4, #1
    WORD $0xf9000032 // str    x18, [x1]
    WORD $0x38646a11 // ldrb    w17, [x16, x4]
LBB0_26:
    WORD $0xaa1203e4 // mov    x4, x18
LBB0_27:
    WORD $0xf9400112 // ldr    x18, [x8]
    CMP $0, R18_PLATFORM
    BEQ LBB0_808
    WORD $0x39405e52 // ldrb    w18, [x18, #23]
    WORD $0x12001252 // and    w18, w18, #0x1f
    WORD $0x71000a5f // cmp    w18, #2
    BEQ LBB0_298
    WORD $0x7100625f // cmp    w18, #24
    BNE LBB0_808
    WORD $0x7101ee3f // cmp    w17, #123
    BNE LBB0_865
    WORD $0xf9400010 // ldr    x16, [x0]
LBB0_32:
    WORD $0xf9400411 // ldr    x17, [x0, #8]
    WORD $0xeb11009f // cmp    x4, x17
    BHS LBB0_37
    WORD $0x38646a12 // ldrb    w18, [x16, x4]
    WORD $0x7100365f // cmp    w18, #13
    BEQ LBB0_37
    WORD $0x7100825f // cmp    w18, #32
    BEQ LBB0_37
    WORD $0x51002e52 // sub    w18, w18, #11
    WORD $0x31000a5f // cmn    w18, #2
    BHS LBB0_37
    WORD $0xaa0403e2 // mov    x2, x4
    B LBB0_53
LBB0_37:
    WORD $0x91000482 // add    x2, x4, #1
    WORD $0xeb11005f // cmp    x2, x17
    BHS LBB0_41
    WORD $0x38626a12 // ldrb    w18, [x16, x2]
    WORD $0x7100365f // cmp    w18, #13
    BEQ LBB0_41
    WORD $0x7100825f // cmp    w18, #32
    BEQ LBB0_41
    WORD $0x51002e52 // sub    w18, w18, #11
    WORD $0x31000a5f // cmn    w18, #2
    BLO LBB0_53
LBB0_41:
    WORD $0x91000882 // add    x2, x4, #2
    WORD $0xeb11005f // cmp    x2, x17
    BHS LBB0_45
    WORD $0x38626a12 // ldrb    w18, [x16, x2]
    WORD $0x7100365f // cmp    w18, #13
    BEQ LBB0_45
    WORD $0x7100825f // cmp    w18, #32
    BEQ LBB0_45
    WORD $0x51002e52 // sub    w18, w18, #11
    WORD $0x31000a5f // cmn    w18, #2
    BLO LBB0_53
LBB0_45:
    WORD $0x91000c82 // add    x2, x4, #3
    WORD $0xeb11005f // cmp    x2, x17
    BHS LBB0_49
    WORD $0x38626a12 // ldrb    w18, [x16, x2]
    WORD $0x7100365f // cmp    w18, #13
    BEQ LBB0_49
    WORD $0x7100825f // cmp    w18, #32
    BEQ LBB0_49
    WORD $0x51002e52 // sub    w18, w18, #11
    WORD $0x31000a5f // cmn    w18, #2
    BLO LBB0_53
LBB0_49:
    WORD $0x91001082 // add    x2, x4, #4
    WORD $0xeb11005f // cmp    x2, x17
    BHS LBB0_809
LBB0_50:
    WORD $0x38626a12 // ldrb    w18, [x16, x2]
    WORD $0x9ad22164 // lsl    x4, x11, x18
    WORD $0x7100825f // cmp    w18, #32
    WORD $0x8a0c0092 // and    x18, x4, x12
    WORD $0xfa409a44 // ccmp    x18, #0, #4, ls
    BEQ LBB0_52
    WORD $0x91000442 // add    x2, x2, #1
    WORD $0xeb02023f // cmp    x17, x2
    BNE LBB0_50
    B LBB0_865
LBB0_52:
    WORD $0xeb11005f // cmp    x2, x17
    BHS LBB0_865
LBB0_53:
    WORD $0x91000454 // add    x20, x2, #1
    WORD $0xf9000034 // str    x20, [x1]
    WORD $0x38626a11 // ldrb    w17, [x16, x2]
    WORD $0x71008a3f // cmp    w17, #34
    BNE LBB0_864
    WORD $0xf9400405 // ldr    x5, [x0, #8]
    WORD $0xeb1400a7 // subs    x7, x5, x20
    BEQ LBB0_934
    WORD $0xf9400511 // ldr    x17, [x8, #8]
    WORD $0xf10100ff // cmp    x7, #64
    WORD $0xa9401232 // ldp    x18, x4, [x17]
    WORD $0x8b140211 // add    x17, x16, x20
    BLO LBB0_260
    WORD $0xaa1f03f3 // mov    x19, xzr
    WORD $0x92800006 // mov    x6, #-1
LBB0_57:
    WORD $0x8b140215 // add    x21, x16, x20
    WORD $0xad4076bc // ldp    q28, q29, [x21]
    WORD $0x6e218f88 // cmeq    v8.16b, v28.16b, v1.16b
    WORD $0x6e238f9c // cmeq    v28.16b, v28.16b, v3.16b
    WORD $0xad417ebe // ldp    q30, q31, [x21, #32]
    WORD $0x6e218fa9 // cmeq    v9.16b, v29.16b, v1.16b
    WORD $0x6e238fbd // cmeq    v29.16b, v29.16b, v3.16b
    WORD $0x4e201d29 // and    v9.16b, v9.16b, v0.16b
    WORD $0x6e218fca // cmeq    v10.16b, v30.16b, v1.16b
    WORD $0x6e238fde // cmeq    v30.16b, v30.16b, v3.16b
    WORD $0x6e218feb // cmeq    v11.16b, v31.16b, v1.16b
    WORD $0x4e201d4a // and    v10.16b, v10.16b, v0.16b
    WORD $0x4e201fbd // and    v29.16b, v29.16b, v0.16b
    WORD $0x4e201d6b // and    v11.16b, v11.16b, v0.16b
    WORD $0x4e02014a // tbl    v10.16b, { v10.16b }, v2.16b
    WORD $0x6e238fff // cmeq    v31.16b, v31.16b, v3.16b
    WORD $0x4e0203bd // tbl    v29.16b, { v29.16b }, v2.16b
    WORD $0x4e201fde // and    v30.16b, v30.16b, v0.16b
    WORD $0x4e02016b // tbl    v11.16b, { v11.16b }, v2.16b
    WORD $0x4e0203de // tbl    v30.16b, { v30.16b }, v2.16b
    WORD $0x4e201fff // and    v31.16b, v31.16b, v0.16b
    WORD $0x4e201d08 // and    v8.16b, v8.16b, v0.16b
    WORD $0x4e201f9c // and    v28.16b, v28.16b, v0.16b
    WORD $0x4e0203ff // tbl    v31.16b, { v31.16b }, v2.16b
    WORD $0x4e020129 // tbl    v9.16b, { v9.16b }, v2.16b
    WORD $0x4e71b94a // addv    h10, v10.8h
    WORD $0x4e71bbbd // addv    h29, v29.8h
    WORD $0x4e02039c // tbl    v28.16b, { v28.16b }, v2.16b
    WORD $0x4e020108 // tbl    v8.16b, { v8.16b }, v2.16b
    WORD $0x4e71b96b // addv    h11, v11.8h
    WORD $0x4e71bbde // addv    h30, v30.8h
    WORD $0x1e260156 // fmov    w22, s10
    WORD $0x1e2603b8 // fmov    w24, s29
    WORD $0x1e260177 // fmov    w23, s11
    WORD $0x4e71bbfd // addv    h29, v31.8h
    WORD $0x1e2603d9 // fmov    w25, s30
    WORD $0x4e71b929 // addv    h9, v9.8h
    WORD $0xd3607ed6 // lsl    x22, x22, #32
    WORD $0x4e71bb9c // addv    h28, v28.8h
    WORD $0xaa17c2d6 // orr    x22, x22, x23, lsl #48
    WORD $0x4e71b91e // addv    h30, v8.8h
    WORD $0xd3607f39 // lsl    x25, x25, #32
    WORD $0x1e2603ba // fmov    w26, s29
    WORD $0x53103f18 // lsl    w24, w24, #16
    WORD $0x1e260135 // fmov    w21, s9
    WORD $0x1e260397 // fmov    w23, s28
    WORD $0x1e2603db // fmov    w27, s30
    WORD $0xaa1ac339 // orr    x25, x25, x26, lsl #48
    WORD $0x53103eb5 // lsl    w21, w21, #16
    WORD $0xaa170337 // orr    x23, x25, x23
    WORD $0xaa1b02d9 // orr    x25, x22, x27
    WORD $0xaa1802f6 // orr    x22, x23, x24
    WORD $0xaa150335 // orr    x21, x25, x21
    CMP $0, R22
    BNE LBB0_61
    CMP $0, R19
    BNE LBB0_63
    CMP $0, R21
    BNE LBB0_64
LBB0_60:
    WORD $0xd10100e7 // sub    x7, x7, #64
    WORD $0x91010294 // add    x20, x20, #64
    WORD $0xf100fcff // cmp    x7, #63
    BHI LBB0_57
    B LBB0_206
LBB0_61:
    WORD $0xb10004df // cmn    x6, #1
    BNE LBB0_63
    WORD $0xdac002c6 // rbit    x6, x22
    WORD $0xdac010c6 // clz    x6, x6
    WORD $0x8b1400c6 // add    x6, x6, x20
LBB0_63:
    WORD $0x8a3302d7 // bic    x23, x22, x19
    WORD $0xaa170673 // orr    x19, x19, x23, lsl #1
    WORD $0x8a3302d6 // bic    x22, x22, x19
    WORD $0x9201f2d6 // and    x22, x22, #0xaaaaaaaaaaaaaaaa
    WORD $0xab1702d6 // adds    x22, x22, x23
    WORD $0xd37ffad6 // lsl    x22, x22, #1
    WORD $0xd200f2d6 // eor    x22, x22, #0x5555555555555555
    WORD $0x8a1302d6 // and    x22, x22, x19
    WORD $0x1a9f37f3 // cset    w19, hs
    WORD $0x8a3602b5 // bic    x21, x21, x22
    CMP $0, R21
    BEQ LBB0_60
LBB0_64:
    WORD $0xdac002a7 // rbit    x7, x21
    WORD $0xdac010e7 // clz    x7, x7
    WORD $0x8b1400e7 // add    x7, x7, x20
    WORD $0x910004e7 // add    x7, x7, #1
    TST $(1<<63), R7
    BNE LBB0_935
LBB0_65:
    WORD $0xb10004df // cmn    x6, #1
    WORD $0xf9000027 // str    x7, [x1]
    BEQ LBB0_67
    WORD $0xeb0700df // cmp    x6, x7
    BLE LBB0_261
LBB0_67:
    WORD $0xcb0200e5 // sub    x5, x7, x2
    WORD $0xd10008a5 // sub    x5, x5, #2
    WORD $0xaa0400a6 // orr    x6, x5, x4
    CMP $0, R6
    BEQ LBB0_77
    WORD $0xeb0400bf // cmp    x5, x4
    BNE LBB0_72
    WORD $0xaa1f03e6 // mov    x6, xzr
    WORD $0xaa0403e5 // mov    x5, x4
LBB0_70:
    WORD $0xf10040b3 // subs    x19, x5, #16
    BLO LBB0_73
    WORD $0x3ce66a3c // ldr    q28, [x17, x6]
    WORD $0x3ce66a5d // ldr    q29, [x18, x6]
    WORD $0x910040c6 // add    x6, x6, #16
    WORD $0x6e3c8fbc // cmeq    v28.16b, v29.16b, v28.16b
    WORD $0x4e201f9c // and    v28.16b, v28.16b, v0.16b
    WORD $0x4e02039c // tbl    v28.16b, { v28.16b }, v2.16b
    WORD $0x4e71bb9c // addv    h28, v28.8h
    WORD $0x1e260385 // fmov    w5, s28
    WORD $0x0a2501d4 // bic    w20, w14, w5
    WORD $0xaa1303e5 // mov    x5, x19
    CMP $0, R20
    BEQ LBB0_70
LBB0_72:
    WORD $0x2a1f03f1 // mov    w17, wzr
    B LBB0_78
LBB0_73:
    WORD $0x0b100042 // add    w2, w2, w16
    WORD $0x8b060252 // add    x18, x18, x6
    WORD $0x0b060042 // add    w2, w2, w6
    WORD $0x11000442 // add    w2, w2, #1
    WORD $0x92402c53 // and    x19, x2, #0xfff
    WORD $0x8b060222 // add    x2, x17, x6
    WORD $0xf13fc27f // cmp    x19, #4080
    BHI LBB0_76
    WORD $0x92402e51 // and    x17, x18, #0xfff
    WORD $0xf13fc63f // cmp    x17, #4081
    BHS LBB0_76
    WORD $0x3dc0005c // ldr    q28, [x2]
    WORD $0x3dc0025d // ldr    q29, [x18]
    WORD $0x6e3c8fbc // cmeq    v28.16b, v29.16b, v28.16b
    WORD $0x4e201f9c // and    v28.16b, v28.16b, v0.16b
    WORD $0x4e02039c // tbl    v28.16b, { v28.16b }, v2.16b
    WORD $0x4e71bb9c // addv    h28, v28.8h
    WORD $0x1e260391 // fmov    w17, s28
    WORD $0x6a3101d1 // bics    w17, w14, w17
    WORD $0xdac00231 // rbit    x17, x17
    WORD $0x1a9f17f2 // cset    w18, eq
    WORD $0xdac01231 // clz    x17, x17
    WORD $0xeb05023f // cmp    x17, x5
    WORD $0x1a9f3651 // csinc    w17, w18, wzr, lo
    B LBB0_78
LBB0_76:
    WORD $0xeb06009f // cmp    x4, x6
    BNE LBB0_121
LBB0_77:
    WORD $0x52800031 // mov    w17, #1
LBB0_78:
    WORD $0xf9400412 // ldr    x18, [x0, #8]
    WORD $0xeb1200ff // cmp    x7, x18
    BHS LBB0_83
    WORD $0x38676a02 // ldrb    w2, [x16, x7]
    WORD $0x7100345f // cmp    w2, #13
    BEQ LBB0_83
    WORD $0x7100805f // cmp    w2, #32
    BEQ LBB0_83
    WORD $0x51002c42 // sub    w2, w2, #11
    WORD $0x3100085f // cmn    w2, #2
    BHS LBB0_83
    WORD $0xaa0703e2 // mov    x2, x7
    B LBB0_99
LBB0_83:
    WORD $0x910004e2 // add    x2, x7, #1
    WORD $0xeb12005f // cmp    x2, x18
    BHS LBB0_87
    WORD $0x38626a04 // ldrb    w4, [x16, x2]
    WORD $0x7100349f // cmp    w4, #13
    BEQ LBB0_87
    WORD $0x7100809f // cmp    w4, #32
    BEQ LBB0_87
    WORD $0x51002c84 // sub    w4, w4, #11
    WORD $0x3100089f // cmn    w4, #2
    BLO LBB0_99
LBB0_87:
    WORD $0x910008e2 // add    x2, x7, #2
    WORD $0xeb12005f // cmp    x2, x18
    BHS LBB0_91
    WORD $0x38626a04 // ldrb    w4, [x16, x2]
    WORD $0x7100349f // cmp    w4, #13
    BEQ LBB0_91
    WORD $0x7100809f // cmp    w4, #32
    BEQ LBB0_91
    WORD $0x51002c84 // sub    w4, w4, #11
    WORD $0x3100089f // cmn    w4, #2
    BLO LBB0_99
LBB0_91:
    WORD $0x91000ce2 // add    x2, x7, #3
    WORD $0xeb12005f // cmp    x2, x18
    BHS LBB0_95
    WORD $0x38626a04 // ldrb    w4, [x16, x2]
    WORD $0x7100349f // cmp    w4, #13
    BEQ LBB0_95
    WORD $0x7100809f // cmp    w4, #32
    BEQ LBB0_95
    WORD $0x51002c84 // sub    w4, w4, #11
    WORD $0x3100089f // cmn    w4, #2
    BLO LBB0_99
LBB0_95:
    WORD $0x910010e2 // add    x2, x7, #4
    WORD $0xeb12005f // cmp    x2, x18
    BHS LBB0_809
LBB0_96:
    WORD $0x38626a04 // ldrb    w4, [x16, x2]
    WORD $0x9ac42165 // lsl    x5, x11, x4
    WORD $0x7100809f // cmp    w4, #32
    WORD $0x8a0c00a4 // and    x4, x5, x12
    WORD $0xfa409884 // ccmp    x4, #0, #4, ls
    BEQ LBB0_98
    WORD $0x91000442 // add    x2, x2, #1
    WORD $0xeb02025f // cmp    x18, x2
    BNE LBB0_96
    B LBB0_865
LBB0_98:
    WORD $0xeb12005f // cmp    x2, x18
    BHS LBB0_865
LBB0_99:
    WORD $0x91000452 // add    x18, x2, #1
    WORD $0xf9000032 // str    x18, [x1]
    WORD $0x38626a04 // ldrb    w4, [x16, x2]
    WORD $0x7100e89f // cmp    w4, #58
    BNE LBB0_865
    CMP $0, R17
    BNE LBB0_481
    WORD $0xf9400404 // ldr    x4, [x0, #8]
    WORD $0xeb04025f // cmp    x18, x4
    BHS LBB0_106
    WORD $0x38726a11 // ldrb    w17, [x16, x18]
    WORD $0x7100363f // cmp    w17, #13
    BEQ LBB0_106
    WORD $0x7100823f // cmp    w17, #32
    BEQ LBB0_106
    WORD $0x51002e31 // sub    w17, w17, #11
    WORD $0x31000a3f // cmn    w17, #2
    BHS LBB0_106
    WORD $0xaa1203f1 // mov    x17, x18
    B LBB0_125
LBB0_106:
    WORD $0x91000851 // add    x17, x2, #2
    WORD $0xeb04023f // cmp    x17, x4
    BHS LBB0_110
    WORD $0x38716a05 // ldrb    w5, [x16, x17]
    WORD $0x710034bf // cmp    w5, #13
    BEQ LBB0_110
    WORD $0x710080bf // cmp    w5, #32
    BEQ LBB0_110
    WORD $0x51002ca5 // sub    w5, w5, #11
    WORD $0x310008bf // cmn    w5, #2
    BLO LBB0_125
LBB0_110:
    WORD $0x91000c51 // add    x17, x2, #3
    WORD $0xeb04023f // cmp    x17, x4
    BHS LBB0_114
    WORD $0x38716a05 // ldrb    w5, [x16, x17]
    WORD $0x710034bf // cmp    w5, #13
    BEQ LBB0_114
    WORD $0x710080bf // cmp    w5, #32
    BEQ LBB0_114
    WORD $0x51002ca5 // sub    w5, w5, #11
    WORD $0x310008bf // cmn    w5, #2
    BLO LBB0_125
LBB0_114:
    WORD $0x91001051 // add    x17, x2, #4
    WORD $0xeb04023f // cmp    x17, x4
    BHS LBB0_118
    WORD $0x38716a05 // ldrb    w5, [x16, x17]
    WORD $0x710034bf // cmp    w5, #13
    BEQ LBB0_118
    WORD $0x710080bf // cmp    w5, #32
    BEQ LBB0_118
    WORD $0x51002ca5 // sub    w5, w5, #11
    WORD $0x310008bf // cmn    w5, #2
    BLO LBB0_125
LBB0_118:
    WORD $0x91001451 // add    x17, x2, #5
    WORD $0xeb04023f // cmp    x17, x4
    BHS LBB0_183
LBB0_119:
    WORD $0x38716a02 // ldrb    w2, [x16, x17]
    WORD $0x9ac22165 // lsl    x5, x11, x2
    WORD $0x7100805f // cmp    w2, #32
    WORD $0x8a0c00a2 // and    x2, x5, x12
    WORD $0xfa409844 // ccmp    x2, #0, #4, ls
    BEQ LBB0_124
    WORD $0x91000631 // add    x17, x17, #1
    WORD $0xeb11009f // cmp    x4, x17
    BNE LBB0_119
    B LBB0_184
LBB0_121:
    WORD $0x52800024 // mov    w4, #1
LBB0_122:
    WORD $0x38401451 // ldrb    w17, [x2], #1
    WORD $0x38401646 // ldrb    w6, [x18], #1
    WORD $0x6b06023f // cmp    w17, w6
    WORD $0x1a9f17f1 // cset    w17, eq
    BNE LBB0_78
    WORD $0x91000486 // add    x6, x4, #1
    WORD $0xeb0400bf // cmp    x5, x4
    WORD $0xaa0603e4 // mov    x4, x6
    BNE LBB0_122
    B LBB0_78
LBB0_124:
    WORD $0xeb04023f // cmp    x17, x4
    BHS LBB0_184
LBB0_125:
    WORD $0x91000632 // add    x18, x17, #1
    WORD $0xf9000032 // str    x18, [x1]
    WORD $0x38716a02 // ldrb    w2, [x16, x17]
    WORD $0x7101685f // cmp    w2, #90
    BGT LBB0_146
    WORD $0x7100bc5f // cmp    w2, #47
    BLE LBB0_177
    WORD $0x5100c042 // sub    w2, w2, #48
    WORD $0x7100285f // cmp    w2, #10
    BHS LBB0_183
LBB0_128:
    WORD $0xf9400402 // ldr    x2, [x0, #8]
    WORD $0xcb120042 // sub    x2, x2, x18
    WORD $0xf100405f // cmp    x2, #16
    BLO LBB0_132
    WORD $0xaa1f03e4 // mov    x4, xzr
LBB0_130:
    WORD $0x3cf26a1c // ldr    q28, [x16, x18]
    WORD $0x6e248f9d // cmeq    v29.16b, v28.16b, v4.16b
    WORD $0x4e251f9c // and    v28.16b, v28.16b, v5.16b
    WORD $0x6e268f9c // cmeq    v28.16b, v28.16b, v6.16b
    WORD $0x4ebd1f9c // orr    v28.16b, v28.16b, v29.16b
    WORD $0x4e201f9c // and    v28.16b, v28.16b, v0.16b
    WORD $0x4e02039c // tbl    v28.16b, { v28.16b }, v2.16b
    WORD $0x4e71bb9c // addv    h28, v28.8h
    WORD $0x1e260385 // fmov    w5, s28
    CMP $0, R5
    BNE LBB0_141
    WORD $0xd1004042 // sub    x2, x2, #16
    WORD $0x91004252 // add    x18, x18, #16
    WORD $0x91004084 // add    x4, x4, #16
    WORD $0xf1003c5f // cmp    x2, #15
    BHI LBB0_130
LBB0_132:
    WORD $0x8b120211 // add    x17, x16, x18
    CMP $0, R2
    BEQ LBB0_140
    WORD $0x8b020232 // add    x18, x17, x2
LBB0_134:
    WORD $0x39400224 // ldrb    w4, [x17]
    WORD $0x7100b09f // cmp    w4, #44
    BHI LBB0_136
    WORD $0x9ac42165 // lsl    x5, x11, x4
    WORD $0xea0d00bf // tst    x5, x13
    BNE LBB0_140
LBB0_136:
    WORD $0x7101749f // cmp    w4, #93
    BEQ LBB0_140
    WORD $0x7101f49f // cmp    w4, #125
    BEQ LBB0_140
    WORD $0x91000631 // add    x17, x17, #1
    WORD $0xf1000442 // subs    x2, x2, #1
    BNE LBB0_134
    WORD $0xaa1203f1 // mov    x17, x18
LBB0_140:
    WORD $0xcb100232 // sub    x18, x17, x16
    WORD $0xf9000032 // str    x18, [x1]
    B LBB0_184
LBB0_141:
    WORD $0x5ac000a2 // rbit    w2, w5
    WORD $0x5ac01042 // clz    w2, w2
    WORD $0x8b120052 // add    x18, x2, x18
    WORD $0xf100065f // cmp    x18, #1
    WORD $0xf9000032 // str    x18, [x1]
    BLT LBB0_184
    WORD $0x8b040052 // add    x18, x2, x4
    WORD $0x8b110210 // add    x16, x16, x17
LBB0_143:
    WORD $0x38726a02 // ldrb    w2, [x16, x18]
    WORD $0x9ac22164 // lsl    x4, x11, x2
    WORD $0x7100805f // cmp    w2, #32
    WORD $0x8a0c0082 // and    x2, x4, x12
    WORD $0xfa409844 // ccmp    x2, #0, #4, ls
    WORD $0x8b120222 // add    x2, x17, x18
    BEQ LBB0_214
    WORD $0xd1000652 // sub    x18, x18, #1
    WORD $0xf9000022 // str    x2, [x1]
    WORD $0x8b120224 // add    x4, x17, x18
    WORD $0x91000885 // add    x5, x4, #2
    WORD $0xf10004bf // cmp    x5, #1
    BHI LBB0_143
    WORD $0x91000492 // add    x18, x4, #1
    B LBB0_184
LBB0_146:
    WORD $0x7101b45f // cmp    w2, #109
    BLE LBB0_180
    WORD $0x7101b85f // cmp    w2, #110
    BEQ LBB0_211
    WORD $0x7101d05f // cmp    w2, #116
    BEQ LBB0_211
    WORD $0x7101ec5f // cmp    w2, #123
    BNE LBB0_183
    WORD $0xf9400404 // ldr    x4, [x0, #8]
    WORD $0xaa1f03e6 // mov    x6, xzr
    WORD $0xaa1f03e2 // mov    x2, xzr
    WORD $0xaa1f03e5 // mov    x5, xzr
    WORD $0xaa1f03f1 // mov    x17, xzr
    WORD $0x8b120210 // add    x16, x16, x18
    WORD $0xcb120084 // sub    x4, x4, x18
    WORD $0xf1010092 // subs    x18, x4, #64
    BGE LBB0_167
LBB0_151:
    WORD $0xf100009f // cmp    x4, #0
    BLE LBB0_295
    WORD $0x92402e07 // and    x7, x16, #0xfff
    WORD $0xad0063f8 // stp    q24, q24, [sp]
    WORD $0xf13f04ff // cmp    x7, #4033
    WORD $0xad0163f8 // stp    q24, q24, [sp, #32]
    BLO LBB0_167
    WORD $0xf1008093 // subs    x19, x4, #32
    BLO LBB0_155
    WORD $0xa9415215 // ldp    x21, x20, [x16, #16]
    WORD $0xaa0903e7 // mov    x7, x9
    WORD $0x3cc2061c // ldr    q28, [x16], #32
    WORD $0x3d8003fc // str    q28, [sp]
    WORD $0xa90153f5 // stp    x21, x20, [sp, #16]
    B LBB0_156
LBB0_155:
    WORD $0x910003e7 // mov    x7, sp
    WORD $0xaa0403f3 // mov    x19, x4
LBB0_156:
    WORD $0xf1004274 // subs    x20, x19, #16
    BLO LBB0_162
    WORD $0xa8c14e15 // ldp    x21, x19, [x16], #16
    WORD $0xa8814cf5 // stp    x21, x19, [x7], #16
    WORD $0xaa1403f3 // mov    x19, x20
    WORD $0xf1002294 // subs    x20, x20, #8
    BHS LBB0_163
LBB0_158:
    WORD $0xf1001274 // subs    x20, x19, #4
    BLO LBB0_164
LBB0_159:
    WORD $0xb8404615 // ldr    w21, [x16], #4
    WORD $0xaa1403f3 // mov    x19, x20
    WORD $0xb80044f5 // str    w21, [x7], #4
    WORD $0xf1000a94 // subs    x20, x20, #2
    BHS LBB0_165
LBB0_160:
    CMP $0, R19
    BEQ LBB0_166
LBB0_161:
    WORD $0x39400213 // ldrb    w19, [x16]
    WORD $0x910003f0 // mov    x16, sp
    WORD $0x390000f3 // strb    w19, [x7]
    B LBB0_167
LBB0_162:
    WORD $0xf1002274 // subs    x20, x19, #8
    BLO LBB0_158
LBB0_163:
    WORD $0xf8408615 // ldr    x21, [x16], #8
    WORD $0xaa1403f3 // mov    x19, x20
    WORD $0xf80084f5 // str    x21, [x7], #8
    WORD $0xf1001294 // subs    x20, x20, #4
    BHS LBB0_159
LBB0_164:
    WORD $0xf1000a74 // subs    x20, x19, #2
    BLO LBB0_160
LBB0_165:
    WORD $0x78402615 // ldrh    w21, [x16], #2
    WORD $0xaa1403f3 // mov    x19, x20
    WORD $0x780024f5 // strh    w21, [x7], #2
    CMP $0, R20
    BNE LBB0_161
LBB0_166:
    WORD $0x910003f0 // mov    x16, sp
LBB0_167:
    WORD $0xad417e1e // ldp    q30, q31, [x16, #32]
    WORD $0x6e238fca // cmeq    v10.16b, v30.16b, v3.16b
    WORD $0xad40761c // ldp    q28, q29, [x16]
    WORD $0x6e238feb // cmeq    v11.16b, v31.16b, v3.16b
    WORD $0x4e201d4a // and    v10.16b, v10.16b, v0.16b
    WORD $0x4e02014a // tbl    v10.16b, { v10.16b }, v2.16b
    WORD $0x6e238f88 // cmeq    v8.16b, v28.16b, v3.16b
    WORD $0x4e201d6b // and    v11.16b, v11.16b, v0.16b
    WORD $0x6e238fa9 // cmeq    v9.16b, v29.16b, v3.16b
    WORD $0x4e201d08 // and    v8.16b, v8.16b, v0.16b
    WORD $0x4e201d29 // and    v9.16b, v9.16b, v0.16b
    WORD $0x4e02016b // tbl    v11.16b, { v11.16b }, v2.16b
    WORD $0x4e020108 // tbl    v8.16b, { v8.16b }, v2.16b
    WORD $0x4e020129 // tbl    v9.16b, { v9.16b }, v2.16b
    WORD $0x4e71b94a // addv    h10, v10.8h
    WORD $0x4e71b96b // addv    h11, v11.8h
    WORD $0x4e71b908 // addv    h8, v8.8h
    WORD $0x4e71b929 // addv    h9, v9.8h
    WORD $0x1e260147 // fmov    w7, s10
    WORD $0x1e260173 // fmov    w19, s11
    WORD $0x1e260114 // fmov    w20, s8
    WORD $0x1e260135 // fmov    w21, s9
    WORD $0xd3607ce7 // lsl    x7, x7, #32
    WORD $0xaa13c0e7 // orr    x7, x7, x19, lsl #48
    WORD $0x53103eb3 // lsl    w19, w21, #16
    WORD $0xaa1400e7 // orr    x7, x7, x20
    WORD $0xaa1300e7 // orr    x7, x7, x19
    WORD $0xaa0200f3 // orr    x19, x7, x2
    CMP $0, R19
    BNE LBB0_169
    WORD $0xaa1f03e2 // mov    x2, xzr
    WORD $0x92800007 // mov    x7, #-1
    B LBB0_170
LBB0_169:
    WORD $0x8a2200f3 // bic    x19, x7, x2
    WORD $0xaa130442 // orr    x2, x2, x19, lsl #1
    WORD $0x8a2200e7 // bic    x7, x7, x2
    WORD $0x9201f0e7 // and    x7, x7, #0xaaaaaaaaaaaaaaaa
    WORD $0xab1300e7 // adds    x7, x7, x19
    WORD $0xd37ff8e7 // lsl    x7, x7, #1
    WORD $0xd200f0e7 // eor    x7, x7, #0x5555555555555555
    WORD $0x8a0200e7 // and    x7, x7, x2
    WORD $0x1a9f37e2 // cset    w2, hs
    WORD $0xaa2703e7 // mvn    x7, x7
LBB0_170:
    WORD $0x6e218fff // cmeq    v31.16b, v31.16b, v1.16b
    WORD $0x6e218fde // cmeq    v30.16b, v30.16b, v1.16b
    WORD $0x4e201fff // and    v31.16b, v31.16b, v0.16b
    WORD $0x4e0203ff // tbl    v31.16b, { v31.16b }, v2.16b
    WORD $0x4e201fde // and    v30.16b, v30.16b, v0.16b
    WORD $0x6e218f88 // cmeq    v8.16b, v28.16b, v1.16b
    WORD $0x4e0203de // tbl    v30.16b, { v30.16b }, v2.16b
    WORD $0x6e218fa9 // cmeq    v9.16b, v29.16b, v1.16b
    WORD $0x4e201d08 // and    v8.16b, v8.16b, v0.16b
    WORD $0x4e201d29 // and    v9.16b, v9.16b, v0.16b
    WORD $0x4e71bbff // addv    h31, v31.8h
    WORD $0x4e020108 // tbl    v8.16b, { v8.16b }, v2.16b
    WORD $0x4e020129 // tbl    v9.16b, { v9.16b }, v2.16b
    WORD $0x4e71bbde // addv    h30, v30.8h
    WORD $0x1e2603f3 // fmov    w19, s31
    WORD $0x4e71b908 // addv    h8, v8.8h
    WORD $0x4e71b93f // addv    h31, v9.8h
    WORD $0x1e2603d4 // fmov    w20, s30
    WORD $0xd3503e73 // lsl    x19, x19, #48
    WORD $0x1e260115 // fmov    w21, s8
    WORD $0xaa148273 // orr    x19, x19, x20, lsl #32
    WORD $0x1e2603f4 // fmov    w20, s31
    WORD $0xaa150273 // orr    x19, x19, x21
    WORD $0x53103e94 // lsl    w20, w20, #16
    WORD $0xaa140273 // orr    x19, x19, x20
    WORD $0x8a070267 // and    x7, x19, x7
    WORD $0x9202e0f3 // and    x19, x7, #0x4444444444444444
    WORD $0x4e080cfe // dup    v30.2d, x7
    WORD $0x9201e0e7 // and    x7, x7, #0x8888888888888888
    WORD $0x4e080e7f // dup    v31.2d, x19
    WORD $0x0420bfe9 // movprfx    z9, z31
    WORD $0x04d000e9 // mul    z9.d, p0/m, z9.d, z7.d
    WORD $0x4e271fde // and    v30.16b, v30.16b, v7.16b
    WORD $0x0420bfc8 // movprfx    z8, z30
    WORD $0x04d00288 // mul    z8.d, p0/m, z8.d, z20.d
    WORD $0x6e291d08 // eor    v8.16b, v8.16b, v9.16b
    WORD $0x04d0027f // mul    z31.d, p0/m, z31.d, z19.d
    WORD $0x4e080ce9 // dup    v9.2d, x7
    WORD $0x0420bd2c // movprfx    z12, z9
    WORD $0x04d002cc // mul    z12.d, p0/m, z12.d, z22.d
    WORD $0x4e0807ca // dup    v10.2d, v30.d[0]
    WORD $0x6e1e43cb // ext    v11.16b, v30.16b, v30.16b, #8
    WORD $0x4e1807de // dup    v30.2d, v30.d[1]
    WORD $0x04d002a9 // mul    z9.d, p0/m, z9.d, z21.d
    WORD $0x04d0022a // mul    z10.d, p0/m, z10.d, z17.d
    WORD $0x04d0025e // mul    z30.d, p0/m, z30.d, z18.d
    WORD $0x6e2c1fff // eor    v31.16b, v31.16b, v12.16b
    WORD $0x6e291d08 // eor    v8.16b, v8.16b, v9.16b
    WORD $0x0420bd69 // movprfx    z9, z11
    WORD $0x04d00209 // mul    z9.d, p0/m, z9.d, z16.d
    WORD $0x6e3e1d5e // eor    v30.16b, v10.16b, v30.16b
    WORD $0x6e3f1fde // eor    v30.16b, v30.16b, v31.16b
    WORD $0x6e281d3f // eor    v31.16b, v9.16b, v8.16b
    WORD $0x4e3b1fff // and    v31.16b, v31.16b, v27.16b
    WORD $0x4e311fde // and    v30.16b, v30.16b, v17.16b
    WORD $0x4ebf1fde // orr    v30.16b, v30.16b, v31.16b
    WORD $0x6e1e43df // ext    v31.16b, v30.16b, v30.16b, #8
    WORD $0x6e398f88 // cmeq    v8.16b, v28.16b, v25.16b
    WORD $0x6e3a8f9c // cmeq    v28.16b, v28.16b, v26.16b
    WORD $0x4e201d08 // and    v8.16b, v8.16b, v0.16b
    WORD $0x0ebf1fde // orr    v30.8b, v30.8b, v31.8b
    WORD $0x6e398fbf // cmeq    v31.16b, v29.16b, v25.16b
    WORD $0x9e6603c7 // fmov    x7, d30
    WORD $0x6e3a8fbd // cmeq    v29.16b, v29.16b, v26.16b
    WORD $0x4e201ffe // and    v30.16b, v31.16b, v0.16b
    WORD $0x4e201fbd // and    v29.16b, v29.16b, v0.16b
    WORD $0xca0600e6 // eor    x6, x7, x6
    WORD $0x4e201f9c // and    v28.16b, v28.16b, v0.16b
    WORD $0xf10080df // cmp    x6, #32
    WORD $0x4e02011f // tbl    v31.16b, { v8.16b }, v2.16b
    WORD $0x2a2603f7 // mvn    w23, w6
    WORD $0x4e0203de // tbl    v30.16b, { v30.16b }, v2.16b
    WORD $0x1a9f97f4 // cset    w20, hi
    WORD $0x4e0203bd // tbl    v29.16b, { v29.16b }, v2.16b
    WORD $0x4e02039c // tbl    v28.16b, { v28.16b }, v2.16b
    WORD $0x4e71bbff // addv    h31, v31.8h
    WORD $0x4e71bbde // addv    h30, v30.8h
    WORD $0x4e71bbbd // addv    h29, v29.8h
    WORD $0x4e71bb9c // addv    h28, v28.8h
    WORD $0x1e2603d5 // fmov    w21, s30
    WORD $0x1e2603b6 // fmov    w22, s29
    WORD $0x1e2603f3 // fmov    w19, s31
    WORD $0x1e260387 // fmov    w7, s28
    WORD $0x33103eb3 // bfi    w19, w21, #16, #16
    WORD $0x33103ec7 // bfi    w7, w22, #16, #16
    WORD $0x8a1302f5 // and    x21, x23, x19
    WORD $0xea0702f6 // ands    x22, x23, x7
    BEQ LBB0_173
LBB0_171:
    WORD $0xd10006d7 // sub    x23, x22, #1
    WORD $0x8a1502f8 // and    x24, x23, x21
    WORD $0x9e67031c // fmov    d28, x24
    WORD $0x0e205b9c // cnt    v28.8b, v28.8b
    WORD $0x2e303b9c // uaddlv    h28, v28.8b
    WORD $0x1e260398 // fmov    w24, s28
    WORD $0x8b050318 // add    x24, x24, x5
    WORD $0xeb11031f // cmp    x24, x17
    BLS LBB0_252
    WORD $0xea1602f6 // ands    x22, x23, x22
    WORD $0x91000631 // add    x17, x17, #1
    BNE LBB0_171
LBB0_173:
    WORD $0x9e6702bc // fmov    d28, x21
    WORD $0xd2407e94 // eor    x20, x20, #0xffffffff
    WORD $0x8a130293 // and    x19, x20, x19
    WORD $0xea070287 // ands    x7, x20, x7
    WORD $0x0e205b9c // cnt    v28.8b, v28.8b
    WORD $0x2e303b9c // uaddlv    h28, v28.8b
    WORD $0x1e260395 // fmov    w21, s28
    WORD $0x8b0502a5 // add    x5, x21, x5
    BEQ LBB0_176
LBB0_174:
    WORD $0xd10004f4 // sub    x20, x7, #1
    WORD $0x8a130295 // and    x21, x20, x19
    WORD $0x9e6702bc // fmov    d28, x21
    WORD $0x0e205b9c // cnt    v28.8b, v28.8b
    WORD $0x2e303b9c // uaddlv    h28, v28.8b
    WORD $0x1e260395 // fmov    w21, s28
    WORD $0x8b0502b5 // add    x21, x21, x5
    WORD $0xeb1102bf // cmp    x21, x17
    BLS LBB0_254
    WORD $0xea070287 // ands    x7, x20, x7
    WORD $0x91000631 // add    x17, x17, #1
    BNE LBB0_174
LBB0_176:
    WORD $0x9e67027c // fmov    d28, x19
    WORD $0x937ffcc6 // asr    x6, x6, #63
    WORD $0x91010210 // add    x16, x16, #64
    WORD $0x0e205b9c // cnt    v28.8b, v28.8b
    WORD $0x2e303b9c // uaddlv    h28, v28.8b
    WORD $0x1e260384 // fmov    w4, s28
    WORD $0x8b050085 // add    x5, x4, x5
    WORD $0xaa1203e4 // mov    x4, x18
    WORD $0xf1010252 // subs    x18, x18, #64
    BGE LBB0_167
    B LBB0_151
LBB0_177:
    CMP $0, R2
    BEQ LBB0_184
    WORD $0x7100885f // cmp    w2, #34
    BEQ LBB0_215
    WORD $0x7100b45f // cmp    w2, #45
    BEQ LBB0_128
    B LBB0_183
LBB0_180:
    WORD $0x71016c5f // cmp    w2, #91
    BEQ LBB0_225
    WORD $0x7101985f // cmp    w2, #102
    BNE LBB0_183
    WORD $0xf9400402 // ldr    x2, [x0, #8]
    WORD $0x91001630 // add    x16, x17, #5
    B LBB0_212
LBB0_183:
    WORD $0xaa1103f2 // mov    x18, x17
    WORD $0xf9000031 // str    x17, [x1]
LBB0_184:
    WORD $0xa9404410 // ldp    x16, x17, [x0]
    WORD $0xeb11025f // cmp    x18, x17
    BHS LBB0_189
    WORD $0x38726a02 // ldrb    w2, [x16, x18]
    WORD $0x7100345f // cmp    w2, #13
    BEQ LBB0_189
    WORD $0x7100805f // cmp    w2, #32
    BEQ LBB0_189
    WORD $0x51002c42 // sub    w2, w2, #11
    WORD $0x3100085f // cmn    w2, #2
    BHS LBB0_189
    WORD $0xaa1203e2 // mov    x2, x18
    B LBB0_205
LBB0_189:
    WORD $0x91000642 // add    x2, x18, #1
    WORD $0xeb11005f // cmp    x2, x17
    BHS LBB0_193
    WORD $0x38626a04 // ldrb    w4, [x16, x2]
    WORD $0x7100349f // cmp    w4, #13
    BEQ LBB0_193
    WORD $0x7100809f // cmp    w4, #32
    BEQ LBB0_193
    WORD $0x51002c84 // sub    w4, w4, #11
    WORD $0x3100089f // cmn    w4, #2
    BLO LBB0_205
LBB0_193:
    WORD $0x91000a42 // add    x2, x18, #2
    WORD $0xeb11005f // cmp    x2, x17
    BHS LBB0_197
    WORD $0x38626a04 // ldrb    w4, [x16, x2]
    WORD $0x7100349f // cmp    w4, #13
    BEQ LBB0_197
    WORD $0x7100809f // cmp    w4, #32
    BEQ LBB0_197
    WORD $0x51002c84 // sub    w4, w4, #11
    WORD $0x3100089f // cmn    w4, #2
    BLO LBB0_205
LBB0_197:
    WORD $0x91000e42 // add    x2, x18, #3
    WORD $0xeb11005f // cmp    x2, x17
    BHS LBB0_201
    WORD $0x38626a04 // ldrb    w4, [x16, x2]
    WORD $0x7100349f // cmp    w4, #13
    BEQ LBB0_201
    WORD $0x7100809f // cmp    w4, #32
    BEQ LBB0_201
    WORD $0x51002c84 // sub    w4, w4, #11
    WORD $0x3100089f // cmn    w4, #2
    BLO LBB0_205
LBB0_201:
    WORD $0x91001242 // add    x2, x18, #4
    WORD $0xeb11005f // cmp    x2, x17
    BHS LBB0_809
LBB0_202:
    WORD $0x38626a12 // ldrb    w18, [x16, x2]
    WORD $0x9ad22164 // lsl    x4, x11, x18
    WORD $0x7100825f // cmp    w18, #32
    WORD $0x8a0c0092 // and    x18, x4, x12
    WORD $0xfa409a44 // ccmp    x18, #0, #4, ls
    BEQ LBB0_204
    WORD $0x91000442 // add    x2, x2, #1
    WORD $0xeb02023f // cmp    x17, x2
    BNE LBB0_202
    B LBB0_865
LBB0_204:
    WORD $0xeb11005f // cmp    x2, x17
    BHS LBB0_865
LBB0_205:
    WORD $0x91000444 // add    x4, x2, #1
    WORD $0xf9000024 // str    x4, [x1]
    WORD $0x38626a11 // ldrb    w17, [x16, x2]
    WORD $0x7100b23f // cmp    w17, #44
    BEQ LBB0_32
    B LBB0_864
LBB0_206:
    WORD $0x8b140214 // add    x20, x16, x20
    WORD $0xf10080f5 // subs    x21, x7, #32
    BLO LBB0_279
LBB0_207:
    WORD $0xad40769c // ldp    q28, q29, [x20]
    WORD $0x6e218f9e // cmeq    v30.16b, v28.16b, v1.16b
    WORD $0x6e238f9c // cmeq    v28.16b, v28.16b, v3.16b
    WORD $0x6e218fbf // cmeq    v31.16b, v29.16b, v1.16b
    WORD $0x6e238fbd // cmeq    v29.16b, v29.16b, v3.16b
    WORD $0x4e201fde // and    v30.16b, v30.16b, v0.16b
    WORD $0x4e201fbd // and    v29.16b, v29.16b, v0.16b
    WORD $0x4e0203bd // tbl    v29.16b, { v29.16b }, v2.16b
    WORD $0x4e201fff // and    v31.16b, v31.16b, v0.16b
    WORD $0x4e201f9c // and    v28.16b, v28.16b, v0.16b
    WORD $0x4e0203ff // tbl    v31.16b, { v31.16b }, v2.16b
    WORD $0x4e02039c // tbl    v28.16b, { v28.16b }, v2.16b
    WORD $0x4e0203de // tbl    v30.16b, { v30.16b }, v2.16b
    WORD $0x4e71bbbd // addv    h29, v29.8h
    WORD $0x4e71bbff // addv    h31, v31.8h
    WORD $0x4e71bb9c // addv    h28, v28.8h
    WORD $0x1e2603b7 // fmov    w23, s29
    WORD $0x4e71bbdd // addv    h29, v30.8h
    WORD $0x1e2603f8 // fmov    w24, s31
    WORD $0x1e260396 // fmov    w22, s28
    WORD $0x1e2603a7 // fmov    w7, s29
    WORD $0x33103ef6 // bfi    w22, w23, #16, #16
    WORD $0x33103f07 // bfi    w7, w24, #16, #16
    CMP $0, R22
    BNE LBB0_275
    CMP $0, R19
    BNE LBB0_277
    CMP $0, R7
    BEQ LBB0_278
LBB0_210:
    WORD $0xdac000e7 // rbit    x7, x7
    WORD $0xcb100293 // sub    x19, x20, x16
    WORD $0xdac010e7 // clz    x7, x7
    WORD $0x8b070267 // add    x7, x19, x7
    WORD $0x910004e7 // add    x7, x7, #1
    TST $(1<<63), R7
    BEQ LBB0_65
    B LBB0_935
LBB0_211:
    WORD $0xf9400402 // ldr    x2, [x0, #8]
    WORD $0x91001230 // add    x16, x17, #4
LBB0_212:
    WORD $0xeb02021f // cmp    x16, x2
    BHI LBB0_184
    WORD $0xaa1003f2 // mov    x18, x16
    WORD $0xf9000030 // str    x16, [x1]
    B LBB0_184
LBB0_214:
    WORD $0x91000452 // add    x18, x2, #1
    B LBB0_184
LBB0_215:
    WORD $0xf9400404 // ldr    x4, [x0, #8]
    WORD $0xcb120082 // sub    x2, x4, x18
    WORD $0xf100805f // cmp    x2, #32
    BLT LBB0_292
    WORD $0xaa1f03e2 // mov    x2, xzr
    WORD $0xaa1f03e7 // mov    x7, xzr
    WORD $0x8b110205 // add    x5, x16, x17
    WORD $0xcb110084 // sub    x4, x4, x17
    WORD $0x528003e6 // mov    w6, #31
LBB0_217:
    WORD $0x8b0200b3 // add    x19, x5, x2
    WORD $0x3cc1127c // ldur    q28, [x19, #17]
    WORD $0x3cc0127e // ldur    q30, [x19, #1]
    WORD $0x6e238f9d // cmeq    v29.16b, v28.16b, v3.16b
    WORD $0x6e218f9c // cmeq    v28.16b, v28.16b, v1.16b
    WORD $0x4e201fbd // and    v29.16b, v29.16b, v0.16b
    WORD $0x4e0203bd // tbl    v29.16b, { v29.16b }, v2.16b
    WORD $0x4e201f9c // and    v28.16b, v28.16b, v0.16b
    WORD $0x4e02039c // tbl    v28.16b, { v28.16b }, v2.16b
    WORD $0x4e71bbbd // addv    h29, v29.8h
    WORD $0x4e71bb9c // addv    h28, v28.8h
    WORD $0x1e2603b3 // fmov    w19, s29
    WORD $0x6e218fdd // cmeq    v29.16b, v30.16b, v1.16b
    WORD $0x6e238fde // cmeq    v30.16b, v30.16b, v3.16b
    WORD $0x4e201fbd // and    v29.16b, v29.16b, v0.16b
    WORD $0x4e201fde // and    v30.16b, v30.16b, v0.16b
    WORD $0x4e0203de // tbl    v30.16b, { v30.16b }, v2.16b
    WORD $0x4e0203bd // tbl    v29.16b, { v29.16b }, v2.16b
    WORD $0x1e260395 // fmov    w21, s28
    WORD $0x4e71bbde // addv    h30, v30.8h
    WORD $0x4e71bbbd // addv    h29, v29.8h
    WORD $0x1e2603d4 // fmov    w20, s30
    WORD $0x33103e74 // bfi    w20, w19, #16, #16
    WORD $0x1e2603b3 // fmov    w19, s29
    WORD $0x7100029f // cmp    w20, #0
    WORD $0xfa4008e0 // ccmp    x7, #0, #0, eq
    WORD $0x33103eb3 // bfi    w19, w21, #16, #16
    BEQ LBB0_219
    WORD $0x0a270295 // bic    w21, w20, w7
    WORD $0x2a1504e7 // orr    w7, w7, w21, lsl #1
    WORD $0x0a270294 // bic    w20, w20, w7
    WORD $0x1201f294 // and    w20, w20, #0xaaaaaaaa
    WORD $0x2b150294 // adds    w20, w20, w21
    WORD $0x531f7a94 // lsl    w20, w20, #1
    WORD $0x5200f294 // eor    w20, w20, #0x55555555
    WORD $0x0a070287 // and    w7, w20, w7
    WORD $0x2a2703f4 // mvn    w20, w7
    WORD $0x1a9f37e7 // cset    w7, hs
    WORD $0x8a130293 // and    x19, x20, x19
    B LBB0_220
LBB0_219:
    WORD $0xaa1f03e7 // mov    x7, xzr
LBB0_220:
    CMP $0, R19
    BNE LBB0_253
    WORD $0xd10080c6 // sub    x6, x6, #32
    WORD $0x91008042 // add    x2, x2, #32
    WORD $0x8b060093 // add    x19, x4, x6
    WORD $0xf100fe7f // cmp    x19, #63
    BGT LBB0_217
    CMP $0, R7
    BNE LBB0_296
    WORD $0x8b110211 // add    x17, x16, x17
    WORD $0x8b020231 // add    x17, x17, x2
    WORD $0xaa2203e2 // mvn    x2, x2
    WORD $0x91000631 // add    x17, x17, #1
    WORD $0x8b040042 // add    x2, x2, x4
LBB0_224:
    WORD $0xf100045f // cmp    x2, #1
    BGE LBB0_257
    B LBB0_184
LBB0_225:
    WORD $0xf9400404 // ldr    x4, [x0, #8]
    WORD $0xaa1f03e6 // mov    x6, xzr
    WORD $0xaa1f03e2 // mov    x2, xzr
    WORD $0xaa1f03e5 // mov    x5, xzr
    WORD $0xaa1f03f1 // mov    x17, xzr
    WORD $0x8b120210 // add    x16, x16, x18
    WORD $0xcb120084 // sub    x4, x4, x18
    WORD $0xf1010092 // subs    x18, x4, #64
    BGE LBB0_242
LBB0_226:
    WORD $0xf100009f // cmp    x4, #0
    BLE LBB0_295
    WORD $0x92402e07 // and    x7, x16, #0xfff
    WORD $0xad0063f8 // stp    q24, q24, [sp]
    WORD $0xf13f04ff // cmp    x7, #4033
    WORD $0xad0163f8 // stp    q24, q24, [sp, #32]
    BLO LBB0_242
    WORD $0xf1008093 // subs    x19, x4, #32
    BLO LBB0_230
    WORD $0xa9415215 // ldp    x21, x20, [x16, #16]
    WORD $0xaa0903e7 // mov    x7, x9
    WORD $0x3cc2061c // ldr    q28, [x16], #32
    WORD $0x3d8003fc // str    q28, [sp]
    WORD $0xa90153f5 // stp    x21, x20, [sp, #16]
    B LBB0_231
LBB0_230:
    WORD $0x910003e7 // mov    x7, sp
    WORD $0xaa0403f3 // mov    x19, x4
LBB0_231:
    WORD $0xf1004274 // subs    x20, x19, #16
    BLO LBB0_237
    WORD $0xa8c14e15 // ldp    x21, x19, [x16], #16
    WORD $0xa8814cf5 // stp    x21, x19, [x7], #16
    WORD $0xaa1403f3 // mov    x19, x20
    WORD $0xf1002294 // subs    x20, x20, #8
    BHS LBB0_238
LBB0_233:
    WORD $0xf1001274 // subs    x20, x19, #4
    BLO LBB0_239
LBB0_234:
    WORD $0xb8404615 // ldr    w21, [x16], #4
    WORD $0xaa1403f3 // mov    x19, x20
    WORD $0xb80044f5 // str    w21, [x7], #4
    WORD $0xf1000a94 // subs    x20, x20, #2
    BHS LBB0_240
LBB0_235:
    CMP $0, R19
    BEQ LBB0_241
LBB0_236:
    WORD $0x39400213 // ldrb    w19, [x16]
    WORD $0x910003f0 // mov    x16, sp
    WORD $0x390000f3 // strb    w19, [x7]
    B LBB0_242
LBB0_237:
    WORD $0xf1002274 // subs    x20, x19, #8
    BLO LBB0_233
LBB0_238:
    WORD $0xf8408615 // ldr    x21, [x16], #8
    WORD $0xaa1403f3 // mov    x19, x20
    WORD $0xf80084f5 // str    x21, [x7], #8
    WORD $0xf1001294 // subs    x20, x20, #4
    BHS LBB0_234
LBB0_239:
    WORD $0xf1000a74 // subs    x20, x19, #2
    BLO LBB0_235
LBB0_240:
    WORD $0x78402615 // ldrh    w21, [x16], #2
    WORD $0xaa1403f3 // mov    x19, x20
    WORD $0x780024f5 // strh    w21, [x7], #2
    CMP $0, R20
    BNE LBB0_236
LBB0_241:
    WORD $0x910003f0 // mov    x16, sp
LBB0_242:
    WORD $0xad417e1e // ldp    q30, q31, [x16, #32]
    WORD $0x6e238fca // cmeq    v10.16b, v30.16b, v3.16b
    WORD $0xad40761c // ldp    q28, q29, [x16]
    WORD $0x6e238feb // cmeq    v11.16b, v31.16b, v3.16b
    WORD $0x4e201d4a // and    v10.16b, v10.16b, v0.16b
    WORD $0x4e02014a // tbl    v10.16b, { v10.16b }, v2.16b
    WORD $0x6e238f88 // cmeq    v8.16b, v28.16b, v3.16b
    WORD $0x4e201d6b // and    v11.16b, v11.16b, v0.16b
    WORD $0x6e238fa9 // cmeq    v9.16b, v29.16b, v3.16b
    WORD $0x4e201d08 // and    v8.16b, v8.16b, v0.16b
    WORD $0x4e201d29 // and    v9.16b, v9.16b, v0.16b
    WORD $0x4e02016b // tbl    v11.16b, { v11.16b }, v2.16b
    WORD $0x4e020108 // tbl    v8.16b, { v8.16b }, v2.16b
    WORD $0x4e020129 // tbl    v9.16b, { v9.16b }, v2.16b
    WORD $0x4e71b94a // addv    h10, v10.8h
    WORD $0x4e71b96b // addv    h11, v11.8h
    WORD $0x4e71b908 // addv    h8, v8.8h
    WORD $0x4e71b929 // addv    h9, v9.8h
    WORD $0x1e260147 // fmov    w7, s10
    WORD $0x1e260173 // fmov    w19, s11
    WORD $0x1e260114 // fmov    w20, s8
    WORD $0x1e260135 // fmov    w21, s9
    WORD $0xd3607ce7 // lsl    x7, x7, #32
    WORD $0xaa13c0e7 // orr    x7, x7, x19, lsl #48
    WORD $0x53103eb3 // lsl    w19, w21, #16
    WORD $0xaa1400e7 // orr    x7, x7, x20
    WORD $0xaa1300e7 // orr    x7, x7, x19
    WORD $0xaa0200f3 // orr    x19, x7, x2
    CMP $0, R19
    BNE LBB0_244
    WORD $0xaa1f03e2 // mov    x2, xzr
    WORD $0x92800007 // mov    x7, #-1
    B LBB0_245
LBB0_244:
    WORD $0x8a2200f3 // bic    x19, x7, x2
    WORD $0xaa130442 // orr    x2, x2, x19, lsl #1
    WORD $0x8a2200e7 // bic    x7, x7, x2
    WORD $0x9201f0e7 // and    x7, x7, #0xaaaaaaaaaaaaaaaa
    WORD $0xab1300e7 // adds    x7, x7, x19
    WORD $0xd37ff8e7 // lsl    x7, x7, #1
    WORD $0xd200f0e7 // eor    x7, x7, #0x5555555555555555
    WORD $0x8a0200e7 // and    x7, x7, x2
    WORD $0x1a9f37e2 // cset    w2, hs
    WORD $0xaa2703e7 // mvn    x7, x7
LBB0_245:
    WORD $0x6e218fff // cmeq    v31.16b, v31.16b, v1.16b
    WORD $0x6e218fde // cmeq    v30.16b, v30.16b, v1.16b
    WORD $0x4e201fff // and    v31.16b, v31.16b, v0.16b
    WORD $0x4e0203ff // tbl    v31.16b, { v31.16b }, v2.16b
    WORD $0x4e201fde // and    v30.16b, v30.16b, v0.16b
    WORD $0x6e218f88 // cmeq    v8.16b, v28.16b, v1.16b
    WORD $0x4e0203de // tbl    v30.16b, { v30.16b }, v2.16b
    WORD $0x6e218fa9 // cmeq    v9.16b, v29.16b, v1.16b
    WORD $0x4e201d08 // and    v8.16b, v8.16b, v0.16b
    WORD $0x4e201d29 // and    v9.16b, v9.16b, v0.16b
    WORD $0x4e71bbff // addv    h31, v31.8h
    WORD $0x4e020108 // tbl    v8.16b, { v8.16b }, v2.16b
    WORD $0x4e020129 // tbl    v9.16b, { v9.16b }, v2.16b
    WORD $0x4e71bbde // addv    h30, v30.8h
    WORD $0x1e2603f3 // fmov    w19, s31
    WORD $0x4e71b908 // addv    h8, v8.8h
    WORD $0x4e71b93f // addv    h31, v9.8h
    WORD $0x1e2603d4 // fmov    w20, s30
    WORD $0xd3503e73 // lsl    x19, x19, #48
    WORD $0x1e260115 // fmov    w21, s8
    WORD $0xaa148273 // orr    x19, x19, x20, lsl #32
    WORD $0x1e2603f4 // fmov    w20, s31
    WORD $0xaa150273 // orr    x19, x19, x21
    WORD $0x53103e94 // lsl    w20, w20, #16
    WORD $0xaa140273 // orr    x19, x19, x20
    WORD $0x8a070267 // and    x7, x19, x7
    WORD $0x9202e0f3 // and    x19, x7, #0x4444444444444444
    WORD $0x4e080cfe // dup    v30.2d, x7
    WORD $0x9201e0e7 // and    x7, x7, #0x8888888888888888
    WORD $0x4e080e7f // dup    v31.2d, x19
    WORD $0x0420bfe9 // movprfx    z9, z31
    WORD $0x04d000e9 // mul    z9.d, p0/m, z9.d, z7.d
    WORD $0x4e271fde // and    v30.16b, v30.16b, v7.16b
    WORD $0x0420bfc8 // movprfx    z8, z30
    WORD $0x04d00288 // mul    z8.d, p0/m, z8.d, z20.d
    WORD $0x6e291d08 // eor    v8.16b, v8.16b, v9.16b
    WORD $0x04d0027f // mul    z31.d, p0/m, z31.d, z19.d
    WORD $0x4e080ce9 // dup    v9.2d, x7
    WORD $0x0420bd2c // movprfx    z12, z9
    WORD $0x04d002cc // mul    z12.d, p0/m, z12.d, z22.d
    WORD $0x4e0807ca // dup    v10.2d, v30.d[0]
    WORD $0x6e1e43cb // ext    v11.16b, v30.16b, v30.16b, #8
    WORD $0x4e1807de // dup    v30.2d, v30.d[1]
    WORD $0x04d002a9 // mul    z9.d, p0/m, z9.d, z21.d
    WORD $0x04d0022a // mul    z10.d, p0/m, z10.d, z17.d
    WORD $0x04d0025e // mul    z30.d, p0/m, z30.d, z18.d
    WORD $0x6e2c1fff // eor    v31.16b, v31.16b, v12.16b
    WORD $0x6e291d08 // eor    v8.16b, v8.16b, v9.16b
    WORD $0x0420bd69 // movprfx    z9, z11
    WORD $0x04d00209 // mul    z9.d, p0/m, z9.d, z16.d
    WORD $0x6e3e1d5e // eor    v30.16b, v10.16b, v30.16b
    WORD $0x6e3f1fde // eor    v30.16b, v30.16b, v31.16b
    WORD $0x6e281d3f // eor    v31.16b, v9.16b, v8.16b
    WORD $0x4e3b1fff // and    v31.16b, v31.16b, v27.16b
    WORD $0x4e311fde // and    v30.16b, v30.16b, v17.16b
    WORD $0x4ebf1fde // orr    v30.16b, v30.16b, v31.16b
    WORD $0x6e1e43df // ext    v31.16b, v30.16b, v30.16b, #8
    WORD $0x6e378f88 // cmeq    v8.16b, v28.16b, v23.16b
    WORD $0x6e268f9c // cmeq    v28.16b, v28.16b, v6.16b
    WORD $0x4e201d08 // and    v8.16b, v8.16b, v0.16b
    WORD $0x0ebf1fde // orr    v30.8b, v30.8b, v31.8b
    WORD $0x6e378fbf // cmeq    v31.16b, v29.16b, v23.16b
    WORD $0x9e6603c7 // fmov    x7, d30
    WORD $0x6e268fbd // cmeq    v29.16b, v29.16b, v6.16b
    WORD $0x4e201ffe // and    v30.16b, v31.16b, v0.16b
    WORD $0x4e201fbd // and    v29.16b, v29.16b, v0.16b
    WORD $0xca0600e6 // eor    x6, x7, x6
    WORD $0x4e201f9c // and    v28.16b, v28.16b, v0.16b
    WORD $0xf10080df // cmp    x6, #32
    WORD $0x4e02011f // tbl    v31.16b, { v8.16b }, v2.16b
    WORD $0x2a2603f7 // mvn    w23, w6
    WORD $0x4e0203de // tbl    v30.16b, { v30.16b }, v2.16b
    WORD $0x1a9f97f4 // cset    w20, hi
    WORD $0x4e0203bd // tbl    v29.16b, { v29.16b }, v2.16b
    WORD $0x4e02039c // tbl    v28.16b, { v28.16b }, v2.16b
    WORD $0x4e71bbff // addv    h31, v31.8h
    WORD $0x4e71bbde // addv    h30, v30.8h
    WORD $0x4e71bbbd // addv    h29, v29.8h
    WORD $0x4e71bb9c // addv    h28, v28.8h
    WORD $0x1e2603d5 // fmov    w21, s30
    WORD $0x1e2603b6 // fmov    w22, s29
    WORD $0x1e2603f3 // fmov    w19, s31
    WORD $0x1e260387 // fmov    w7, s28
    WORD $0x33103eb3 // bfi    w19, w21, #16, #16
    WORD $0x33103ec7 // bfi    w7, w22, #16, #16
    WORD $0x8a1302f5 // and    x21, x23, x19
    WORD $0xea0702f6 // ands    x22, x23, x7
    BEQ LBB0_248
LBB0_246:
    WORD $0xd10006d7 // sub    x23, x22, #1
    WORD $0x8a1502f8 // and    x24, x23, x21
    WORD $0x9e67031c // fmov    d28, x24
    WORD $0x0e205b9c // cnt    v28.8b, v28.8b
    WORD $0x2e303b9c // uaddlv    h28, v28.8b
    WORD $0x1e260398 // fmov    w24, s28
    WORD $0x8b050318 // add    x24, x24, x5
    WORD $0xeb11031f // cmp    x24, x17
    BLS LBB0_252
    WORD $0xea1602f6 // ands    x22, x23, x22
    WORD $0x91000631 // add    x17, x17, #1
    BNE LBB0_246
LBB0_248:
    WORD $0x9e6702bc // fmov    d28, x21
    WORD $0xd2407e94 // eor    x20, x20, #0xffffffff
    WORD $0x8a130293 // and    x19, x20, x19
    WORD $0xea070287 // ands    x7, x20, x7
    WORD $0x0e205b9c // cnt    v28.8b, v28.8b
    WORD $0x2e303b9c // uaddlv    h28, v28.8b
    WORD $0x1e260395 // fmov    w21, s28
    WORD $0x8b0502a5 // add    x5, x21, x5
    BEQ LBB0_251
LBB0_249:
    WORD $0xd10004f4 // sub    x20, x7, #1
    WORD $0x8a130295 // and    x21, x20, x19
    WORD $0x9e6702bc // fmov    d28, x21
    WORD $0x0e205b9c // cnt    v28.8b, v28.8b
    WORD $0x2e303b9c // uaddlv    h28, v28.8b
    WORD $0x1e260395 // fmov    w21, s28
    WORD $0x8b0502b5 // add    x21, x21, x5
    WORD $0xeb1102bf // cmp    x21, x17
    BLS LBB0_254
    WORD $0xea070287 // ands    x7, x20, x7
    WORD $0x91000631 // add    x17, x17, #1
    BNE LBB0_249
LBB0_251:
    WORD $0x9e67027c // fmov    d28, x19
    WORD $0x937ffcc6 // asr    x6, x6, #63
    WORD $0x91010210 // add    x16, x16, #64
    WORD $0x0e205b9c // cnt    v28.8b, v28.8b
    WORD $0x2e303b9c // uaddlv    h28, v28.8b
    WORD $0x1e260384 // fmov    w4, s28
    WORD $0x8b050085 // add    x5, x4, x5
    WORD $0xaa1203e4 // mov    x4, x18
    WORD $0xf1010252 // subs    x18, x18, #64
    BGE LBB0_242
    B LBB0_226
LBB0_252:
    WORD $0xf9400410 // ldr    x16, [x0, #8]
    WORD $0xdac002d1 // rbit    x17, x22
    B LBB0_255
LBB0_253:
    WORD $0x5ac00270 // rbit    w16, w19
    WORD $0x8b020231 // add    x17, x17, x2
    WORD $0x5ac01210 // clz    w16, w16
    WORD $0x8b100230 // add    x16, x17, x16
    WORD $0x91000a12 // add    x18, x16, #2
    WORD $0xf9000032 // str    x18, [x1]
    B LBB0_184
LBB0_254:
    WORD $0xf9400410 // ldr    x16, [x0, #8]
    WORD $0xdac000f1 // rbit    x17, x7
LBB0_255:
    WORD $0xdac01231 // clz    x17, x17
    WORD $0xcb040231 // sub    x17, x17, x4
    WORD $0x8b100230 // add    x16, x17, x16
    WORD $0x91000611 // add    x17, x16, #1
    WORD $0xf9000031 // str    x17, [x1]
    WORD $0xf9400412 // ldr    x18, [x0, #8]
    WORD $0xeb12023f // cmp    x17, x18
    WORD $0x9a902652 // csinc    x18, x18, x16, hs
    WORD $0xf9000032 // str    x18, [x1]
    B LBB0_184
LBB0_256:
    WORD $0x92800024 // mov    x4, #-2
    WORD $0x52800045 // mov    w5, #2
    WORD $0x8b050231 // add    x17, x17, x5
    WORD $0xab020082 // adds    x2, x4, x2
    BLE LBB0_184
LBB0_257:
    WORD $0x39400224 // ldrb    w4, [x17]
    WORD $0x7101709f // cmp    w4, #92
    BEQ LBB0_256
    WORD $0x7100889f // cmp    w4, #34
    BEQ LBB0_274
    WORD $0x92800004 // mov    x4, #-1
    WORD $0x52800025 // mov    w5, #1
    WORD $0x8b050231 // add    x17, x17, x5
    WORD $0xab020082 // adds    x2, x4, x2
    BGT LBB0_257
    B LBB0_184
LBB0_260:
    WORD $0xaa1f03f3 // mov    x19, xzr
    WORD $0x92800006 // mov    x6, #-1
    WORD $0xaa1103f4 // mov    x20, x17
    WORD $0xf10080f5 // subs    x21, x7, #32
    BHS LBB0_207
    B LBB0_279
LBB0_261:
    WORD $0x8b070202 // add    x2, x16, x7
    WORD $0x8b040245 // add    x5, x18, x4
    WORD $0xd1000442 // sub    x2, x2, #1
    WORD $0xeb02023f // cmp    x17, x2
    BHS LBB0_273
    WORD $0xf100049f // cmp    x4, #1
    BLT LBB0_273
LBB0_263:
    WORD $0x39400224 // ldrb    w4, [x17]
    WORD $0x7101709f // cmp    w4, #92
    BNE LBB0_269
    WORD $0xcb110044 // sub    x4, x2, x17
    WORD $0xf100049f // cmp    x4, #1
    BLT LBB0_958
    WORD $0x39400624 // ldrb    w4, [x17, #1]
    WORD $0x386469e4 // ldrb    w4, [x15, x4]
    CMP $0, R4
    BEQ LBB0_959
    WORD $0xeb05025f // cmp    x18, x5
    BHS LBB0_72
    WORD $0x39400246 // ldrb    w6, [x18]
    WORD $0x6b0400df // cmp    w6, w4
    BNE LBB0_72
    WORD $0x91000a31 // add    x17, x17, #2
    B LBB0_271
LBB0_269:
    WORD $0x39400246 // ldrb    w6, [x18]
    WORD $0x6b06009f // cmp    w4, w6
    BNE LBB0_72
    WORD $0x91000631 // add    x17, x17, #1
LBB0_271:
    WORD $0x91000652 // add    x18, x18, #1
    WORD $0xeb02023f // cmp    x17, x2
    BHS LBB0_273
    WORD $0xeb05025f // cmp    x18, x5
    BLO LBB0_263
LBB0_273:
    WORD $0xeb02023f // cmp    x17, x2
    WORD $0xfa450240 // ccmp    x18, x5, #0, eq
    WORD $0x1a9f17f1 // cset    w17, eq
    B LBB0_78
LBB0_274:
    WORD $0xcb100230 // sub    x16, x17, x16
    WORD $0x91000612 // add    x18, x16, #1
    WORD $0xf9000032 // str    x18, [x1]
    B LBB0_184
LBB0_275:
    WORD $0xb10004df // cmn    x6, #1
    BNE LBB0_277
    WORD $0xdac002c6 // rbit    x6, x22
    WORD $0xcb100297 // sub    x23, x20, x16
    WORD $0xdac010c6 // clz    x6, x6
    WORD $0x8b1700c6 // add    x6, x6, x23
LBB0_277:
    WORD $0x0a3302d7 // bic    w23, w22, w19
    WORD $0x531f7af8 // lsl    w24, w23, #1
    WORD $0x0a3802d6 // bic    w22, w22, w24
    WORD $0x1201f2d6 // and    w22, w22, #0xaaaaaaaa
    WORD $0x331f7af3 // bfi    w19, w23, #1, #31
    WORD $0x2b1702d6 // adds    w22, w22, w23
    WORD $0x531f7ad6 // lsl    w22, w22, #1
    WORD $0x1a9f37f7 // cset    w23, hs
    WORD $0x5200f2d6 // eor    w22, w22, #0x55555555
    WORD $0x0a1302d3 // and    w19, w22, w19
    WORD $0x2a3303f3 // mvn    w19, w19
    WORD $0x8a070267 // and    x7, x19, x7
    WORD $0xaa1703f3 // mov    x19, x23
    CMP $0, R7
    BNE LBB0_210
LBB0_278:
    WORD $0x91008294 // add    x20, x20, #32
    WORD $0xaa1503e7 // mov    x7, x21
LBB0_279:
    CMP $0, R19
    BNE LBB0_293
    WORD $0xaa0603f3 // mov    x19, x6
    CMP $0, R7
    BEQ LBB0_289
LBB0_281:
    WORD $0xcb1003f5 // neg    x21, x16
LBB0_282:
    WORD $0xaa1f03f6 // mov    x22, xzr
LBB0_283:
    WORD $0x38766a97 // ldrb    w23, [x20, x22]
    WORD $0x71008aff // cmp    w23, #34
    BEQ LBB0_288
    WORD $0x710172ff // cmp    w23, #92
    BEQ LBB0_286
    WORD $0x910006d6 // add    x22, x22, #1
    WORD $0xeb1600ff // cmp    x7, x22
    BNE LBB0_283
    B LBB0_290
LBB0_286:
    WORD $0xd10004f7 // sub    x23, x7, #1
    WORD $0xeb1602ff // cmp    x23, x22
    BEQ LBB0_935
    WORD $0x8b160294 // add    x20, x20, x22
    WORD $0xcb1600f7 // sub    x23, x7, x22
    WORD $0xd10008f8 // sub    x24, x7, #2
    WORD $0xd1000ae7 // sub    x7, x23, #2
    WORD $0x8b150297 // add    x23, x20, x21
    WORD $0xb100067f // cmn    x19, #1
    WORD $0x9a8602e6 // csel    x6, x23, x6, eq
    WORD $0x9a9302f3 // csel    x19, x23, x19, eq
    WORD $0x91000a94 // add    x20, x20, #2
    WORD $0xeb16031f // cmp    x24, x22
    BNE LBB0_282
    B LBB0_935
LBB0_288:
    WORD $0x8b160287 // add    x7, x20, x22
    WORD $0x910004f4 // add    x20, x7, #1
LBB0_289:
    WORD $0xcb100287 // sub    x7, x20, x16
    TST $(1<<63), R7
    BEQ LBB0_65
    B LBB0_935
LBB0_290:
    WORD $0x71008aff // cmp    w23, #34
    BNE LBB0_935
    WORD $0x8b070294 // add    x20, x20, x7
    B LBB0_289
LBB0_292:
    WORD $0x8b120211 // add    x17, x16, x18
    B LBB0_224
LBB0_293:
    CMP $0, R7
    BEQ LBB0_935
    WORD $0xaa3003f3 // mvn    x19, x16
    WORD $0xb10004df // cmn    x6, #1
    WORD $0x8b130293 // add    x19, x20, x19
    WORD $0x91000694 // add    x20, x20, #1
    WORD $0x9a860275 // csel    x21, x19, x6, eq
    WORD $0x9a860273 // csel    x19, x19, x6, eq
    WORD $0xd10004e7 // sub    x7, x7, #1
    WORD $0xaa1503e6 // mov    x6, x21
    CMP $0, R7
    BNE LBB0_281
    B LBB0_289
LBB0_295:
    WORD $0xf9400412 // ldr    x18, [x0, #8]
    WORD $0xf9000032 // str    x18, [x1]
    B LBB0_184
LBB0_296:
    WORD $0xd1000485 // sub    x5, x4, #1
    WORD $0xeb0200bf // cmp    x5, x2
    BEQ LBB0_184
    WORD $0x8b110211 // add    x17, x16, x17
    WORD $0x8b020231 // add    x17, x17, x2
    WORD $0xcb020082 // sub    x2, x4, x2
    WORD $0x91000a31 // add    x17, x17, #2
    WORD $0xd1000842 // sub    x2, x2, #2
    B LBB0_224
LBB0_298:
    WORD $0x71016e3f // cmp    w17, #91
    BNE LBB0_865
    WORD $0xf9400511 // ldr    x17, [x8, #8]
    WORD $0xf9400231 // ldr    x17, [x17]
    TST $(1<<63), R17
    BNE LBB0_808
    WORD $0xf9400412 // ldr    x18, [x0, #8]
    WORD $0xeb12009f // cmp    x4, x18
    BHS LBB0_305
    WORD $0x38646a02 // ldrb    w2, [x16, x4]
    WORD $0x7100345f // cmp    w2, #13
    BEQ LBB0_305
    WORD $0x7100805f // cmp    w2, #32
    BEQ LBB0_305
    WORD $0x51002c42 // sub    w2, w2, #11
    WORD $0x3100085f // cmn    w2, #2
    BHS LBB0_305
    WORD $0xaa0403e2 // mov    x2, x4
    B LBB0_322
LBB0_305:
    WORD $0x91000482 // add    x2, x4, #1
    WORD $0xeb12005f // cmp    x2, x18
    BHS LBB0_309
    WORD $0x38626a05 // ldrb    w5, [x16, x2]
    WORD $0x710034bf // cmp    w5, #13
    BEQ LBB0_309
    WORD $0x710080bf // cmp    w5, #32
    BEQ LBB0_309
    WORD $0x51002ca5 // sub    w5, w5, #11
    WORD $0x310008bf // cmn    w5, #2
    BLO LBB0_322
LBB0_309:
    WORD $0x91000882 // add    x2, x4, #2
    WORD $0xeb12005f // cmp    x2, x18
    BHS LBB0_313
    WORD $0x38626a05 // ldrb    w5, [x16, x2]
    WORD $0x710034bf // cmp    w5, #13
    BEQ LBB0_313
    WORD $0x710080bf // cmp    w5, #32
    BEQ LBB0_313
    WORD $0x51002ca5 // sub    w5, w5, #11
    WORD $0x310008bf // cmn    w5, #2
    BLO LBB0_322
LBB0_313:
    WORD $0x91000c82 // add    x2, x4, #3
    WORD $0xeb12005f // cmp    x2, x18
    BHS LBB0_317
    WORD $0x38626a05 // ldrb    w5, [x16, x2]
    WORD $0x710034bf // cmp    w5, #13
    BEQ LBB0_317
    WORD $0x710080bf // cmp    w5, #32
    BEQ LBB0_317
    WORD $0x51002ca5 // sub    w5, w5, #11
    WORD $0x310008bf // cmn    w5, #2
    BLO LBB0_322
LBB0_317:
    WORD $0x91001082 // add    x2, x4, #4
    WORD $0xeb12005f // cmp    x2, x18
    BHS LBB0_320
LBB0_318:
    WORD $0x38626a05 // ldrb    w5, [x16, x2]
    WORD $0x9ac52166 // lsl    x6, x11, x5
    WORD $0x710080bf // cmp    w5, #32
    WORD $0x8a0c00c5 // and    x5, x6, x12
    WORD $0xfa4098a4 // ccmp    x5, #0, #4, ls
    BEQ LBB0_321
    WORD $0x91000442 // add    x2, x2, #1
    WORD $0xeb02025f // cmp    x18, x2
    BNE LBB0_318
    B LBB0_323
LBB0_320:
    WORD $0xaa0203e4 // mov    x4, x2
    B LBB0_323
LBB0_321:
    WORD $0xeb12005f // cmp    x2, x18
    BHS LBB0_323
LBB0_322:
    WORD $0x91000444 // add    x4, x2, #1
    WORD $0xf9000024 // str    x4, [x1]
    WORD $0x38626a12 // ldrb    w18, [x16, x2]
    WORD $0x7101765f // cmp    w18, #93
    BEQ LBB0_811
LBB0_323:
    WORD $0xd1000492 // sub    x18, x4, #1
    WORD $0xf9000032 // str    x18, [x1]
LBB0_324:
    WORD $0xf1000631 // subs    x17, x17, #1
    BLT LBB0_481
    WORD $0xf9400404 // ldr    x4, [x0, #8]
    WORD $0xeb04025f // cmp    x18, x4
    BHS LBB0_330
    WORD $0x38726a02 // ldrb    w2, [x16, x18]
    WORD $0x7100345f // cmp    w2, #13
    BEQ LBB0_330
    WORD $0x7100805f // cmp    w2, #32
    BEQ LBB0_330
    WORD $0x51002c42 // sub    w2, w2, #11
    WORD $0x3100085f // cmn    w2, #2
    BHS LBB0_330
    WORD $0xaa1203e2 // mov    x2, x18
    B LBB0_346
LBB0_330:
    WORD $0x91000642 // add    x2, x18, #1
    WORD $0xeb04005f // cmp    x2, x4
    BHS LBB0_334
    WORD $0x38626a05 // ldrb    w5, [x16, x2]
    WORD $0x710034bf // cmp    w5, #13
    BEQ LBB0_334
    WORD $0x710080bf // cmp    w5, #32
    BEQ LBB0_334
    WORD $0x51002ca5 // sub    w5, w5, #11
    WORD $0x310008bf // cmn    w5, #2
    BLO LBB0_346
LBB0_334:
    WORD $0x91000a42 // add    x2, x18, #2
    WORD $0xeb04005f // cmp    x2, x4
    BHS LBB0_338
    WORD $0x38626a05 // ldrb    w5, [x16, x2]
    WORD $0x710034bf // cmp    w5, #13
    BEQ LBB0_338
    WORD $0x710080bf // cmp    w5, #32
    BEQ LBB0_338
    WORD $0x51002ca5 // sub    w5, w5, #11
    WORD $0x310008bf // cmn    w5, #2
    BLO LBB0_346
LBB0_338:
    WORD $0x91000e42 // add    x2, x18, #3
    WORD $0xeb04005f // cmp    x2, x4
    BHS LBB0_342
    WORD $0x38626a05 // ldrb    w5, [x16, x2]
    WORD $0x710034bf // cmp    w5, #13
    BEQ LBB0_342
    WORD $0x710080bf // cmp    w5, #32
    BEQ LBB0_342
    WORD $0x51002ca5 // sub    w5, w5, #11
    WORD $0x310008bf // cmn    w5, #2
    BLO LBB0_346
LBB0_342:
    WORD $0x91001242 // add    x2, x18, #4
    WORD $0xeb04005f // cmp    x2, x4
    BHS LBB0_404
LBB0_343:
    WORD $0x38626a05 // ldrb    w5, [x16, x2]
    WORD $0x9ac52166 // lsl    x6, x11, x5
    WORD $0x710080bf // cmp    w5, #32
    WORD $0x8a0c00c5 // and    x5, x6, x12
    WORD $0xfa4098a4 // ccmp    x5, #0, #4, ls
    BEQ LBB0_345
    WORD $0x91000442 // add    x2, x2, #1
    WORD $0xeb02009f // cmp    x4, x2
    BNE LBB0_343
    B LBB0_405
LBB0_345:
    WORD $0xeb04005f // cmp    x2, x4
    BHS LBB0_405
LBB0_346:
    WORD $0x91000452 // add    x18, x2, #1
    WORD $0xf9000032 // str    x18, [x1]
    WORD $0x38626a04 // ldrb    w4, [x16, x2]
    WORD $0x7101689f // cmp    w4, #90
    BGT LBB0_367
    WORD $0x7100bc9f // cmp    w4, #47
    BLE LBB0_398
    WORD $0x5100c084 // sub    w4, w4, #48
    WORD $0x7100289f // cmp    w4, #10
    BHS LBB0_404
LBB0_349:
    WORD $0xf9400404 // ldr    x4, [x0, #8]
    WORD $0xcb120084 // sub    x4, x4, x18
    WORD $0xf100409f // cmp    x4, #16
    BLO LBB0_353
    WORD $0xaa1f03e5 // mov    x5, xzr
LBB0_351:
    WORD $0x3cf26a1c // ldr    q28, [x16, x18]
    WORD $0x6e248f9d // cmeq    v29.16b, v28.16b, v4.16b
    WORD $0x4e251f9c // and    v28.16b, v28.16b, v5.16b
    WORD $0x6e268f9c // cmeq    v28.16b, v28.16b, v6.16b
    WORD $0x4ebd1f9c // orr    v28.16b, v28.16b, v29.16b
    WORD $0x4e201f9c // and    v28.16b, v28.16b, v0.16b
    WORD $0x4e02039c // tbl    v28.16b, { v28.16b }, v2.16b
    WORD $0x4e71bb9c // addv    h28, v28.8h
    WORD $0x1e260386 // fmov    w6, s28
    CMP $0, R6
    BNE LBB0_362
    WORD $0xd1004084 // sub    x4, x4, #16
    WORD $0x91004252 // add    x18, x18, #16
    WORD $0x910040a5 // add    x5, x5, #16
    WORD $0xf1003c9f // cmp    x4, #15
    BHI LBB0_351
LBB0_353:
    WORD $0x8b120212 // add    x18, x16, x18
    CMP $0, R4
    BEQ LBB0_361
    WORD $0x8b040242 // add    x2, x18, x4
LBB0_355:
    WORD $0x39400245 // ldrb    w5, [x18]
    WORD $0x7100b0bf // cmp    w5, #44
    BHI LBB0_357
    WORD $0x9ac52166 // lsl    x6, x11, x5
    WORD $0xea0d00df // tst    x6, x13
    BNE LBB0_361
LBB0_357:
    WORD $0x710174bf // cmp    w5, #93
    BEQ LBB0_361
    WORD $0x7101f4bf // cmp    w5, #125
    BEQ LBB0_361
    WORD $0x91000652 // add    x18, x18, #1
    WORD $0xf1000484 // subs    x4, x4, #1
    BNE LBB0_355
    WORD $0xaa0203f2 // mov    x18, x2
LBB0_361:
    WORD $0xcb100252 // sub    x18, x18, x16
    WORD $0xf9000032 // str    x18, [x1]
    B LBB0_405
LBB0_362:
    WORD $0x5ac000c4 // rbit    w4, w6
    WORD $0x5ac01084 // clz    w4, w4
    WORD $0x8b120092 // add    x18, x4, x18
    WORD $0xf100065f // cmp    x18, #1
    WORD $0xf9000032 // str    x18, [x1]
    BLT LBB0_405
    WORD $0x8b050092 // add    x18, x4, x5
    WORD $0x8b020210 // add    x16, x16, x2
LBB0_364:
    WORD $0x38726a04 // ldrb    w4, [x16, x18]
    WORD $0x9ac42165 // lsl    x5, x11, x4
    WORD $0x7100809f // cmp    w4, #32
    WORD $0x8a0c00a4 // and    x4, x5, x12
    WORD $0xfa409884 // ccmp    x4, #0, #4, ls
    WORD $0x8b120044 // add    x4, x2, x18
    BEQ LBB0_430
    WORD $0xd1000652 // sub    x18, x18, #1
    WORD $0xf9000024 // str    x4, [x1]
    WORD $0x8b120045 // add    x5, x2, x18
    WORD $0x910008a6 // add    x6, x5, #2
    WORD $0xf10004df // cmp    x6, #1
    BHI LBB0_364
    WORD $0x910004b2 // add    x18, x5, #1
    B LBB0_405
LBB0_367:
    WORD $0x7101b49f // cmp    w4, #109
    BLE LBB0_401
    WORD $0x7101b89f // cmp    w4, #110
    BEQ LBB0_427
    WORD $0x7101d09f // cmp    w4, #116
    BEQ LBB0_427
    WORD $0x7101ec9f // cmp    w4, #123
    BNE LBB0_404
    WORD $0xf9400405 // ldr    x5, [x0, #8]
    WORD $0xaa1f03e7 // mov    x7, xzr
    WORD $0xaa1f03e4 // mov    x4, xzr
    WORD $0xaa1f03e6 // mov    x6, xzr
    WORD $0xaa1f03e2 // mov    x2, xzr
    WORD $0x8b120210 // add    x16, x16, x18
    WORD $0xcb1200a5 // sub    x5, x5, x18
    WORD $0xf10100b2 // subs    x18, x5, #64
    BGE LBB0_388
LBB0_372:
    WORD $0xf10000bf // cmp    x5, #0
    BLE LBB0_478
    WORD $0x92402e13 // and    x19, x16, #0xfff
    WORD $0xad0063f8 // stp    q24, q24, [sp]
    WORD $0xf13f067f // cmp    x19, #4033
    WORD $0xad0163f8 // stp    q24, q24, [sp, #32]
    BLO LBB0_388
    WORD $0xf10080b4 // subs    x20, x5, #32
    BLO LBB0_376
    WORD $0xa9415616 // ldp    x22, x21, [x16, #16]
    WORD $0xaa0903f3 // mov    x19, x9
    WORD $0x3cc2061c // ldr    q28, [x16], #32
    WORD $0x3d8003fc // str    q28, [sp]
    WORD $0xa90157f6 // stp    x22, x21, [sp, #16]
    B LBB0_377
LBB0_376:
    WORD $0x910003f3 // mov    x19, sp
    WORD $0xaa0503f4 // mov    x20, x5
LBB0_377:
    WORD $0xf1004295 // subs    x21, x20, #16
    BLO LBB0_383
    WORD $0xa8c15216 // ldp    x22, x20, [x16], #16
    WORD $0xa8815276 // stp    x22, x20, [x19], #16
    WORD $0xaa1503f4 // mov    x20, x21
    WORD $0xf10022b5 // subs    x21, x21, #8
    BHS LBB0_384
LBB0_379:
    WORD $0xf1001295 // subs    x21, x20, #4
    BLO LBB0_385
LBB0_380:
    WORD $0xb8404616 // ldr    w22, [x16], #4
    WORD $0xaa1503f4 // mov    x20, x21
    WORD $0xb8004676 // str    w22, [x19], #4
    WORD $0xf1000ab5 // subs    x21, x21, #2
    BHS LBB0_386
LBB0_381:
    CMP $0, R20
    BEQ LBB0_387
LBB0_382:
    WORD $0x39400214 // ldrb    w20, [x16]
    WORD $0x910003f0 // mov    x16, sp
    WORD $0x39000274 // strb    w20, [x19]
    B LBB0_388
LBB0_383:
    WORD $0xf1002295 // subs    x21, x20, #8
    BLO LBB0_379
LBB0_384:
    WORD $0xf8408616 // ldr    x22, [x16], #8
    WORD $0xaa1503f4 // mov    x20, x21
    WORD $0xf8008676 // str    x22, [x19], #8
    WORD $0xf10012b5 // subs    x21, x21, #4
    BHS LBB0_380
LBB0_385:
    WORD $0xf1000a95 // subs    x21, x20, #2
    BLO LBB0_381
LBB0_386:
    WORD $0x78402616 // ldrh    w22, [x16], #2
    WORD $0xaa1503f4 // mov    x20, x21
    WORD $0x78002676 // strh    w22, [x19], #2
    CMP $0, R21
    BNE LBB0_382
LBB0_387:
    WORD $0x910003f0 // mov    x16, sp
LBB0_388:
    WORD $0xad417e1e // ldp    q30, q31, [x16, #32]
    WORD $0x6e238fca // cmeq    v10.16b, v30.16b, v3.16b
    WORD $0xad40761c // ldp    q28, q29, [x16]
    WORD $0x6e238feb // cmeq    v11.16b, v31.16b, v3.16b
    WORD $0x4e201d4a // and    v10.16b, v10.16b, v0.16b
    WORD $0x4e02014a // tbl    v10.16b, { v10.16b }, v2.16b
    WORD $0x6e238f88 // cmeq    v8.16b, v28.16b, v3.16b
    WORD $0x4e201d6b // and    v11.16b, v11.16b, v0.16b
    WORD $0x6e238fa9 // cmeq    v9.16b, v29.16b, v3.16b
    WORD $0x4e201d08 // and    v8.16b, v8.16b, v0.16b
    WORD $0x4e201d29 // and    v9.16b, v9.16b, v0.16b
    WORD $0x4e02016b // tbl    v11.16b, { v11.16b }, v2.16b
    WORD $0x4e020108 // tbl    v8.16b, { v8.16b }, v2.16b
    WORD $0x4e020129 // tbl    v9.16b, { v9.16b }, v2.16b
    WORD $0x4e71b94a // addv    h10, v10.8h
    WORD $0x4e71b96b // addv    h11, v11.8h
    WORD $0x4e71b908 // addv    h8, v8.8h
    WORD $0x4e71b929 // addv    h9, v9.8h
    WORD $0x1e260153 // fmov    w19, s10
    WORD $0x1e260174 // fmov    w20, s11
    WORD $0x1e260115 // fmov    w21, s8
    WORD $0x1e260136 // fmov    w22, s9
    WORD $0xd3607e73 // lsl    x19, x19, #32
    WORD $0xaa14c273 // orr    x19, x19, x20, lsl #48
    WORD $0x53103ed4 // lsl    w20, w22, #16
    WORD $0xaa150273 // orr    x19, x19, x21
    WORD $0xaa140273 // orr    x19, x19, x20
    WORD $0xaa040274 // orr    x20, x19, x4
    CMP $0, R20
    BNE LBB0_390
    WORD $0xaa1f03e4 // mov    x4, xzr
    WORD $0x92800013 // mov    x19, #-1
    B LBB0_391
LBB0_390:
    WORD $0x8a240274 // bic    x20, x19, x4
    WORD $0xaa140484 // orr    x4, x4, x20, lsl #1
    WORD $0x8a240273 // bic    x19, x19, x4
    WORD $0x9201f273 // and    x19, x19, #0xaaaaaaaaaaaaaaaa
    WORD $0xab140273 // adds    x19, x19, x20
    WORD $0xd37ffa73 // lsl    x19, x19, #1
    WORD $0xd200f273 // eor    x19, x19, #0x5555555555555555
    WORD $0x8a040273 // and    x19, x19, x4
    WORD $0x1a9f37e4 // cset    w4, hs
    WORD $0xaa3303f3 // mvn    x19, x19
LBB0_391:
    WORD $0x6e218fff // cmeq    v31.16b, v31.16b, v1.16b
    WORD $0x6e218fde // cmeq    v30.16b, v30.16b, v1.16b
    WORD $0x4e201fff // and    v31.16b, v31.16b, v0.16b
    WORD $0x4e0203ff // tbl    v31.16b, { v31.16b }, v2.16b
    WORD $0x4e201fde // and    v30.16b, v30.16b, v0.16b
    WORD $0x6e218f88 // cmeq    v8.16b, v28.16b, v1.16b
    WORD $0x4e0203de // tbl    v30.16b, { v30.16b }, v2.16b
    WORD $0x6e218fa9 // cmeq    v9.16b, v29.16b, v1.16b
    WORD $0x4e201d08 // and    v8.16b, v8.16b, v0.16b
    WORD $0x4e201d29 // and    v9.16b, v9.16b, v0.16b
    WORD $0x4e71bbff // addv    h31, v31.8h
    WORD $0x4e020108 // tbl    v8.16b, { v8.16b }, v2.16b
    WORD $0x4e020129 // tbl    v9.16b, { v9.16b }, v2.16b
    WORD $0x4e71bbde // addv    h30, v30.8h
    WORD $0x1e2603f4 // fmov    w20, s31
    WORD $0x4e71b908 // addv    h8, v8.8h
    WORD $0x4e71b93f // addv    h31, v9.8h
    WORD $0x1e2603d5 // fmov    w21, s30
    WORD $0xd3503e94 // lsl    x20, x20, #48
    WORD $0x1e260116 // fmov    w22, s8
    WORD $0xaa158294 // orr    x20, x20, x21, lsl #32
    WORD $0x1e2603f5 // fmov    w21, s31
    WORD $0xaa160294 // orr    x20, x20, x22
    WORD $0x53103eb5 // lsl    w21, w21, #16
    WORD $0xaa150294 // orr    x20, x20, x21
    WORD $0x8a130293 // and    x19, x20, x19
    WORD $0x9202e274 // and    x20, x19, #0x4444444444444444
    WORD $0x4e080e7e // dup    v30.2d, x19
    WORD $0x9201e273 // and    x19, x19, #0x8888888888888888
    WORD $0x4e080e9f // dup    v31.2d, x20
    WORD $0x0420bfe9 // movprfx    z9, z31
    WORD $0x04d000e9 // mul    z9.d, p0/m, z9.d, z7.d
    WORD $0x4e271fde // and    v30.16b, v30.16b, v7.16b
    WORD $0x0420bfc8 // movprfx    z8, z30
    WORD $0x04d00288 // mul    z8.d, p0/m, z8.d, z20.d
    WORD $0x6e291d08 // eor    v8.16b, v8.16b, v9.16b
    WORD $0x04d0027f // mul    z31.d, p0/m, z31.d, z19.d
    WORD $0x4e080e69 // dup    v9.2d, x19
    WORD $0x0420bd2c // movprfx    z12, z9
    WORD $0x04d002cc // mul    z12.d, p0/m, z12.d, z22.d
    WORD $0x4e0807ca // dup    v10.2d, v30.d[0]
    WORD $0x6e1e43cb // ext    v11.16b, v30.16b, v30.16b, #8
    WORD $0x4e1807de // dup    v30.2d, v30.d[1]
    WORD $0x04d002a9 // mul    z9.d, p0/m, z9.d, z21.d
    WORD $0x04d0022a // mul    z10.d, p0/m, z10.d, z17.d
    WORD $0x04d0025e // mul    z30.d, p0/m, z30.d, z18.d
    WORD $0x6e2c1fff // eor    v31.16b, v31.16b, v12.16b
    WORD $0x6e291d08 // eor    v8.16b, v8.16b, v9.16b
    WORD $0x0420bd69 // movprfx    z9, z11
    WORD $0x04d00209 // mul    z9.d, p0/m, z9.d, z16.d
    WORD $0x6e3e1d5e // eor    v30.16b, v10.16b, v30.16b
    WORD $0x6e3f1fde // eor    v30.16b, v30.16b, v31.16b
    WORD $0x6e281d3f // eor    v31.16b, v9.16b, v8.16b
    WORD $0x4e3b1fff // and    v31.16b, v31.16b, v27.16b
    WORD $0x4e311fde // and    v30.16b, v30.16b, v17.16b
    WORD $0x4ebf1fde // orr    v30.16b, v30.16b, v31.16b
    WORD $0x6e1e43df // ext    v31.16b, v30.16b, v30.16b, #8
    WORD $0x6e398f88 // cmeq    v8.16b, v28.16b, v25.16b
    WORD $0x6e3a8f9c // cmeq    v28.16b, v28.16b, v26.16b
    WORD $0x4e201d08 // and    v8.16b, v8.16b, v0.16b
    WORD $0x0ebf1fde // orr    v30.8b, v30.8b, v31.8b
    WORD $0x6e398fbf // cmeq    v31.16b, v29.16b, v25.16b
    WORD $0x9e6603d3 // fmov    x19, d30
    WORD $0x6e3a8fbd // cmeq    v29.16b, v29.16b, v26.16b
    WORD $0x4e201ffe // and    v30.16b, v31.16b, v0.16b
    WORD $0x4e201fbd // and    v29.16b, v29.16b, v0.16b
    WORD $0xca070267 // eor    x7, x19, x7
    WORD $0x4e201f9c // and    v28.16b, v28.16b, v0.16b
    WORD $0xf10080ff // cmp    x7, #32
    WORD $0x4e02011f // tbl    v31.16b, { v8.16b }, v2.16b
    WORD $0x2a2703f8 // mvn    w24, w7
    WORD $0x4e0203de // tbl    v30.16b, { v30.16b }, v2.16b
    WORD $0x1a9f97f5 // cset    w21, hi
    WORD $0x4e0203bd // tbl    v29.16b, { v29.16b }, v2.16b
    WORD $0x4e02039c // tbl    v28.16b, { v28.16b }, v2.16b
    WORD $0x4e71bbff // addv    h31, v31.8h
    WORD $0x4e71bbde // addv    h30, v30.8h
    WORD $0x4e71bbbd // addv    h29, v29.8h
    WORD $0x4e71bb9c // addv    h28, v28.8h
    WORD $0x1e2603d6 // fmov    w22, s30
    WORD $0x1e2603b7 // fmov    w23, s29
    WORD $0x1e2603f4 // fmov    w20, s31
    WORD $0x1e260393 // fmov    w19, s28
    WORD $0x33103ed4 // bfi    w20, w22, #16, #16
    WORD $0x33103ef3 // bfi    w19, w23, #16, #16
    WORD $0x8a140316 // and    x22, x24, x20
    WORD $0xea130317 // ands    x23, x24, x19
    BEQ LBB0_394
LBB0_392:
    WORD $0xd10006f8 // sub    x24, x23, #1
    WORD $0x8a160319 // and    x25, x24, x22
    WORD $0x9e67033c // fmov    d28, x25
    WORD $0x0e205b9c // cnt    v28.8b, v28.8b
    WORD $0x2e303b9c // uaddlv    h28, v28.8b
    WORD $0x1e260399 // fmov    w25, s28
    WORD $0x8b060339 // add    x25, x25, x6
    WORD $0xeb02033f // cmp    x25, x2
    BLS LBB0_468
    WORD $0xea170317 // ands    x23, x24, x23
    WORD $0x91000442 // add    x2, x2, #1
    BNE LBB0_392
LBB0_394:
    WORD $0x9e6702dc // fmov    d28, x22
    WORD $0xd2407eb5 // eor    x21, x21, #0xffffffff
    WORD $0x8a1402b4 // and    x20, x21, x20
    WORD $0xea1302b3 // ands    x19, x21, x19
    WORD $0x0e205b9c // cnt    v28.8b, v28.8b
    WORD $0x2e303b9c // uaddlv    h28, v28.8b
    WORD $0x1e260396 // fmov    w22, s28
    WORD $0x8b0602c6 // add    x6, x22, x6
    BEQ LBB0_397
LBB0_395:
    WORD $0xd1000675 // sub    x21, x19, #1
    WORD $0x8a1402b6 // and    x22, x21, x20
    WORD $0x9e6702dc // fmov    d28, x22
    WORD $0x0e205b9c // cnt    v28.8b, v28.8b
    WORD $0x2e303b9c // uaddlv    h28, v28.8b
    WORD $0x1e260396 // fmov    w22, s28
    WORD $0x8b0602d6 // add    x22, x22, x6
    WORD $0xeb0202df // cmp    x22, x2
    BLS LBB0_470
    WORD $0xea1302b3 // ands    x19, x21, x19
    WORD $0x91000442 // add    x2, x2, #1
    BNE LBB0_395
LBB0_397:
    WORD $0x9e67029c // fmov    d28, x20
    WORD $0x937ffce7 // asr    x7, x7, #63
    WORD $0x91010210 // add    x16, x16, #64
    WORD $0x0e205b9c // cnt    v28.8b, v28.8b
    WORD $0x2e303b9c // uaddlv    h28, v28.8b
    WORD $0x1e260385 // fmov    w5, s28
    WORD $0x8b0600a6 // add    x6, x5, x6
    WORD $0xaa1203e5 // mov    x5, x18
    WORD $0xf1010252 // subs    x18, x18, #64
    BGE LBB0_388
    B LBB0_372
LBB0_398:
    CMP $0, R4
    BEQ LBB0_405
    WORD $0x7100889f // cmp    w4, #34
    BEQ LBB0_431
    WORD $0x7100b49f // cmp    w4, #45
    BEQ LBB0_349
    B LBB0_404
LBB0_401:
    WORD $0x71016c9f // cmp    w4, #91
    BEQ LBB0_441
    WORD $0x7101989f // cmp    w4, #102
    BNE LBB0_404
    WORD $0xf9400404 // ldr    x4, [x0, #8]
    WORD $0x91001450 // add    x16, x2, #5
    B LBB0_428
LBB0_404:
    WORD $0xaa0203f2 // mov    x18, x2
    WORD $0xf9000022 // str    x2, [x1]
LBB0_405:
    WORD $0xa9401010 // ldp    x16, x4, [x0]
    WORD $0xeb04025f // cmp    x18, x4
    BHS LBB0_410
    WORD $0x38726a02 // ldrb    w2, [x16, x18]
    WORD $0x7100345f // cmp    w2, #13
    BEQ LBB0_410
    WORD $0x7100805f // cmp    w2, #32
    BEQ LBB0_410
    WORD $0x51002c42 // sub    w2, w2, #11
    WORD $0x3100085f // cmn    w2, #2
    BHS LBB0_410
    WORD $0xaa1203e2 // mov    x2, x18
    B LBB0_426
LBB0_410:
    WORD $0x91000642 // add    x2, x18, #1
    WORD $0xeb04005f // cmp    x2, x4
    BHS LBB0_414
    WORD $0x38626a05 // ldrb    w5, [x16, x2]
    WORD $0x710034bf // cmp    w5, #13
    BEQ LBB0_414
    WORD $0x710080bf // cmp    w5, #32
    BEQ LBB0_414
    WORD $0x51002ca5 // sub    w5, w5, #11
    WORD $0x310008bf // cmn    w5, #2
    BLO LBB0_426
LBB0_414:
    WORD $0x91000a42 // add    x2, x18, #2
    WORD $0xeb04005f // cmp    x2, x4
    BHS LBB0_418
    WORD $0x38626a05 // ldrb    w5, [x16, x2]
    WORD $0x710034bf // cmp    w5, #13
    BEQ LBB0_418
    WORD $0x710080bf // cmp    w5, #32
    BEQ LBB0_418
    WORD $0x51002ca5 // sub    w5, w5, #11
    WORD $0x310008bf // cmn    w5, #2
    BLO LBB0_426
LBB0_418:
    WORD $0x91000e42 // add    x2, x18, #3
    WORD $0xeb04005f // cmp    x2, x4
    BHS LBB0_422
    WORD $0x38626a05 // ldrb    w5, [x16, x2]
    WORD $0x710034bf // cmp    w5, #13
    BEQ LBB0_422
    WORD $0x710080bf // cmp    w5, #32
    BEQ LBB0_422
    WORD $0x51002ca5 // sub    w5, w5, #11
    WORD $0x310008bf // cmn    w5, #2
    BLO LBB0_426
LBB0_422:
    WORD $0x91001242 // add    x2, x18, #4
    WORD $0xeb04005f // cmp    x2, x4
    BHS LBB0_809
LBB0_423:
    WORD $0x38626a12 // ldrb    w18, [x16, x2]
    WORD $0x9ad22165 // lsl    x5, x11, x18
    WORD $0x7100825f // cmp    w18, #32
    WORD $0x8a0c00b2 // and    x18, x5, x12
    WORD $0xfa409a44 // ccmp    x18, #0, #4, ls
    BEQ LBB0_425
    WORD $0x91000442 // add    x2, x2, #1
    WORD $0xeb02009f // cmp    x4, x2
    BNE LBB0_423
    B LBB0_865
LBB0_425:
    WORD $0xeb04005f // cmp    x2, x4
    BHS LBB0_865
LBB0_426:
    WORD $0x91000452 // add    x18, x2, #1
    WORD $0xf9000032 // str    x18, [x1]
    WORD $0x38626a04 // ldrb    w4, [x16, x2]
    WORD $0x7100b09f // cmp    w4, #44
    BEQ LBB0_324
    B LBB0_810
LBB0_427:
    WORD $0xf9400404 // ldr    x4, [x0, #8]
    WORD $0x91001050 // add    x16, x2, #4
LBB0_428:
    WORD $0xeb04021f // cmp    x16, x4
    BHI LBB0_405
    WORD $0xaa1003f2 // mov    x18, x16
    WORD $0xf9000030 // str    x16, [x1]
    B LBB0_405
LBB0_430:
    WORD $0x91000492 // add    x18, x4, #1
    B LBB0_405
LBB0_431:
    WORD $0xf9400405 // ldr    x5, [x0, #8]
    WORD $0xcb1200a4 // sub    x4, x5, x18
    WORD $0xf100809f // cmp    x4, #32
    BLT LBB0_477
    WORD $0xaa1f03e4 // mov    x4, xzr
    WORD $0xaa1f03f3 // mov    x19, xzr
    WORD $0x8b020206 // add    x6, x16, x2
    WORD $0xcb0200a5 // sub    x5, x5, x2
    WORD $0x528003e7 // mov    w7, #31
LBB0_433:
    WORD $0x8b0400d4 // add    x20, x6, x4
    WORD $0x3cc1129c // ldur    q28, [x20, #17]
    WORD $0x3cc0129e // ldur    q30, [x20, #1]
    WORD $0x6e238f9d // cmeq    v29.16b, v28.16b, v3.16b
    WORD $0x6e218f9c // cmeq    v28.16b, v28.16b, v1.16b
    WORD $0x4e201fbd // and    v29.16b, v29.16b, v0.16b
    WORD $0x4e0203bd // tbl    v29.16b, { v29.16b }, v2.16b
    WORD $0x4e201f9c // and    v28.16b, v28.16b, v0.16b
    WORD $0x4e02039c // tbl    v28.16b, { v28.16b }, v2.16b
    WORD $0x4e71bbbd // addv    h29, v29.8h
    WORD $0x4e71bb9c // addv    h28, v28.8h
    WORD $0x1e2603b4 // fmov    w20, s29
    WORD $0x6e218fdd // cmeq    v29.16b, v30.16b, v1.16b
    WORD $0x6e238fde // cmeq    v30.16b, v30.16b, v3.16b
    WORD $0x4e201fbd // and    v29.16b, v29.16b, v0.16b
    WORD $0x4e201fde // and    v30.16b, v30.16b, v0.16b
    WORD $0x4e0203de // tbl    v30.16b, { v30.16b }, v2.16b
    WORD $0x4e0203bd // tbl    v29.16b, { v29.16b }, v2.16b
    WORD $0x1e260396 // fmov    w22, s28
    WORD $0x4e71bbde // addv    h30, v30.8h
    WORD $0x4e71bbbd // addv    h29, v29.8h
    WORD $0x1e2603d5 // fmov    w21, s30
    WORD $0x33103e95 // bfi    w21, w20, #16, #16
    WORD $0x1e2603b4 // fmov    w20, s29
    WORD $0x710002bf // cmp    w21, #0
    WORD $0xfa400a60 // ccmp    x19, #0, #0, eq
    WORD $0x33103ed4 // bfi    w20, w22, #16, #16
    BEQ LBB0_435
    WORD $0x0a3302b6 // bic    w22, w21, w19
    WORD $0x2a160673 // orr    w19, w19, w22, lsl #1
    WORD $0x0a3302b5 // bic    w21, w21, w19
    WORD $0x1201f2b5 // and    w21, w21, #0xaaaaaaaa
    WORD $0x2b1602b5 // adds    w21, w21, w22
    WORD $0x531f7ab5 // lsl    w21, w21, #1
    WORD $0x5200f2b5 // eor    w21, w21, #0x55555555
    WORD $0x0a1302b3 // and    w19, w21, w19
    WORD $0x2a3303f5 // mvn    w21, w19
    WORD $0x1a9f37f3 // cset    w19, hs
    WORD $0x8a1402b4 // and    x20, x21, x20
    B LBB0_436
LBB0_435:
    WORD $0xaa1f03f3 // mov    x19, xzr
LBB0_436:
    CMP $0, R20
    BNE LBB0_469
    WORD $0xd10080e7 // sub    x7, x7, #32
    WORD $0x91008084 // add    x4, x4, #32
    WORD $0x8b0700b4 // add    x20, x5, x7
    WORD $0xf100fe9f // cmp    x20, #63
    BGT LBB0_433
    CMP $0, R19
    BNE LBB0_479
    WORD $0x8b020202 // add    x2, x16, x2
    WORD $0x8b040042 // add    x2, x2, x4
    WORD $0xaa2403e4 // mvn    x4, x4
    WORD $0x91000442 // add    x2, x2, #1
    WORD $0x8b050084 // add    x4, x4, x5
LBB0_440:
    WORD $0xf100049f // cmp    x4, #1
    BGE LBB0_473
    B LBB0_405
LBB0_441:
    WORD $0xf9400405 // ldr    x5, [x0, #8]
    WORD $0xaa1f03e7 // mov    x7, xzr
    WORD $0xaa1f03e4 // mov    x4, xzr
    WORD $0xaa1f03e6 // mov    x6, xzr
    WORD $0xaa1f03e2 // mov    x2, xzr
    WORD $0x8b120210 // add    x16, x16, x18
    WORD $0xcb1200a5 // sub    x5, x5, x18
    WORD $0xf10100b2 // subs    x18, x5, #64
    BGE LBB0_458
LBB0_442:
    WORD $0xf10000bf // cmp    x5, #0
    BLE LBB0_478
    WORD $0x92402e13 // and    x19, x16, #0xfff
    WORD $0xad0063f8 // stp    q24, q24, [sp]
    WORD $0xf13f067f // cmp    x19, #4033
    WORD $0xad0163f8 // stp    q24, q24, [sp, #32]
    BLO LBB0_458
    WORD $0xf10080b4 // subs    x20, x5, #32
    BLO LBB0_446
    WORD $0xa9415616 // ldp    x22, x21, [x16, #16]
    WORD $0xaa0903f3 // mov    x19, x9
    WORD $0x3cc2061c // ldr    q28, [x16], #32
    WORD $0x3d8003fc // str    q28, [sp]
    WORD $0xa90157f6 // stp    x22, x21, [sp, #16]
    B LBB0_447
LBB0_446:
    WORD $0x910003f3 // mov    x19, sp
    WORD $0xaa0503f4 // mov    x20, x5
LBB0_447:
    WORD $0xf1004295 // subs    x21, x20, #16
    BLO LBB0_453
    WORD $0xa8c15216 // ldp    x22, x20, [x16], #16
    WORD $0xa8815276 // stp    x22, x20, [x19], #16
    WORD $0xaa1503f4 // mov    x20, x21
    WORD $0xf10022b5 // subs    x21, x21, #8
    BHS LBB0_454
LBB0_449:
    WORD $0xf1001295 // subs    x21, x20, #4
    BLO LBB0_455
LBB0_450:
    WORD $0xb8404616 // ldr    w22, [x16], #4
    WORD $0xaa1503f4 // mov    x20, x21
    WORD $0xb8004676 // str    w22, [x19], #4
    WORD $0xf1000ab5 // subs    x21, x21, #2
    BHS LBB0_456
LBB0_451:
    CMP $0, R20
    BEQ LBB0_457
LBB0_452:
    WORD $0x39400214 // ldrb    w20, [x16]
    WORD $0x910003f0 // mov    x16, sp
    WORD $0x39000274 // strb    w20, [x19]
    B LBB0_458
LBB0_453:
    WORD $0xf1002295 // subs    x21, x20, #8
    BLO LBB0_449
LBB0_454:
    WORD $0xf8408616 // ldr    x22, [x16], #8
    WORD $0xaa1503f4 // mov    x20, x21
    WORD $0xf8008676 // str    x22, [x19], #8
    WORD $0xf10012b5 // subs    x21, x21, #4
    BHS LBB0_450
LBB0_455:
    WORD $0xf1000a95 // subs    x21, x20, #2
    BLO LBB0_451
LBB0_456:
    WORD $0x78402616 // ldrh    w22, [x16], #2
    WORD $0xaa1503f4 // mov    x20, x21
    WORD $0x78002676 // strh    w22, [x19], #2
    CMP $0, R21
    BNE LBB0_452
LBB0_457:
    WORD $0x910003f0 // mov    x16, sp
LBB0_458:
    WORD $0xad417e1e // ldp    q30, q31, [x16, #32]
    WORD $0x6e238fca // cmeq    v10.16b, v30.16b, v3.16b
    WORD $0xad40761c // ldp    q28, q29, [x16]
    WORD $0x6e238feb // cmeq    v11.16b, v31.16b, v3.16b
    WORD $0x4e201d4a // and    v10.16b, v10.16b, v0.16b
    WORD $0x4e02014a // tbl    v10.16b, { v10.16b }, v2.16b
    WORD $0x6e238f88 // cmeq    v8.16b, v28.16b, v3.16b
    WORD $0x4e201d6b // and    v11.16b, v11.16b, v0.16b
    WORD $0x6e238fa9 // cmeq    v9.16b, v29.16b, v3.16b
    WORD $0x4e201d08 // and    v8.16b, v8.16b, v0.16b
    WORD $0x4e201d29 // and    v9.16b, v9.16b, v0.16b
    WORD $0x4e02016b // tbl    v11.16b, { v11.16b }, v2.16b
    WORD $0x4e020108 // tbl    v8.16b, { v8.16b }, v2.16b
    WORD $0x4e020129 // tbl    v9.16b, { v9.16b }, v2.16b
    WORD $0x4e71b94a // addv    h10, v10.8h
    WORD $0x4e71b96b // addv    h11, v11.8h
    WORD $0x4e71b908 // addv    h8, v8.8h
    WORD $0x4e71b929 // addv    h9, v9.8h
    WORD $0x1e260153 // fmov    w19, s10
    WORD $0x1e260174 // fmov    w20, s11
    WORD $0x1e260115 // fmov    w21, s8
    WORD $0x1e260136 // fmov    w22, s9
    WORD $0xd3607e73 // lsl    x19, x19, #32
    WORD $0xaa14c273 // orr    x19, x19, x20, lsl #48
    WORD $0x53103ed4 // lsl    w20, w22, #16
    WORD $0xaa150273 // orr    x19, x19, x21
    WORD $0xaa140273 // orr    x19, x19, x20
    WORD $0xaa040274 // orr    x20, x19, x4
    CMP $0, R20
    BNE LBB0_460
    WORD $0xaa1f03e4 // mov    x4, xzr
    WORD $0x92800013 // mov    x19, #-1
    B LBB0_461
LBB0_460:
    WORD $0x8a240274 // bic    x20, x19, x4
    WORD $0xaa140484 // orr    x4, x4, x20, lsl #1
    WORD $0x8a240273 // bic    x19, x19, x4
    WORD $0x9201f273 // and    x19, x19, #0xaaaaaaaaaaaaaaaa
    WORD $0xab140273 // adds    x19, x19, x20
    WORD $0xd37ffa73 // lsl    x19, x19, #1
    WORD $0xd200f273 // eor    x19, x19, #0x5555555555555555
    WORD $0x8a040273 // and    x19, x19, x4
    WORD $0x1a9f37e4 // cset    w4, hs
    WORD $0xaa3303f3 // mvn    x19, x19
LBB0_461:
    WORD $0x6e218fff // cmeq    v31.16b, v31.16b, v1.16b
    WORD $0x6e218fde // cmeq    v30.16b, v30.16b, v1.16b
    WORD $0x4e201fff // and    v31.16b, v31.16b, v0.16b
    WORD $0x4e0203ff // tbl    v31.16b, { v31.16b }, v2.16b
    WORD $0x4e201fde // and    v30.16b, v30.16b, v0.16b
    WORD $0x6e218f88 // cmeq    v8.16b, v28.16b, v1.16b
    WORD $0x4e0203de // tbl    v30.16b, { v30.16b }, v2.16b
    WORD $0x6e218fa9 // cmeq    v9.16b, v29.16b, v1.16b
    WORD $0x4e201d08 // and    v8.16b, v8.16b, v0.16b
    WORD $0x4e201d29 // and    v9.16b, v9.16b, v0.16b
    WORD $0x4e71bbff // addv    h31, v31.8h
    WORD $0x4e020108 // tbl    v8.16b, { v8.16b }, v2.16b
    WORD $0x4e020129 // tbl    v9.16b, { v9.16b }, v2.16b
    WORD $0x4e71bbde // addv    h30, v30.8h
    WORD $0x1e2603f4 // fmov    w20, s31
    WORD $0x4e71b908 // addv    h8, v8.8h
    WORD $0x4e71b93f // addv    h31, v9.8h
    WORD $0x1e2603d5 // fmov    w21, s30
    WORD $0xd3503e94 // lsl    x20, x20, #48
    WORD $0x1e260116 // fmov    w22, s8
    WORD $0xaa158294 // orr    x20, x20, x21, lsl #32
    WORD $0x1e2603f5 // fmov    w21, s31
    WORD $0xaa160294 // orr    x20, x20, x22
    WORD $0x53103eb5 // lsl    w21, w21, #16
    WORD $0xaa150294 // orr    x20, x20, x21
    WORD $0x8a130293 // and    x19, x20, x19
    WORD $0x9202e274 // and    x20, x19, #0x4444444444444444
    WORD $0x4e080e7e // dup    v30.2d, x19
    WORD $0x9201e273 // and    x19, x19, #0x8888888888888888
    WORD $0x4e080e9f // dup    v31.2d, x20
    WORD $0x0420bfe9 // movprfx    z9, z31
    WORD $0x04d000e9 // mul    z9.d, p0/m, z9.d, z7.d
    WORD $0x4e271fde // and    v30.16b, v30.16b, v7.16b
    WORD $0x0420bfc8 // movprfx    z8, z30
    WORD $0x04d00288 // mul    z8.d, p0/m, z8.d, z20.d
    WORD $0x6e291d08 // eor    v8.16b, v8.16b, v9.16b
    WORD $0x04d0027f // mul    z31.d, p0/m, z31.d, z19.d
    WORD $0x4e080e69 // dup    v9.2d, x19
    WORD $0x0420bd2c // movprfx    z12, z9
    WORD $0x04d002cc // mul    z12.d, p0/m, z12.d, z22.d
    WORD $0x4e0807ca // dup    v10.2d, v30.d[0]
    WORD $0x6e1e43cb // ext    v11.16b, v30.16b, v30.16b, #8
    WORD $0x4e1807de // dup    v30.2d, v30.d[1]
    WORD $0x04d002a9 // mul    z9.d, p0/m, z9.d, z21.d
    WORD $0x04d0022a // mul    z10.d, p0/m, z10.d, z17.d
    WORD $0x04d0025e // mul    z30.d, p0/m, z30.d, z18.d
    WORD $0x6e2c1fff // eor    v31.16b, v31.16b, v12.16b
    WORD $0x6e291d08 // eor    v8.16b, v8.16b, v9.16b
    WORD $0x0420bd69 // movprfx    z9, z11
    WORD $0x04d00209 // mul    z9.d, p0/m, z9.d, z16.d
    WORD $0x6e3e1d5e // eor    v30.16b, v10.16b, v30.16b
    WORD $0x6e3f1fde // eor    v30.16b, v30.16b, v31.16b
    WORD $0x6e281d3f // eor    v31.16b, v9.16b, v8.16b
    WORD $0x4e3b1fff // and    v31.16b, v31.16b, v27.16b
    WORD $0x4e311fde // and    v30.16b, v30.16b, v17.16b
    WORD $0x4ebf1fde // orr    v30.16b, v30.16b, v31.16b
    WORD $0x6e1e43df // ext    v31.16b, v30.16b, v30.16b, #8
    WORD $0x6e378f88 // cmeq    v8.16b, v28.16b, v23.16b
    WORD $0x6e268f9c // cmeq    v28.16b, v28.16b, v6.16b
    WORD $0x4e201d08 // and    v8.16b, v8.16b, v0.16b
    WORD $0x0ebf1fde // orr    v30.8b, v30.8b, v31.8b
    WORD $0x6e378fbf // cmeq    v31.16b, v29.16b, v23.16b
    WORD $0x9e6603d3 // fmov    x19, d30
    WORD $0x6e268fbd // cmeq    v29.16b, v29.16b, v6.16b
    WORD $0x4e201ffe // and    v30.16b, v31.16b, v0.16b
    WORD $0x4e201fbd // and    v29.16b, v29.16b, v0.16b
    WORD $0xca070267 // eor    x7, x19, x7
    WORD $0x4e201f9c // and    v28.16b, v28.16b, v0.16b
    WORD $0xf10080ff // cmp    x7, #32
