// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package neon

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __lspace_entry__() uintptr

var (
    _subr__lspace uintptr = __lspace_entry__() + 16
)

const (
    _stack__lspace = 0
)

var (
    _ = _subr__lspace
)

const (
    _ = _stack__lspace
)
