// +build !noasm !appengine
// Code generated by asm2asm_tool, DO NOT EDIT.

package neon

import (
    `github.com/bytedance/sonic/loader`
)

const (
    _entry__skip_one_fast = 0
)

const (
    _stack__skip_one_fast = 208
)

const (
    _size__skip_one_fast = 3572
)

var (
    _pcsp__skip_one_fast = [][2]uint32{
        {0x1, 0},
        {0xd40, 208},
        {0xd44, 0},
        {0xdf4, 208},
    }
)

var _cfunc_skip_one_fast = []loader.CFunc{
    {"_skip_one_fast_entry", 0, _entry__skip_one_fast, 0, nil},
    {"_skip_one_fast", _entry__skip_one_fast, _size__skip_one_fast, _stack__skip_one_fast, _pcsp__skip_one_fast},
}
