// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__unquote_entry__(SB), NOSPLIT, $112
	NO_LOCAL_POINTERS
	WORD $0x10000000  // adr x0, . $0(%rip)
	WORD $0x910203ff  // add sp, sp, #128
	WORD $0xd65f03c0  // ret
	WORD $0x00000000  // .p2align 4, 0x00
lCPI0_0:
	WORD $0x08040201
	WORD $0x80402010
	WORD $0x08040201
	WORD $0x80402010
	// // .byte 1
// .byte 2
// .byte 4
// .byte 8
// .byte 16
// .byte 32
// .byte 64
// .byte 128
// .byte 1
// .byte 2
// .byte 4
// .byte 8
// .byte 16
// .byte 32
// .byte 64
// .byte 128

lCPI0_1:
	WORD $0x09010800
	WORD $0x0b030a02
	WORD $0x0d050c04
	WORD $0x0f070e06
	// // .byte 0
// .byte 8
// .byte 1
// .byte 9
// .byte 2
// .byte 10
// .byte 3
// .byte 11
// .byte 4
// .byte 12
// .byte 5
// .byte 13
// .byte 6
// .byte 14
// .byte 7
// .byte 15

_unquote:
	MOVD.W R30, -128(RSP)	// 	WORD $0xf8180ffe  // str	x30, [sp, #-128]!
	WORD $0xa9026ffc  // stp	x28, x27, [sp, #32]
	WORD $0xa90367fa  // stp	x26, x25, [sp, #48]
	WORD $0xa9045ff8  // stp	x24, x23, [sp, #64]
	WORD $0xa90557f6  // stp	x22, x21, [sp, #80]
	WORD $0xa9064ff4  // stp	x20, x19, [sp, #96]
	WORD $0xa9077bfd  // stp	x29, x30, [sp, #112]
	WORD $0xb4002161  // cbz	x1, LBB0_62 $1068(%rip)
	WORD $0x3203cbe9  // mov	w9, #-522133280
	WORD $0x5299fa0a  // mov	w10, #53200
	WORD $0x72b9f9ea  // movk	w10, #53199, lsl #16
	WORD $0x3202c7eb  // mov	w11, #-1061109568
	WORD $0x3201c3ec  // mov	w12, #-2139062144
	WORD $0x3200dbed  // mov	w13, #2139062143
	WORD $0x5288c8ce  // mov	w14, #17990
	WORD $0x72a8c8ce  // movk	w14, #17990, lsl #16
	WORD $0x5287272f  // mov	w15, #14649
	WORD $0x72a7272f  // movk	w15, #14649, lsl #16
	WORD $0x52832330  // mov	w16, #6425
	WORD $0x72a32330  // movk	w16, #6425, lsl #16
	WORD $0x3200cff1  // mov	w17, #252645135
	WORD $0x3200c3e6  // mov	w6, #16843009
	WORD $0x92400085  // and	x5, x4, #0x1
	WORD $0x528017b4  // mov	w20, #189
	WORD $0x52848015  // mov	w21, #9216
	WORD $0x72bf9415  // movk	w21, #64672, lsl #16
	WORD $0x4f02e780  // movi.16b	v0, #92
Lloh0:
	WORD $0x10fffba8  // adr	x8, lCPI0_0 $-140(%rip)
Lloh1:
	WORD $0x3dc00101  // ldr	q1, [x8, lCPI0_0@PAGEOFF] $0(%rip)
Lloh2:
	WORD $0x10fffbe8  // adr	x8, lCPI0_1 $-132(%rip)
Lloh3:
	WORD $0x3dc00102  // ldr	q2, [x8, lCPI0_1@PAGEOFF] $0(%rip)
	WORD $0xaa0003e8  // mov	x8, x0
	WORD $0xaa0103e7  // mov	x7, x1
	WORD $0xaa0203f6  // mov	x22, x2
Lloh4:
	WORD $0x100032d7  // adr	x23, __UnquoteTab $1624(%rip)
Lloh5:
	WORD $0x910002f7  // add	x23, x23, __UnquoteTab@PAGEOFF $0(%rip)
LBB0_2:
	WORD $0x39400118  // ldrb	w24, [x8]
	WORD $0x7101731f  // cmp	w24, #92
	WORD $0x54000061  // b.ne	LBB0_4 $12(%rip)
	WORD $0xd2800018  // mov	x24, #0
	WORD $0x14000027  // b	LBB0_15 $156(%rip)
LBB0_4:
	WORD $0xaa0703f9  // mov	x25, x7
	WORD $0xaa1603fb  // mov	x27, x22
	WORD $0xaa0803fa  // mov	x26, x8
	WORD $0xf10040ff  // cmp	x7, #16
	WORD $0x5400024b  // b.lt	LBB0_9 $72(%rip)
	WORD $0xd2800018  // mov	x24, #0
	WORD $0xaa0703fa  // mov	x26, x7
LBB0_6:
	WORD $0x3cf86903  // ldr	q3, [x8, x24]
	WORD $0x6e208c64  // cmeq.16b	v4, v3, v0
	WORD $0x3cb86ac3  // str	q3, [x22, x24]
	WORD $0x4e211c83  // and.16b	v3, v4, v1
	WORD $0x4e020063  // tbl.16b	v3, { v3 }, v2
	WORD $0x4e71b863  // addv.8h	h3, v3
	WORD $0x1e260079  // fmov	w25, s3
	WORD $0x35000279  // cbnz	w25, LBB0_13 $76(%rip)
	WORD $0xd1004359  // sub	x25, x26, #16
	WORD $0x91004318  // add	x24, x24, #16
	WORD $0xf1007f5f  // cmp	x26, #31
	WORD $0xaa1903fa  // mov	x26, x25
	WORD $0x54fffe88  // b.hi	LBB0_6 $-48(%rip)
	WORD $0x8b18011a  // add	x26, x8, x24
	WORD $0x8b1802db  // add	x27, x22, x24
LBB0_9:
	WORD $0xb4001ab9  // cbz	x25, LBB0_63 $852(%rip)
	WORD $0xcb080358  // sub	x24, x26, x8
LBB0_11:
	WORD $0x3940035c  // ldrb	w28, [x26]
	WORD $0x7101739f  // cmp	w28, #92
	WORD $0x54000140  // b.eq	LBB0_14 $40(%rip)
	WORD $0x9100075a  // add	x26, x26, #1
	WORD $0x3800177c  // strb	w28, [x27], #1
	WORD $0x91000718  // add	x24, x24, #1
	WORD $0xd1000739  // sub	x25, x25, #1
	WORD $0xb5ffff39  // cbnz	x25, LBB0_11 $-28(%rip)
	WORD $0x140000cb  // b	LBB0_63 $812(%rip)
LBB0_13:
	WORD $0x5ac00339  // rbit	w25, w25
	WORD $0x5ac01339  // clz	w25, w25
	WORD $0x8b180338  // add	x24, x25, x24
LBB0_14:
	WORD $0xb100071f  // cmn	x24, #1
	WORD $0x540018c0  // b.eq	LBB0_63 $792(%rip)
LBB0_15:
	WORD $0x91000b19  // add	x25, x24, #2
	WORD $0xeb1900e7  // subs	x7, x7, x25
	WORD $0x54002c84  // b.mi	LBB0_97 $1424(%rip)
	WORD $0x8b190108  // add	x8, x8, x25
	WORD $0xb5000145  // cbnz	x5, LBB0_20 $40(%rip)
	WORD $0x8b1802da  // add	x26, x22, x24
	WORD $0x385ff119  // ldurb	w25, [x8, #-1]
	WORD $0x38796af9  // ldrb	w25, [x23, x25]
	WORD $0x7103ff3f  // cmp	w25, #255
	WORD $0x540003a0  // b.eq	LBB0_28 $116(%rip)
LBB0_18:
	WORD $0x34002139  // cbz	w25, LBB0_79 $1060(%rip)
	WORD $0x38001759  // strb	w25, [x26], #1
	WORD $0xaa1a03f6  // mov	x22, x26
	WORD $0x14000092  // b	LBB0_54 $584(%rip)
LBB0_20:
	WORD $0x34002b07  // cbz	w7, LBB0_97 $1376(%rip)
	WORD $0x385ff119  // ldurb	w25, [x8, #-1]
	WORD $0x7101733f  // cmp	w25, #92
	WORD $0x54002801  // b.ne	LBB0_90 $1280(%rip)
	WORD $0x39400119  // ldrb	w25, [x8]
	WORD $0x7101733f  // cmp	w25, #92
	WORD $0x54000161  // b.ne	LBB0_27 $44(%rip)
	WORD $0x710004ff  // cmp	w7, #1
	WORD $0x54002a0d  // b.le	LBB0_97 $1344(%rip)
	WORD $0xaa0803f9  // mov	x25, x8
	WORD $0x38401f3a  // ldrb	w26, [x25, #1]!
	WORD $0x71008b5f  // cmp	w26, #34
	WORD $0x54000060  // b.eq	LBB0_26 $12(%rip)
	WORD $0x7101735f  // cmp	w26, #92
	WORD $0x54002701  // b.ne	LBB0_91 $1248(%rip)
LBB0_26:
	WORD $0xd10004e7  // sub	x7, x7, #1
	WORD $0xaa1903e8  // mov	x8, x25
LBB0_27:
	WORD $0x91000508  // add	x8, x8, #1
	WORD $0xd10004e7  // sub	x7, x7, #1
	WORD $0x8b1802da  // add	x26, x22, x24
	WORD $0x385ff119  // ldurb	w25, [x8, #-1]
	WORD $0x38796af9  // ldrb	w25, [x23, x25]
	WORD $0x7103ff3f  // cmp	w25, #255
	WORD $0x54fffca1  // b.ne	LBB0_18 $-108(%rip)
LBB0_28:
	WORD $0xf1000cff  // cmp	x7, #3
	WORD $0x540027e9  // b.ls	LBB0_97 $1276(%rip)
	WORD $0xb9400119  // ldr	w25, [x8]
	WORD $0x0a39019b  // bic	w27, w12, w25
	WORD $0x0b0a033c  // add	w28, w25, w10
	WORD $0x0a1c037c  // and	w28, w27, w28
	WORD $0x7100039f  // cmp	w28, #0
	WORD $0x0b10033c  // add	w28, w25, w16
	WORD $0x2a19039c  // orr	w28, w28, w25
	WORD $0x0a0c039c  // and	w28, w28, w12
	WORD $0x7a400b80  // ccmp	w28, #0, #0, eq
	WORD $0x540013c1  // b.ne	LBB0_65 $632(%rip)
	WORD $0x0a0d033c  // and	w28, w25, w13
	WORD $0x0b0e039e  // add	w30, w28, w14
	WORD $0x4b1c0173  // sub	w19, w11, w28
	WORD $0x0a130373  // and	w19, w27, w19
	WORD $0x6a1e027f  // tst	w19, w30
	WORD $0x54001301  // b.ne	LBB0_65 $608(%rip)
	WORD $0x0b0f0393  // add	w19, w28, w15
	WORD $0x4b1c013c  // sub	w28, w9, w28
	WORD $0x0a1c037b  // and	w27, w27, w28
	WORD $0x6a13037f  // tst	w27, w19
	WORD $0x54001261  // b.ne	LBB0_65 $588(%rip)
	WORD $0x5ac00b33  // rev	w19, w25
	WORD $0x0a7310d9  // bic	w25, w6, w19, lsr #4
	WORD $0x0b190f39  // add	w25, w25, w25, lsl #3
	WORD $0x0a110273  // and	w19, w19, w17
	WORD $0x0b130333  // add	w19, w25, w19
	WORD $0x2a531273  // orr	w19, w19, w19, lsr #4
	WORD $0x53087e79  // lsr	w25, w19, #8
	WORD $0x12181f39  // and	w25, w25, #0xff00
	WORD $0x33001e79  // bfxil	w25, w19, #0, #8
	WORD $0x91001108  // add	x8, x8, #4
	WORD $0xd10010e7  // sub	x7, x7, #4
	WORD $0x7102033f  // cmp	w25, #128
	WORD $0x54000b03  // b.lo	LBB0_55 $352(%rip)
	WORD $0x8b1802d3  // add	x19, x22, x24
	WORD $0x91000a76  // add	x22, x19, #2
LBB0_34:
	WORD $0x711fff3f  // cmp	w25, #2047
	WORD $0x54000b09  // b.ls	LBB0_57 $352(%rip)
	WORD $0x51403b33  // sub	w19, w25, #14, lsl #12
	WORD $0x3120067f  // cmn	w19, #2049
	WORD $0x540008c9  // b.ls	LBB0_53 $280(%rip)
	WORD $0xb50006c5  // cbnz	x5, LBB0_48 $216(%rip)
	WORD $0xaa0703f8  // mov	x24, x7
	WORD $0xf1001b07  // subs	x7, x24, #6
	WORD $0x5400078b  // b.lt	LBB0_51 $240(%rip)
LBB0_38:
	WORD $0x530a7f33  // lsr	w19, w25, #10
	WORD $0x7100da7f  // cmp	w19, #54
	WORD $0x54000728  // b.hi	LBB0_51 $228(%rip)
	WORD $0x39400113  // ldrb	w19, [x8]
	WORD $0x7101727f  // cmp	w19, #92
	WORD $0x540006c1  // b.ne	LBB0_51 $216(%rip)
	WORD $0x39400513  // ldrb	w19, [x8, #1]
	WORD $0x7101d67f  // cmp	w19, #117
	WORD $0x54000661  // b.ne	LBB0_51 $204(%rip)
	WORD $0xb8402118  // ldur	w24, [x8, #2]
	WORD $0x0b0a0313  // add	w19, w24, w10
	WORD $0x0a38019a  // bic	w26, w12, w24
	WORD $0x6a13035f  // tst	w26, w19
	WORD $0x540016c1  // b.ne	LBB0_80 $728(%rip)
	WORD $0x0b100313  // add	w19, w24, w16
	WORD $0x2a180273  // orr	w19, w19, w24
	WORD $0x6a0c027f  // tst	w19, w12
	WORD $0x54001641  // b.ne	LBB0_80 $712(%rip)
	WORD $0x0a0d031b  // and	w27, w24, w13
	WORD $0x0b0e0373  // add	w19, w27, w14
	WORD $0x4b1b017c  // sub	w28, w11, w27
	WORD $0x0a1c035c  // and	w28, w26, w28
	WORD $0x6a13039f  // tst	w28, w19
	WORD $0x54001581  // b.ne	LBB0_80 $688(%rip)
	WORD $0x0b0f0373  // add	w19, w27, w15
	WORD $0x4b1b013b  // sub	w27, w9, w27
	WORD $0x0a1b035a  // and	w26, w26, w27
	WORD $0x6a13035f  // tst	w26, w19
	WORD $0x540014e1  // b.ne	LBB0_80 $668(%rip)
	WORD $0x5ac00b13  // rev	w19, w24
	WORD $0x0a7310d8  // bic	w24, w6, w19, lsr #4
	WORD $0x0b180f18  // add	w24, w24, w24, lsl #3
	WORD $0x0a110273  // and	w19, w19, w17
	WORD $0x0b130313  // add	w19, w24, w19
	WORD $0x2a531273  // orr	w19, w19, w19, lsr #4
	WORD $0x53087e78  // lsr	w24, w19, #8
	WORD $0x12181f18  // and	w24, w24, #0xff00
	WORD $0x33001e78  // bfxil	w24, w19, #0, #8
	WORD $0x91001908  // add	x8, x8, #6
	WORD $0x51403b13  // sub	w19, w24, #14, lsl #12
	WORD $0x3110067f  // cmn	w19, #1025
	WORD $0x540005c8  // b.hi	LBB0_58 $184(%rip)
	WORD $0x36081b04  // tbz	w4, #1, LBB0_92 $864(%rip)
	WORD $0x5297fdf3  // mov	w19, #49135
	WORD $0x781fe2d3  // sturh	w19, [x22, #-2]
	WORD $0x380036d4  // strb	w20, [x22], #3
	WORD $0xaa1803f9  // mov	x25, x24
	WORD $0x7102031f  // cmp	w24, #128
	WORD $0x54fff8e2  // b.hs	LBB0_34 $-228(%rip)
	WORD $0x14000036  // b	LBB0_59 $216(%rip)
LBB0_48:
	WORD $0xf10000ff  // cmp	x7, #0
	WORD $0x54001aed  // b.le	LBB0_95 $860(%rip)
	WORD $0x39400113  // ldrb	w19, [x8]
	WORD $0x7101727f  // cmp	w19, #92
	WORD $0x54000661  // b.ne	LBB0_60 $204(%rip)
	WORD $0xd10004f8  // sub	x24, x7, #1
	WORD $0x91000508  // add	x8, x8, #1
	WORD $0xf1001b07  // subs	x7, x24, #6
	WORD $0x54fff8ca  // b.ge	LBB0_38 $-232(%rip)
LBB0_51:
	WORD $0x36081984  // tbz	w4, #1, LBB0_94 $816(%rip)
	WORD $0x5297fde7  // mov	w7, #49135
	WORD $0x781fe2c7  // sturh	w7, [x22, #-2]
	WORD $0x380016d4  // strb	w20, [x22], #1
	WORD $0xaa1803e7  // mov	x7, x24
	WORD $0x1400000a  // b	LBB0_54 $40(%rip)
LBB0_53:
	WORD $0x530c7f33  // lsr	w19, w25, #12
	WORD $0x321b0a73  // orr	w19, w19, #0xe0
	WORD $0x381fe2d3  // sturb	w19, [x22, #-2]
	WORD $0x52801013  // mov	w19, #128
	WORD $0x33062f33  // bfxil	w19, w25, #6, #6
	WORD $0x381ff2d3  // sturb	w19, [x22, #-1]
	WORD $0x52801013  // mov	w19, #128
	WORD $0x33001733  // bfxil	w19, w25, #0, #6
	WORD $0x380016d3  // strb	w19, [x22], #1
LBB0_54:
	WORD $0xb5ffe6c7  // cbnz	x7, LBB0_2 $-808(%rip)
	WORD $0x14000025  // b	LBB0_63 $148(%rip)
LBB0_55:
	WORD $0xaa1903f8  // mov	x24, x25
LBB0_56:
	WORD $0x38001758  // strb	w24, [x26], #1
	WORD $0xaa1a03f6  // mov	x22, x26
	WORD $0x17fffffb  // b	LBB0_54 $-20(%rip)
LBB0_57:
	WORD $0x53067f33  // lsr	w19, w25, #6
	WORD $0x321a0673  // orr	w19, w19, #0xc0
	WORD $0x381fe2d3  // sturb	w19, [x22, #-2]
	WORD $0x52801013  // mov	w19, #128
	WORD $0x33001733  // bfxil	w19, w25, #0, #6
	WORD $0x381ff2d3  // sturb	w19, [x22, #-1]
	WORD $0x17fffff4  // b	LBB0_54 $-48(%rip)
LBB0_58:
	WORD $0x0b192b13  // add	w19, w24, w25, lsl #10
	WORD $0x0b150278  // add	w24, w19, w21
	WORD $0x53127f19  // lsr	w25, w24, #18
	WORD $0x321c0f39  // orr	w25, w25, #0xf0
	WORD $0x381fe2d9  // sturb	w25, [x22, #-2]
	WORD $0x52801019  // mov	w25, #128
	WORD $0x330c4719  // bfxil	w25, w24, #12, #6
	WORD $0x381ff2d9  // sturb	w25, [x22, #-1]
	WORD $0x52801019  // mov	w25, #128
	WORD $0x33062f19  // bfxil	w25, w24, #6, #6
	WORD $0x390002d9  // strb	w25, [x22]
	WORD $0x52801018  // mov	w24, #128
	WORD $0x33001678  // bfxil	w24, w19, #0, #6
	WORD $0x390006d8  // strb	w24, [x22, #1]
	WORD $0x91000ad6  // add	x22, x22, #2
	WORD $0x17ffffe4  // b	LBB0_54 $-112(%rip)
LBB0_59:
	WORD $0xd1000ada  // sub	x26, x22, #2
	WORD $0x17ffffe5  // b	LBB0_56 $-108(%rip)
LBB0_60:
	WORD $0x36081324  // tbz	w4, #1, LBB0_92 $612(%rip)
	WORD $0x5297fdf3  // mov	w19, #49135
	WORD $0x781fe2d3  // sturh	w19, [x22, #-2]
	WORD $0x380016d4  // strb	w20, [x22], #1
	WORD $0x17ffffdd  // b	LBB0_54 $-140(%rip)
LBB0_62:
	WORD $0xd2800007  // mov	x7, #0
	WORD $0xaa0203f6  // mov	x22, x2
LBB0_63:
	WORD $0x8b0702c8  // add	x8, x22, x7
	WORD $0xcb020100  // sub	x0, x8, x2
LBB0_64:
	WORD $0xa9477bfd  // ldp	x29, x30, [sp, #112]
	WORD $0xa9464ff4  // ldp	x20, x19, [sp, #96]
	WORD $0xa94557f6  // ldp	x22, x21, [sp, #80]
	WORD $0xa9445ff8  // ldp	x24, x23, [sp, #64]
	WORD $0xa94367fa  // ldp	x26, x25, [sp, #48]
	WORD $0xa9426ffc  // ldp	x28, x27, [sp, #32]
	WORD $0x910203ff  // add	sp, sp, #128
	WORD $0xd65f03c0  // ret
LBB0_65:
	WORD $0xcb000109  // sub	x9, x8, x0
	WORD $0xf9000069  // str	x9, [x3]
	WORD $0x3940010a  // ldrb	w10, [x8]
	WORD $0x5100e94b  // sub	w11, w10, #58
	WORD $0x12001d6b  // and	w11, w11, #0xff
	WORD $0x7103d57f  // cmp	w11, #245
	WORD $0x54000148  // b.hi	LBB0_68 $40(%rip)
	WORD $0x12001d4a  // and	w10, w10, #0xff
	WORD $0x92800020  // mov	x0, #-2
	WORD $0x5101054a  // sub	w10, w10, #65
	WORD $0x7100955f  // cmp	w10, #37
	WORD $0x54fffda8  // b.hi	LBB0_64 $-76(%rip)
	WORD $0x5280002b  // mov	w11, #1
	WORD $0x9aca216a  // lsl	x10, x11, x10
	WORD $0xf200155f  // tst	x10, #0x3f0000003f
	WORD $0x54fffd20  // b.eq	LBB0_64 $-92(%rip)
LBB0_68:
	WORD $0x9100052a  // add	x10, x9, #1
	WORD $0xf900006a  // str	x10, [x3]
	WORD $0x3940050a  // ldrb	w10, [x8, #1]
	WORD $0x5100e94b  // sub	w11, w10, #58
	WORD $0x12001d6b  // and	w11, w11, #0xff
	WORD $0x7103d57f  // cmp	w11, #245
	WORD $0x54000148  // b.hi	LBB0_71 $40(%rip)
	WORD $0x12001d4a  // and	w10, w10, #0xff
	WORD $0x92800020  // mov	x0, #-2
	WORD $0x5101054a  // sub	w10, w10, #65
	WORD $0x7100955f  // cmp	w10, #37
	WORD $0x54fffba8  // b.hi	LBB0_64 $-140(%rip)
	WORD $0x5280002b  // mov	w11, #1
	WORD $0x9aca216a  // lsl	x10, x11, x10
	WORD $0xf200155f  // tst	x10, #0x3f0000003f
	WORD $0x54fffb20  // b.eq	LBB0_64 $-156(%rip)
LBB0_71:
	WORD $0x9100092a  // add	x10, x9, #2
	WORD $0xf900006a  // str	x10, [x3]
	WORD $0x3940090a  // ldrb	w10, [x8, #2]
	WORD $0x5100e94b  // sub	w11, w10, #58
	WORD $0x12001d6b  // and	w11, w11, #0xff
	WORD $0x7103d57f  // cmp	w11, #245
	WORD $0x54000148  // b.hi	LBB0_74 $40(%rip)
	WORD $0x12001d4a  // and	w10, w10, #0xff
	WORD $0x92800020  // mov	x0, #-2
	WORD $0x5101054a  // sub	w10, w10, #65
	WORD $0x7100955f  // cmp	w10, #37
	WORD $0x54fff9a8  // b.hi	LBB0_64 $-204(%rip)
	WORD $0x5280002b  // mov	w11, #1
	WORD $0x9aca216a  // lsl	x10, x11, x10
	WORD $0xf200155f  // tst	x10, #0x3f0000003f
	WORD $0x54fff920  // b.eq	LBB0_64 $-220(%rip)
LBB0_74:
	WORD $0x91000d2a  // add	x10, x9, #3
	WORD $0xf900006a  // str	x10, [x3]
	WORD $0x39400d08  // ldrb	w8, [x8, #3]
	WORD $0x5100e90a  // sub	w10, w8, #58
	WORD $0x12001d4a  // and	w10, w10, #0xff
	WORD $0x7103d55f  // cmp	w10, #245
	WORD $0x54000148  // b.hi	LBB0_77 $40(%rip)
LBB0_75:
	WORD $0x12001d08  // and	w8, w8, #0xff
	WORD $0x92800020  // mov	x0, #-2
	WORD $0x51010508  // sub	w8, w8, #65
	WORD $0x7100951f  // cmp	w8, #37
	WORD $0x54fff7a8  // b.hi	LBB0_64 $-268(%rip)
	WORD $0x5280002a  // mov	w10, #1
	WORD $0x9ac82148  // lsl	x8, x10, x8
	WORD $0xf200151f  // tst	x8, #0x3f0000003f
	WORD $0x54fff720  // b.eq	LBB0_64 $-284(%rip)
LBB0_77:
	WORD $0x91001128  // add	x8, x9, #4
LBB0_78:
	WORD $0xf9000068  // str	x8, [x3]
	WORD $0x92800020  // mov	x0, #-2
	WORD $0x17ffffb5  // b	LBB0_64 $-300(%rip)
LBB0_79:
	WORD $0xaa2003e9  // mvn	x9, x0
	WORD $0x8b090108  // add	x8, x8, x9
	WORD $0xf9000068  // str	x8, [x3]
	WORD $0x92800040  // mov	x0, #-3
	WORD $0x17ffffb0  // b	LBB0_64 $-320(%rip)
LBB0_80:
	WORD $0xcb000109  // sub	x9, x8, x0
	WORD $0x91000929  // add	x9, x9, #2
	WORD $0xf9000069  // str	x9, [x3]
	WORD $0x3940090a  // ldrb	w10, [x8, #2]
	WORD $0x5100e94b  // sub	w11, w10, #58
	WORD $0x12001d6b  // and	w11, w11, #0xff
	WORD $0x7103d57f  // cmp	w11, #245
	WORD $0x54000148  // b.hi	LBB0_83 $40(%rip)
	WORD $0x12001d4a  // and	w10, w10, #0xff
	WORD $0x92800020  // mov	x0, #-2
	WORD $0x5101054a  // sub	w10, w10, #65
	WORD $0x7100955f  // cmp	w10, #37
	WORD $0x54fff468  // b.hi	LBB0_64 $-372(%rip)
	WORD $0x5280002b  // mov	w11, #1
	WORD $0x9aca216a  // lsl	x10, x11, x10
	WORD $0xf200155f  // tst	x10, #0x3f0000003f
	WORD $0x54fff3e0  // b.eq	LBB0_64 $-388(%rip)
LBB0_83:
	WORD $0x9100052a  // add	x10, x9, #1
	WORD $0xf900006a  // str	x10, [x3]
	WORD $0x39400d0a  // ldrb	w10, [x8, #3]
	WORD $0x5100e94b  // sub	w11, w10, #58
	WORD $0x12001d6b  // and	w11, w11, #0xff
	WORD $0x7103d57f  // cmp	w11, #245
	WORD $0x54000148  // b.hi	LBB0_86 $40(%rip)
	WORD $0x12001d4a  // and	w10, w10, #0xff
	WORD $0x92800020  // mov	x0, #-2
	WORD $0x5101054a  // sub	w10, w10, #65
	WORD $0x7100955f  // cmp	w10, #37
	WORD $0x54fff268  // b.hi	LBB0_64 $-436(%rip)
	WORD $0x5280002b  // mov	w11, #1
	WORD $0x9aca216a  // lsl	x10, x11, x10
	WORD $0xf200155f  // tst	x10, #0x3f0000003f
	WORD $0x54fff1e0  // b.eq	LBB0_64 $-452(%rip)
LBB0_86:
	WORD $0x9100092a  // add	x10, x9, #2
	WORD $0xf900006a  // str	x10, [x3]
	WORD $0x3940110a  // ldrb	w10, [x8, #4]
	WORD $0x5100e94b  // sub	w11, w10, #58
	WORD $0x12001d6b  // and	w11, w11, #0xff
	WORD $0x7103d57f  // cmp	w11, #245
	WORD $0x54000148  // b.hi	LBB0_89 $40(%rip)
	WORD $0x12001d4a  // and	w10, w10, #0xff
	WORD $0x92800020  // mov	x0, #-2
	WORD $0x5101054a  // sub	w10, w10, #65
	WORD $0x7100955f  // cmp	w10, #37
	WORD $0x54fff068  // b.hi	LBB0_64 $-500(%rip)
	WORD $0x5280002b  // mov	w11, #1
	WORD $0x9aca216a  // lsl	x10, x11, x10
	WORD $0xf200155f  // tst	x10, #0x3f0000003f
	WORD $0x54ffefe0  // b.eq	LBB0_64 $-516(%rip)
LBB0_89:
	WORD $0x91000d2a  // add	x10, x9, #3
	WORD $0xf900006a  // str	x10, [x3]
	WORD $0x39401508  // ldrb	w8, [x8, #5]
	WORD $0x5100e90a  // sub	w10, w8, #58
	WORD $0x12001d4a  // and	w10, w10, #0xff
	WORD $0x7103d55f  // cmp	w10, #245
	WORD $0x54fff6e9  // b.ls	LBB0_75 $-292(%rip)
	WORD $0x17ffffbf  // b	LBB0_77 $-260(%rip)
LBB0_90:
	WORD $0xaa2003e9  // mvn	x9, x0
	WORD $0x8b090108  // add	x8, x8, x9
	WORD $0x17ffffbd  // b	LBB0_78 $-268(%rip)
LBB0_91:
	WORD $0xcb000108  // sub	x8, x8, x0
	WORD $0x91000508  // add	x8, x8, #1
	WORD $0x17ffffba  // b	LBB0_78 $-280(%rip)
LBB0_92:
	WORD $0xcb000108  // sub	x8, x8, x0
LBB0_93:
	WORD $0xd1001108  // sub	x8, x8, #4
	WORD $0xf9000068  // str	x8, [x3]
	WORD $0x92800060  // mov	x0, #-4
	WORD $0x17ffff6c  // b	LBB0_64 $-592(%rip)
LBB0_94:
	WORD $0x8b0000a9  // add	x9, x5, x0
	WORD $0xcb090108  // sub	x8, x8, x9
	WORD $0x17fffffa  // b	LBB0_93 $-24(%rip)
LBB0_95:
	WORD $0x360800e4  // tbz	w4, #1, LBB0_97 $28(%rip)
	WORD $0xd2800007  // mov	x7, #0
	WORD $0x5297fde8  // mov	w8, #49135
	WORD $0x781fe2c8  // sturh	w8, [x22, #-2]
	WORD $0x528017a8  // mov	w8, #189
	WORD $0x380016c8  // strb	w8, [x22], #1
	WORD $0x17ffff60  // b	LBB0_63 $-640(%rip)
LBB0_97:
	WORD $0xf9000061  // str	x1, [x3]
	WORD $0x92800000  // mov	x0, #-1
	WORD $0x17ffff5f  // b	LBB0_64 $-644(%rip)
__UnquoteTab:
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00"\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00220000  // .ascii 4, '\x00\x00"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00/\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x2f000000  // .ascii 4, '\x00\x00\x00/\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\\\x00\x00\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\x00\x00\\\x00\x00\x00\x00\x00\x08\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\\\x00\x00\x00\x00\x00\x08\x00\x00\x00\x0c\x00'
	WORD $0x0000005c  // .ascii 4, '\\\x00\x00\x00\x00\x00\x08\x00\x00\x00\x0c\x00\x00\x00\x00\x00'
	WORD $0x00080000  // .ascii 4, '\x00\x00\x08\x00\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\n\x00'
	WORD $0x000c0000  // .ascii 4, '\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\r\x00'
	WORD $0x00000000  // .ascii 4, '\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\r\x00\t\xff\x00\x00'
	WORD $0x000a0000  // .ascii 4, '\x00\x00\n\x00\x00\x00\r\x00\t\xff\x00\x00'
	WORD $0x000d0000  // .ascii 4, '\x00\x00\r\x00\t\xff\x00\x00'
	WORD $0x0000ff09  // .ascii 4, '\t\xff\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00\x00\x00\x00\x00'
	WORD $0x00000000  // .space 4, '\x00\x00\x00\x00'

TEXT ·__unquote(SB), $0-48
	NO_LOCAL_POINTERS

_entry:
	MOVD 16(g), R16
	SUB $160, RSP, R17
	CMP  R16, R17
	BLS  _stack_grow

_unquote:
	MOVD sp+0(FP), R0
	MOVD nb+8(FP), R1
	MOVD dp+16(FP), R2
	MOVD ep+24(FP), R3
	MOVD flags+32(FP), R4
	CALL ·__unquote_entry__+60(SB)  // _unquote
	MOVD R0, ret+40(FP)
	RET

_stack_grow:
	MOVD R30, R3
	CALL runtime·morestack_noctxt<>(SB)
	JMP  _entry
