// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package neon

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __unquote_entry__() uintptr

var (
    _subr__unquote uintptr = 32
)

const (
    _stack__unquote = 112
)

var (
    _ = _subr__unquote
)

const (
    _ = _stack__unquote
)
