// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package neon

//go:nosplit
//go:noescape
//goland:noinspection ALL
func __validate_utf8_entry__() uintptr

var (
    _subr__validate_utf8 uintptr = __validate_utf8_entry__() + 16
)

const (
    _stack__validate_utf8 = 32
)

var (
    _ = _subr__validate_utf8
)

const (
    _ = _stack__validate_utf8
)
