//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT
#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__validate_utf8_fast_entry__(SB), NOSPLIT, $32
	NO_LOCAL_POINTERS
	WORD $0x100000a0 // adr x0, .+20
	MOVD R0, ret(FP)
	RET
	// .p2align 2, 0x00
	
DATA LCDATA1<>+0x000(SB)/8, $0xffffffffffffffff
DATA LCDATA1<>+0x008(SB)/8, $0xbfdfefffffffffff
GLOBL LCDATA1<>(SB), 8, $16


LCPI0_0:
    WORD $0xffffffff
    WORD $0xffffffff
    WORD $0xffffffff
    WORD $0xbfdfefff
validate_utf8_fast:
    WORD $0xf9400408 // ldr    x8, [x0, #8]
    CMP $0, R8
    BEQ LBB0_11
    WORD $0xf81f0ffd // str    fp, [sp, #-16]!
    WORD $0xd10183ff // sub    sp, sp, #96
    WORD $0x043f57ff // addvl    sp, sp, #-1
    WORD $0x2518e3e0 // ptrue    p0.b
    WORD $0xf9400009 // ldr    x9, [x0]
    WORD $0x2538d000 // mov    z0.b, #-128
    WORD $0x8b08012a // add    x10, x9, x8
    WORD $0xd102014c // sub    x12, x10, #128
    WORD $0xeb0c013f // cmp    x9, x12
    BHS LBB0_12
    WORD $0x2538c003 // mov    z3.b, #0
    WORD $0x2558e3e1 // ptrue    p1.h
    ADR LCPI0_0, R11
    WORD $0x6f07e7e4 // movi    v4.2d, #0xffffffffffffffff
    WORD $0x2538c085 // mov    z5.b, #4
    WORD $0x3dc00167 // ldr    q7, [x11, :lo12:.LCPI0_0]
    WORD $0x2578c006 // mov    z6.h, #0
    WORD $0x5280040d // mov    w13, #32
    WORD $0x5280080e // mov    w14, #64
    WORD $0x04633061 // mov    z1.d, z3.d
    WORD $0x04633062 // mov    z2.d, z3.d
    WORD $0x04633070 // mov    z16.d, z3.d
    ADR check_special_casestab1, R15
    WORD $0x910001ef // add    x15, x15, :lo12:check_special_cases.tab1
    WORD $0x52800c10 // mov    w16, #96
    ADR check_special_casestab2, R17
    WORD $0x91000231 // add    x17, x17, :lo12:check_special_cases.tab2
    ADR check_special_casestab3, R18_PLATFORM
    WORD $0x91000252 // add    x18, x18, :lo12:check_special_cases.tab3
    WORD $0x910003e1 // mov    x1, sp
    WORD $0xaa0903eb // mov    x11, x9
LBB0_3:
    WORD $0xa4104173 // ld1b    { z19.b }, p0/z, [x11, x16]
    WORD $0xa40d4172 // ld1b    { z18.b }, p0/z, [x11, x13]
    WORD $0x910183fd // add    fp, sp, #96
    WORD $0xa40e4171 // ld1b    { z17.b }, p0/z, [x11, x14]
    WORD $0xa400a175 // ld1b    { z21.b }, p0/z, [x11]
    WORD $0x04733276 // mov    z22.d, z19.d
    WORD $0x04723254 // mov    z20.d, z18.d
    WORD $0x04180236 // orr    z22.b, p0/m, z22.b, z17.b
    WORD $0x041802b4 // orr    z20.b, p0/m, z20.b, z21.b
    WORD $0x047632d7 // mov    z23.d, z22.d
    WORD $0x04180297 // orr    z23.b, p0/m, z23.b, z20.b
    WORD $0x240002e2 // cmphs    p2.b, p0/z, z23.b, z0.b
    WORD $0xe5801fa2 // str    p2, [fp, #7, mul vl]
    WORD $0x047f50fd // addpl    fp, sp, #7
    WORD $0xb94063a2 // ldr    w2, [fp, #96]
    CMP $0, R2
    BNE LBB0_6
    WORD $0x04703211 // mov    z17.d, z16.d
    WORD $0x04180031 // orr    z17.b, p0/m, z17.b, z1.b
    WORD $0x04713221 // mov    z1.d, z17.d
LBB0_5:
    WORD $0x9100816b // add    x11, x11, #32
    WORD $0x9101816b // add    x11, x11, #96
    WORD $0xeb0c017f // cmp    x11, x12
    BLO LBB0_3
    B LBB0_13
LBB0_6:
    WORD $0x24000282 // cmphs    p2.b, p0/z, z20.b, z0.b
    WORD $0x910183fd // add    fp, sp, #96
    WORD $0xe5801fa2 // str    p2, [fp, #7, mul vl]
    WORD $0x047f50fd // addpl    fp, sp, #7
    WORD $0xb94063a2 // ldr    w2, [fp, #96]
    CMP $0, R2
    BNE LBB0_8
    WORD $0x04623052 // mov    z18.d, z2.d
    WORD $0x04713234 // mov    z20.d, z17.d
    WORD $0x0420be37 // movprfx    z23, z17
    WORD $0x045184b7 // lsr    z23.h, p1/m, z23.h, z5.h
    WORD $0x04623058 // mov    z24.d, z2.d
    WORD $0x04713239 // mov    z25.d, z17.d
    WORD $0xa40021fa // ld1rqb    { z26.b }, p0/z, [x15]
    WORD $0x05231622 // ext    z2.b, z2.b, z17.b, #29
    WORD $0x0420be7b // movprfx    z27, z19
    WORD $0x045184bb // lsr    z27.h, p1/m, z27.h, z5.h
    WORD $0x05800477 // and    z23.h, z23.h, #0xf
    WORD $0x05231e32 // ext    z18.b, z18.b, z17.b, #31
    WORD $0x05231e74 // ext    z20.b, z20.b, z19.b, #31
    WORD $0x0420be55 // movprfx    z21, z18
    WORD $0x045184b5 // lsr    z21.h, p1/m, z21.h, z5.h
    WORD $0x0420be96 // movprfx    z22, z20
    WORD $0x045184b6 // lsr    z22.h, p1/m, z22.h, z5.h
    WORD $0x05231a38 // ext    z24.b, z24.b, z17.b, #30
    WORD $0x05800475 // and    z21.h, z21.h, #0xf
    WORD $0x05231a79 // ext    z25.b, z25.b, z19.b, #30
    WORD $0x05231671 // ext    z17.b, z17.b, z19.b, #29
    WORD $0x05800476 // and    z22.h, z22.h, #0xf
    WORD $0x2527dde2 // uqsub    z2.b, z2.b, #239
    WORD $0x0523c252 // sel    z18.b, p0, z18.b, z3.b
    WORD $0x0523c294 // sel    z20.b, p0, z20.b, z3.b
    WORD $0x2527dbf8 // uqsub    z24.b, z24.b, #223
    WORD $0x0523c2b5 // sel    z21.b, p0, z21.b, z3.b
    WORD $0x0580047b // and    z27.h, z27.h, #0xf
    WORD $0x2527dbf9 // uqsub    z25.b, z25.b, #223
    WORD $0x2527ddf1 // uqsub    z17.b, z17.b, #239
    WORD $0x0523c2d6 // sel    z22.b, p0, z22.b, z3.b
    WORD $0x0523c252 // sel    z18.b, p0, z18.b, z3.b
    WORD $0x0523c294 // sel    z20.b, p0, z20.b, z3.b
    WORD $0x04180030 // orr    z16.b, p0/m, z16.b, z1.b
    WORD $0x05800675 // and    z21.b, z21.b, #0xf
    WORD $0x04180302 // orr    z2.b, p0/m, z2.b, z24.b
    WORD $0xa4002238 // ld1rqb    { z24.b }, p0/z, [x17]
    WORD $0x05800676 // and    z22.b, z22.b, #0xf
    WORD $0x04180331 // orr    z17.b, p0/m, z17.b, z25.b
    WORD $0x05800672 // and    z18.b, z18.b, #0xf
    WORD $0x05800674 // and    z20.b, z20.b, #0xf
    WORD $0x05353355 // tbl    z21.b, { z26.b }, z21.b
    WORD $0x24200052 // cmphi    p2.b, p0/z, z2.b, #0
    WORD $0x05363342 // tbl    z2.b, { z26.b }, z22.b
    WORD $0x0523c376 // sel    z22.b, p0, z27.b, z3.b
    WORD $0x24200233 // cmphi    p3.b, p0/z, z17.b, #0
    WORD $0x0523c2f1 // sel    z17.b, p0, z23.b, z3.b
    WORD $0xa4002257 // ld1rqb    { z23.b }, p0/z, [x18]
    WORD $0xad001fe4 // stp    q4, q7, [sp]
    WORD $0x05323312 // tbl    z18.b, { z24.b }, z18.b
    WORD $0x05343314 // tbl    z20.b, { z24.b }, z20.b
    WORD $0x25024002 // and    p2.b, p0/z, p0.b, p2.b
    WORD $0x0523c2b5 // sel    z21.b, p0, z21.b, z3.b
    WORD $0x05800676 // and    z22.b, z22.b, #0xf
    WORD $0x25034003 // and    p3.b, p0/z, p0.b, p3.b
    WORD $0x0523c042 // sel    z2.b, p0, z2.b, z3.b
    WORD $0x05800671 // and    z17.b, z17.b, #0xf
    WORD $0x043232b2 // and    z18.d, z21.d, z18.d
    WORD $0x04343042 // and    z2.d, z2.d, z20.d
    WORD $0x053132f1 // tbl    z17.b, { z23.b }, z17.b
    WORD $0x053632f4 // tbl    z20.b, { z23.b }, z22.b
    WORD $0x0523c252 // sel    z18.b, p0, z18.b, z3.b
    WORD $0x05121ff5 // mov    z21.b, p2/z, #-1
    WORD $0x05131ff6 // mov    z22.b, p3/z, #-1
    WORD $0x0523c042 // sel    z2.b, p0, z2.b, z3.b
    WORD $0x04313251 // and    z17.d, z18.d, z17.d
    WORD $0x05800e15 // and    z21.b, z21.b, #0x80
    WORD $0x04343041 // and    z1.d, z2.d, z20.d
    WORD $0xa400a022 // ld1b    { z2.b }, p0/z, [x1]
    WORD $0x05800e16 // and    z22.b, z22.b, #0x80
    WORD $0x041902b1 // eor    z17.b, p0/m, z17.b, z21.b
    WORD $0x041902c1 // eor    z1.b, p0/m, z1.b, z22.b
    WORD $0x04180221 // orr    z1.b, p0/m, z1.b, z17.b
    WORD $0x0523c271 // sel    z17.b, p0, z19.b, z3.b
    WORD $0x04180201 // orr    z1.b, p0/m, z1.b, z16.b
    WORD $0x04220630 // sub    z16.b, z17.b, z2.b
    WORD $0x04733262 // mov    z2.d, z19.d
    B LBB0_5
LBB0_8:
    WORD $0x04623050 // mov    z16.d, z2.d
    WORD $0x047532b3 // mov    z19.d, z21.d
    WORD $0x0420beb8 // movprfx    z24, z21
    WORD $0x045184b8 // lsr    z24.h, p1/m, z24.h, z5.h
    WORD $0x04623059 // mov    z25.d, z2.d
    WORD $0x047532ba // mov    z26.d, z21.d
    WORD $0x0420be5d // movprfx    z29, z18
    WORD $0x045184bd // lsr    z29.h, p1/m, z29.h, z5.h
    WORD $0x052316a2 // ext    z2.b, z2.b, z21.b, #29
    WORD $0x05800478 // and    z24.h, z24.h, #0xf
    WORD $0x910183fd // add    fp, sp, #96
    WORD $0x05231eb0 // ext    z16.b, z16.b, z21.b, #31
    WORD $0x05231e53 // ext    z19.b, z19.b, z18.b, #31
    WORD $0x0420be14 // movprfx    z20, z16
    WORD $0x045184b4 // lsr    z20.h, p1/m, z20.h, z5.h
    WORD $0x0420be77 // movprfx    z23, z19
    WORD $0x045184b7 // lsr    z23.h, p1/m, z23.h, z5.h
    WORD $0x05231ab9 // ext    z25.b, z25.b, z21.b, #30
    WORD $0x05800474 // and    z20.h, z20.h, #0xf
    WORD $0x05231a5a // ext    z26.b, z26.b, z18.b, #30
    WORD $0x05231655 // ext    z21.b, z21.b, z18.b, #29
    WORD $0x05800477 // and    z23.h, z23.h, #0xf
    WORD $0x2527dde2 // uqsub    z2.b, z2.b, #239
    WORD $0x0523c21b // sel    z27.b, p0, z16.b, z3.b
    WORD $0xa40021f0 // ld1rqb    { z16.b }, p0/z, [x15]
    WORD $0x2527dbf9 // uqsub    z25.b, z25.b, #223
    WORD $0x0523c273 // sel    z19.b, p0, z19.b, z3.b
    WORD $0x0523c29c // sel    z28.b, p0, z20.b, z3.b
    WORD $0xa4002234 // ld1rqb    { z20.b }, p0/z, [x17]
    WORD $0x2527dbfa // uqsub    z26.b, z26.b, #223
    WORD $0x2527ddf5 // uqsub    z21.b, z21.b, #239
    WORD $0x0523c2f7 // sel    z23.b, p0, z23.b, z3.b
    WORD $0x0523c37b // sel    z27.b, p0, z27.b, z3.b
    WORD $0x0580047d // and    z29.h, z29.h, #0xf
    WORD $0x0580067c // and    z28.b, z28.b, #0xf
    WORD $0x0523c273 // sel    z19.b, p0, z19.b, z3.b
    WORD $0x04180322 // orr    z2.b, p0/m, z2.b, z25.b
    WORD $0x05800677 // and    z23.b, z23.b, #0xf
    WORD $0x04180355 // orr    z21.b, p0/m, z21.b, z26.b
    WORD $0x0580067b // and    z27.b, z27.b, #0xf
    WORD $0x053c3219 // tbl    z25.b, { z16.b }, z28.b
    WORD $0x05800673 // and    z19.b, z19.b, #0xf
    WORD $0x24200052 // cmphi    p2.b, p0/z, z2.b, #0
    WORD $0x05373202 // tbl    z2.b, { z16.b }, z23.b
    WORD $0x242002b3 // cmphi    p3.b, p0/z, z21.b, #0
    WORD $0xa4002255 // ld1rqb    { z21.b }, p0/z, [x18]
    WORD $0xad001fe4 // stp    q4, q7, [sp]
    WORD $0x0523c317 // sel    z23.b, p0, z24.b, z3.b
    WORD $0x0523c3b8 // sel    z24.b, p0, z29.b, z3.b
    WORD $0x053b329a // tbl    z26.b, { z20.b }, z27.b
    WORD $0x05333293 // tbl    z19.b, { z20.b }, z19.b
    WORD $0x25024002 // and    p2.b, p0/z, p0.b, p2.b
    WORD $0x0523c339 // sel    z25.b, p0, z25.b, z3.b
    WORD $0x25034003 // and    p3.b, p0/z, p0.b, p3.b
    WORD $0x0523c042 // sel    z2.b, p0, z2.b, z3.b
    WORD $0x05800677 // and    z23.b, z23.b, #0xf
    WORD $0x05800678 // and    z24.b, z24.b, #0xf
    WORD $0x043a3339 // and    z25.d, z25.d, z26.d
    WORD $0x04333042 // and    z2.d, z2.d, z19.d
    WORD $0x053732b3 // tbl    z19.b, { z21.b }, z23.b
    WORD $0x053832b7 // tbl    z23.b, { z21.b }, z24.b
    WORD $0x0523c338 // sel    z24.b, p0, z25.b, z3.b
    WORD $0x05121ff9 // mov    z25.b, p2/z, #-1
    WORD $0x05131ffa // mov    z26.b, p3/z, #-1
    WORD $0x0523c042 // sel    z2.b, p0, z2.b, z3.b
    WORD $0x240002c2 // cmphs    p2.b, p0/z, z22.b, z0.b
    WORD $0x04333318 // and    z24.d, z24.d, z19.d
    WORD $0x05800e19 // and    z25.b, z25.b, #0x80
    WORD $0x05800e1a // and    z26.b, z26.b, #0x80
    WORD $0x04373053 // and    z19.d, z2.d, z23.d
    WORD $0xe5801fa2 // str    p2, [fp, #7, mul vl]
    WORD $0x047f50fd // addpl    fp, sp, #7
    WORD $0xb94063a2 // ldr    w2, [fp, #96]
    WORD $0x04190338 // eor    z24.b, p0/m, z24.b, z25.b
    WORD $0x04190353 // eor    z19.b, p0/m, z19.b, z26.b
    WORD $0x04180313 // orr    z19.b, p0/m, z19.b, z24.b
    WORD $0x04180033 // orr    z19.b, p0/m, z19.b, z1.b
    WORD $0xa400a021 // ld1b    { z1.b }, p0/z, [x1]
    CMP $0, R2
    BEQ LBB0_10
    WORD $0x91018162 // add    x2, x11, #96
    WORD $0x04723241 // mov    z1.d, z18.d
    WORD $0x04713236 // mov    z22.d, z17.d
    WORD $0xa400a042 // ld1b    { z2.b }, p0/z, [x2]
    WORD $0x0472325a // mov    z26.d, z18.d
    WORD $0x0471323b // mov    z27.d, z17.d
    WORD $0x05231632 // ext    z18.b, z18.b, z17.b, #29
    WORD $0x0566c639 // sel    z25.h, p1, z17.h, z6.h
    WORD $0xad001fe4 // stp    q4, q7, [sp]
    WORD $0x05231e21 // ext    z1.b, z1.b, z17.b, #31
    WORD $0x05231c56 // ext    z22.b, z22.b, z2.b, #31
    WORD $0x05231a3a // ext    z26.b, z26.b, z17.b, #30
    WORD $0x0566c45c // sel    z28.h, p1, z2.h, z6.h
    WORD $0x0523185b // ext    z27.b, z27.b, z2.b, #30
    WORD $0x05231451 // ext    z17.b, z17.b, z2.b, #29
    WORD $0x2527ddf2 // uqsub    z18.b, z18.b, #239
    WORD $0x0566c437 // sel    z23.h, p1, z1.h, z6.h
    WORD $0x045184b9 // lsr    z25.h, p1/m, z25.h, z5.h
    WORD $0x0523c021 // sel    z1.b, p0, z1.b, z3.b
    WORD $0x0566c6d8 // sel    z24.h, p1, z22.h, z6.h
    WORD $0x2527dbfa // uqsub    z26.b, z26.b, #223
    WORD $0x0523c2d6 // sel    z22.b, p0, z22.b, z3.b
    WORD $0x045184bc // lsr    z28.h, p1/m, z28.h, z5.h
    WORD $0x2527dbfb // uqsub    z27.b, z27.b, #223
    WORD $0x2527ddf1 // uqsub    z17.b, z17.b, #239
    WORD $0x045184b7 // lsr    z23.h, p1/m, z23.h, z5.h
    WORD $0x0523c021 // sel    z1.b, p0, z1.b, z3.b
    WORD $0x0566c739 // sel    z25.h, p1, z25.h, z6.h
    WORD $0x045184b8 // lsr    z24.h, p1/m, z24.h, z5.h
    WORD $0x0523c2d6 // sel    z22.b, p0, z22.b, z3.b
    WORD $0x04180352 // orr    z18.b, p0/m, z18.b, z26.b
    WORD $0x0566c79a // sel    z26.h, p1, z28.h, z6.h
    WORD $0x0566c6f7 // sel    z23.h, p1, z23.h, z6.h
    WORD $0x04180371 // orr    z17.b, p0/m, z17.b, z27.b
    WORD $0x05800661 // and    z1.b, z1.b, #0xf
    WORD $0x0566c718 // sel    z24.h, p1, z24.h, z6.h
    WORD $0x05800479 // and    z25.h, z25.h, #0xf
    WORD $0x05800676 // and    z22.b, z22.b, #0xf
    WORD $0x0580047a // and    z26.h, z26.h, #0xf
    WORD $0x24200252 // cmphi    p2.b, p0/z, z18.b, #0
    WORD $0x05800477 // and    z23.h, z23.h, #0xf
    WORD $0x24200233 // cmphi    p3.b, p0/z, z17.b, #0
    WORD $0x05213281 // tbl    z1.b, { z20.b }, z1.b
    WORD $0x05800478 // and    z24.h, z24.h, #0xf
    WORD $0x0523c331 // sel    z17.b, p0, z25.b, z3.b
    WORD $0x05363294 // tbl    z20.b, { z20.b }, z22.b
    WORD $0x0523c356 // sel    z22.b, p0, z26.b, z3.b
    WORD $0x25024002 // and    p2.b, p0/z, p0.b, p2.b
    WORD $0x0523c2f7 // sel    z23.b, p0, z23.b, z3.b
    WORD $0x25034003 // and    p3.b, p0/z, p0.b, p3.b
    WORD $0x0523c318 // sel    z24.b, p0, z24.b, z3.b
    WORD $0x05800671 // and    z17.b, z17.b, #0xf
    WORD $0x05800676 // and    z22.b, z22.b, #0xf
    WORD $0x05800677 // and    z23.b, z23.b, #0xf
    WORD $0x05800678 // and    z24.b, z24.b, #0xf
    WORD $0x053132b1 // tbl    z17.b, { z21.b }, z17.b
    WORD $0x05373217 // tbl    z23.b, { z16.b }, z23.b
    WORD $0x05383210 // tbl    z16.b, { z16.b }, z24.b
    WORD $0x0523c2f2 // sel    z18.b, p0, z23.b, z3.b
    WORD $0x0523c210 // sel    z16.b, p0, z16.b, z3.b
    WORD $0x04213241 // and    z1.d, z18.d, z1.d
    WORD $0x053632b2 // tbl    z18.b, { z21.b }, z22.b
    WORD $0x05131ff5 // mov    z21.b, p3/z, #-1
    WORD $0x04343210 // and    z16.d, z16.d, z20.d
    WORD $0x05121ff4 // mov    z20.b, p2/z, #-1
    WORD $0x0523c021 // sel    z1.b, p0, z1.b, z3.b
    WORD $0x05800e15 // and    z21.b, z21.b, #0x80
    WORD $0x0523c210 // sel    z16.b, p0, z16.b, z3.b
    WORD $0x05800e14 // and    z20.b, z20.b, #0x80
    WORD $0x04313031 // and    z17.d, z1.d, z17.d
    WORD $0x04323201 // and    z1.d, z16.d, z18.d
    WORD $0xa400a030 // ld1b    { z16.b }, p0/z, [x1]
    WORD $0x04190291 // eor    z17.b, p0/m, z17.b, z20.b
    WORD $0x041902a1 // eor    z1.b, p0/m, z1.b, z21.b
    WORD $0x04180221 // orr    z1.b, p0/m, z1.b, z17.b
    WORD $0x0523c051 // sel    z17.b, p0, z2.b, z3.b
    WORD $0x04180261 // orr    z1.b, p0/m, z1.b, z19.b
    WORD $0x04300630 // sub    z16.b, z17.b, z16.b
    B LBB0_5
LBB0_10:
    WORD $0x0523c242 // sel    z2.b, p0, z18.b, z3.b
    WORD $0x04210450 // sub    z16.b, z2.b, z1.b
    WORD $0x04723242 // mov    z2.d, z18.d
    WORD $0x04703201 // mov    z1.d, z16.d
    WORD $0x04180261 // orr    z1.b, p0/m, z1.b, z19.b
    B LBB0_5
LBB0_11:
    WORD $0xaa1f03e0 // mov    x0, xzr
    WORD $0xd65f03c0 // ret
LBB0_12:
    WORD $0x2538c010 // mov    z16.b, #0
    WORD $0xaa0903eb // mov    x11, x9
    WORD $0x04703202 // mov    z2.d, z16.d
    WORD $0x04703201 // mov    z1.d, z16.d
LBB0_13:
    WORD $0xd101014c // sub    x12, x10, #64
    WORD $0xeb0c017f // cmp    x11, x12
    BHS LBB0_19
    WORD $0x2558e3e1 // ptrue    p1.h
    WORD $0x6f07e7e3 // movi    v3.2d, #0xffffffffffffffff
    WORD $0x2538c084 // mov    z4.b, #4
    WORD $0x2538c005 // mov    z5.b, #0
    ADR LCPI0_0, R16
    WORD $0x5280040d // mov    w13, #32
    WORD $0x3dc00206 // ldr    q6, [x16, :lo12:.LCPI0_0]
    ADR check_special_casestab1, R14
    WORD $0x910001ce // add    x14, x14, :lo12:check_special_cases.tab1
    ADR check_special_casestab2, R15
    WORD $0x910001ef // add    x15, x15, :lo12:check_special_cases.tab2
    ADR check_special_casestab3, R16
    WORD $0x91000210 // add    x16, x16, :lo12:check_special_cases.tab3
    WORD $0x910003f1 // mov    x17, sp
LBB0_15:
    WORD $0xa40d4167 // ld1b    { z7.b }, p0/z, [x11, x13]
    WORD $0xa400a171 // ld1b    { z17.b }, p0/z, [x11]
    WORD $0xaa0b03f2 // mov    x18, x11
    WORD $0x910183eb // add    x11, sp, #96
    WORD $0x046730f2 // mov    z18.d, z7.d
    WORD $0x04180232 // orr    z18.b, p0/m, z18.b, z17.b
    WORD $0x24000242 // cmphs    p2.b, p0/z, z18.b, z0.b
    WORD $0xe5801d62 // str    p2, [x11, #7, mul vl]
    WORD $0x047f50eb // addpl    x11, sp, #7
    WORD $0xb940616b // ldr    w11, [x11, #96]
    CMP $0, R11
    BNE LBB0_17
    WORD $0x04703207 // mov    z7.d, z16.d
    WORD $0x04180027 // orr    z7.b, p0/m, z7.b, z1.b
    WORD $0x046730e1 // mov    z1.d, z7.d
    WORD $0x9100824b // add    x11, x18, #32
    WORD $0x9100816b // add    x11, x11, #32
    WORD $0xeb0c017f // cmp    x11, x12
    BLO LBB0_15
    B LBB0_18
LBB0_17:
    WORD $0x04623050 // mov    z16.d, z2.d
    WORD $0x04713232 // mov    z18.d, z17.d
    WORD $0x0420be35 // movprfx    z21, z17
    WORD $0x04518495 // lsr    z21.h, p1/m, z21.h, z4.h
    WORD $0x04623056 // mov    z22.d, z2.d
    WORD $0x04713237 // mov    z23.d, z17.d
    WORD $0xa40021d8 // ld1rqb    { z24.b }, p0/z, [x14]
    WORD $0x05231622 // ext    z2.b, z2.b, z17.b, #29
    WORD $0x0420bcf9 // movprfx    z25, z7
    WORD $0x04518499 // lsr    z25.h, p1/m, z25.h, z4.h
    WORD $0x05800475 // and    z21.h, z21.h, #0xf
    WORD $0x05231e30 // ext    z16.b, z16.b, z17.b, #31
    WORD $0x05231cf2 // ext    z18.b, z18.b, z7.b, #31
    WORD $0x0420be13 // movprfx    z19, z16
    WORD $0x04518493 // lsr    z19.h, p1/m, z19.h, z4.h
    WORD $0x0420be54 // movprfx    z20, z18
    WORD $0x04518494 // lsr    z20.h, p1/m, z20.h, z4.h
    WORD $0x05231a36 // ext    z22.b, z22.b, z17.b, #30
    WORD $0x05800473 // and    z19.h, z19.h, #0xf
    WORD $0x052318f7 // ext    z23.b, z23.b, z7.b, #30
    WORD $0x052314f1 // ext    z17.b, z17.b, z7.b, #29
    WORD $0x05800474 // and    z20.h, z20.h, #0xf
    WORD $0x2527dde2 // uqsub    z2.b, z2.b, #239
    WORD $0x0525c210 // sel    z16.b, p0, z16.b, z5.b
    WORD $0x0525c252 // sel    z18.b, p0, z18.b, z5.b
    WORD $0x2527dbf6 // uqsub    z22.b, z22.b, #223
    WORD $0x0525c273 // sel    z19.b, p0, z19.b, z5.b
    WORD $0x05800479 // and    z25.h, z25.h, #0xf
    WORD $0x2527dbf7 // uqsub    z23.b, z23.b, #223
    WORD $0x2527ddf1 // uqsub    z17.b, z17.b, #239
    WORD $0x0525c294 // sel    z20.b, p0, z20.b, z5.b
    WORD $0x0525c210 // sel    z16.b, p0, z16.b, z5.b
    WORD $0x0525c252 // sel    z18.b, p0, z18.b, z5.b
    WORD $0x05800673 // and    z19.b, z19.b, #0xf
    WORD $0x041802c2 // orr    z2.b, p0/m, z2.b, z22.b
    WORD $0xa40021f6 // ld1rqb    { z22.b }, p0/z, [x15]
    WORD $0x05800674 // and    z20.b, z20.b, #0xf
    WORD $0x041802f1 // orr    z17.b, p0/m, z17.b, z23.b
    WORD $0x05800670 // and    z16.b, z16.b, #0xf
    WORD $0x05800672 // and    z18.b, z18.b, #0xf
    WORD $0x05333313 // tbl    z19.b, { z24.b }, z19.b
    WORD $0x24200052 // cmphi    p2.b, p0/z, z2.b, #0
    WORD $0x05343302 // tbl    z2.b, { z24.b }, z20.b
    WORD $0x0525c334 // sel    z20.b, p0, z25.b, z5.b
    WORD $0x24200233 // cmphi    p3.b, p0/z, z17.b, #0
    WORD $0x0525c2b1 // sel    z17.b, p0, z21.b, z5.b
    WORD $0xa4002215 // ld1rqb    { z21.b }, p0/z, [x16]
    WORD $0xad001be3 // stp    q3, q6, [sp]
    WORD $0x053032d0 // tbl    z16.b, { z22.b }, z16.b
    WORD $0x053232d2 // tbl    z18.b, { z22.b }, z18.b
    WORD $0x25024002 // and    p2.b, p0/z, p0.b, p2.b
    WORD $0x0525c273 // sel    z19.b, p0, z19.b, z5.b
    WORD $0x05800674 // and    z20.b, z20.b, #0xf
    WORD $0x25034003 // and    p3.b, p0/z, p0.b, p3.b
    WORD $0x0525c042 // sel    z2.b, p0, z2.b, z5.b
    WORD $0x05800671 // and    z17.b, z17.b, #0xf
    WORD $0x04303270 // and    z16.d, z19.d, z16.d
    WORD $0x04323042 // and    z2.d, z2.d, z18.d
    WORD $0x053132b1 // tbl    z17.b, { z21.b }, z17.b
    WORD $0x053432b2 // tbl    z18.b, { z21.b }, z20.b
    WORD $0x0525c210 // sel    z16.b, p0, z16.b, z5.b
    WORD $0x05121ff3 // mov    z19.b, p2/z, #-1
    WORD $0x05131ff4 // mov    z20.b, p3/z, #-1
    WORD $0x0525c042 // sel    z2.b, p0, z2.b, z5.b
    WORD $0x04313210 // and    z16.d, z16.d, z17.d
    WORD $0x05800e13 // and    z19.b, z19.b, #0x80
    WORD $0x04323051 // and    z17.d, z2.d, z18.d
    WORD $0x05800e14 // and    z20.b, z20.b, #0x80
    WORD $0xa400a222 // ld1b    { z2.b }, p0/z, [x17]
    WORD $0x04190270 // eor    z16.b, p0/m, z16.b, z19.b
    WORD $0x04190291 // eor    z17.b, p0/m, z17.b, z20.b
    WORD $0x04180211 // orr    z17.b, p0/m, z17.b, z16.b
    WORD $0x0525c0f0 // sel    z16.b, p0, z7.b, z5.b
    WORD $0x04180031 // orr    z17.b, p0/m, z17.b, z1.b
    WORD $0x04220610 // sub    z16.b, z16.b, z2.b
    WORD $0x046730e2 // mov    z2.d, z7.d
    WORD $0x04713221 // mov    z1.d, z17.d
    WORD $0x9100824b // add    x11, x18, #32
    WORD $0x9100816b // add    x11, x11, #32
    WORD $0xeb0c017f // cmp    x11, x12
    BLO LBB0_15
LBB0_18:
    WORD $0x9101024b // add    x11, x18, #64
LBB0_19:
    WORD $0x6f00e403 // movi    v3.2d, #0000000000000000
    WORD $0xeb0a017f // cmp    x11, x10
    WORD $0xad000fe3 // stp    q3, q3, [sp]
    WORD $0xad010fe3 // stp    q3, q3, [sp, #32]
    BHS LBB0_25
    WORD $0x8b090108 // add    x8, x8, x9
    WORD $0x0460e3ec // cnth    x12
    WORD $0xcb0b0109 // sub    x9, x8, x11
    WORD $0xeb0c013f // cmp    x9, x12
    BLO LBB0_22
    WORD $0x910003ea // mov    x10, sp
    WORD $0x04bf504d // rdvl    x13, #2
    WORD $0xcb0b014a // sub    x10, x10, x11
    WORD $0xeb0d015f // cmp    x10, x13
    BHS LBB0_61
LBB0_22:
    WORD $0xaa1f03ea // mov    x10, xzr
    WORD $0xaa0b03ed // mov    x13, x11
LBB0_23:
    WORD $0x910003e9 // mov    x9, sp
    WORD $0xcb0a010c // sub    x12, x8, x10
    WORD $0x8b0a0128 // add    x8, x9, x10
    WORD $0xcb0b0189 // sub    x9, x12, x11
LBB0_24:
    WORD $0x384015aa // ldrb    w10, [x13], #1
    WORD $0xf1000529 // subs    x9, x9, #1
    WORD $0x3800150a // strb    w10, [x8], #1
    BNE LBB0_24
LBB0_25:
    WORD $0x910003e8 // mov    x8, sp
    WORD $0x52800409 // mov    w9, #32
    WORD $0xa400a104 // ld1b    { z4.b }, p0/z, [x8]
    WORD $0xa4094103 // ld1b    { z3.b }, p0/z, [x8, x9]
    WORD $0x910183e8 // add    x8, sp, #96
    WORD $0x04643065 // orr    z5.d, z3.d, z4.d
    WORD $0x240000a1 // cmphs    p1.b, p0/z, z5.b, z0.b
    WORD $0xe5801d01 // str    p1, [x8, #7, mul vl]
    WORD $0x047f50e8 // addpl    x8, sp, #7
    WORD $0xb9406108 // ldr    w8, [x8, #96]
    CMP $0, R8
    BNE LBB0_72
    WORD $0x04703202 // mov    z2.d, z16.d
    WORD $0x04180022 // orr    z2.b, p0/m, z2.b, z1.b
    WORD $0x04180050 // orr    z16.b, p0/m, z16.b, z2.b
    WORD $0x24200210 // cmphi    p0.b, p0/z, z16.b, #0
    BPL LBB0_73
LBB0_27:
    WORD $0xa9402408 // ldp    x8, x9, [x0]
    WORD $0x8b090109 // add    x9, x8, x9
    WORD $0xd1000d2b // sub    x11, x9, #3
    WORD $0xeb0b011f // cmp    x8, x11
    BHS LBB0_44
    WORD $0x52981e0c // mov    w12, #49392
    WORD $0x52901c0d // mov    w13, #32992
    WORD $0x52981f12 // mov    w18, #49400
    WORD $0x52901e01 // mov    w1, #33008
    WORD $0x72a0180c // movk    w12, #192, lsl #16
    WORD $0x72a0100d // movk    w13, #128, lsl #16
    WORD $0x528401ee // mov    w14, #8207
    WORD $0x528401af // mov    w15, #8205
    WORD $0x52981c10 // mov    w16, #49376
    WORD $0x52901811 // mov    w17, #32960
    WORD $0x72b81812 // movk    w18, #49344, lsl #16
    WORD $0x528600e0 // mov    w0, #12295
    WORD $0x72b01001 // movk    w1, #32896, lsl #16
    WORD $0x52860062 // mov    w2, #12291
    WORD $0xaa0803ea // mov    x10, x8
    B LBB0_31
LBB0_29:
    WORD $0x52800023 // mov    w3, #1
LBB0_30:
    WORD $0x8b03014a // add    x10, x10, x3
    WORD $0xeb0b015f // cmp    x10, x11
    BHS LBB0_45
LBB0_31:
    WORD $0x39c00143 // ldrsb    w3, [x10]
    TST $(1<<31), R3
    BEQ LBB0_29
    WORD $0xb9400143 // ldr    w3, [x10]
    WORD $0x0a0c0064 // and    w4, w3, w12
    WORD $0x6b0d009f // cmp    w4, w13
    BNE LBB0_35
    WORD $0x0a0e0064 // and    w4, w3, w14
    WORD $0x6b0f009f // cmp    w4, w15
    BEQ LBB0_35
    CMP $0, R4
    BNE LBB0_43
LBB0_35:
    WORD $0x0a100064 // and    w4, w3, w16
    WORD $0x6b11009f // cmp    w4, w17
    BNE LBB0_38
    WORD $0x121f0c64 // and    w4, w3, #0x1e
    CMP $0, R4
    BEQ LBB0_38
    WORD $0x52800043 // mov    w3, #2
    B LBB0_30
LBB0_38:
    WORD $0x0a120064 // and    w4, w3, w18
    WORD $0x6b01009f // cmp    w4, w1
    BNE LBB0_66
    WORD $0x0a000064 // and    w4, w3, w0
    CMP $0, R4
    BEQ LBB0_66
    TST $(1<<2), R3
    BEQ LBB0_42
    WORD $0x0a020064 // and    w4, w3, w2
    WORD $0x52800083 // mov    w3, #4
    CMP $0, R4
    BEQ LBB0_30
    B LBB0_66
LBB0_42:
    WORD $0x52800083 // mov    w3, #4
    B LBB0_30
LBB0_43:
    WORD $0x52800063 // mov    w3, #3
    B LBB0_30
LBB0_44:
    WORD $0xaa0803ea // mov    x10, x8
LBB0_45:
    WORD $0xeb09015f // cmp    x10, x9
    BHS LBB0_73
    WORD $0x52981e0b // mov    w11, #49392
    WORD $0x52901c0c // mov    w12, #32992
    WORD $0x528401ed // mov    w13, #8207
    WORD $0x72a0180b // movk    w11, #192, lsl #16
    WORD $0x72a0100c // movk    w12, #128, lsl #16
    WORD $0x528401ae // mov    w14, #8205
    WORD $0x52981c0f // mov    w15, #49376
    WORD $0x52901810 // mov    w16, #32960
    B LBB0_49
LBB0_47:
    WORD $0x9100054a // add    x10, x10, #1
LBB0_48:
    WORD $0xeb09015f // cmp    x10, x9
    BHS LBB0_73
LBB0_49:
    WORD $0x39c00151 // ldrsb    w17, [x10]
    TST $(1<<31), R17
    BEQ LBB0_47
    WORD $0xcb0a0121 // sub    x1, x9, x10
    WORD $0x390003ff // strb    wzr, [sp]
    WORD $0xf1000823 // subs    x3, x1, #2
    WORD $0x390103ff // strb    wzr, [sp, #64]
    BLO LBB0_53
    WORD $0x39400151 // ldrb    w17, [x10]
    WORD $0x39400552 // ldrb    w18, [x10, #1]
    WORD $0x91000942 // add    x2, x10, #2
    WORD $0x910103e0 // add    x0, sp, #64
    WORD $0xaa0303e1 // mov    x1, x3
    WORD $0x390003f1 // strb    w17, [sp]
    CMP $0, R3
    BEQ LBB0_54
LBB0_52:
    WORD $0x39400051 // ldrb    w17, [x2]
    WORD $0x39000011 // strb    w17, [x0]
    WORD $0x394003f1 // ldrb    w17, [sp]
    WORD $0x394103e0 // ldrb    w0, [sp, #64]
    WORD $0x53185e52 // lsl    w18, w18, #8
    WORD $0x2a004252 // orr    w18, w18, w0, lsl #16
    WORD $0x2a110252 // orr    w18, w18, w17
    WORD $0x0a0b0240 // and    w0, w18, w11
    WORD $0x6b0c001f // cmp    w0, w12
    BEQ LBB0_55
    B LBB0_57
LBB0_53:
    WORD $0x2a1f03f1 // mov    w17, wzr
    WORD $0x2a1f03f2 // mov    w18, wzr
    WORD $0x910003e0 // mov    x0, sp
    WORD $0xaa0a03e2 // mov    x2, x10
    CMP $0, R1
    BNE LBB0_52
LBB0_54:
    WORD $0x2a1f03e0 // mov    w0, wzr
    WORD $0x53185e52 // lsl    w18, w18, #8
    WORD $0x2a1f4252 // orr    w18, w18, wzr, lsl #16
    WORD $0x2a110252 // orr    w18, w18, w17
    WORD $0x0a0b0240 // and    w0, w18, w11
    WORD $0x6b0c001f // cmp    w0, w12
    BNE LBB0_57
LBB0_55:
    WORD $0x0a0d0240 // and    w0, w18, w13
    WORD $0x6b0e001f // cmp    w0, w14
    BEQ LBB0_57
    CMP $0, R0
    BNE LBB0_60
LBB0_57:
    WORD $0x721f0e3f // tst    w17, #0x1e
    BEQ LBB0_66
    WORD $0x0a0f0251 // and    w17, w18, w15
    WORD $0x6b10023f // cmp    w17, w16
    BNE LBB0_66
    WORD $0x52800051 // mov    w17, #2
    WORD $0x8b11014a // add    x10, x10, x17
    B LBB0_48
LBB0_60:
    WORD $0x52800071 // mov    w17, #3
    WORD $0x8b11014a // add    x10, x10, x17
    B LBB0_48
LBB0_61:
    WORD $0xeb0d013f // cmp    x9, x13
    BHS LBB0_67
    WORD $0xaa1f03ea // mov    x10, xzr
LBB0_63:
    WORD $0x2558e3e1 // ptrue    p1.h
    WORD $0xcb0c03ed // neg    x13, x12
    WORD $0xaa0a03ee // mov    x14, x10
    WORD $0x8a0d012a // and    x10, x9, x13
    WORD $0x910003ef // mov    x15, sp
    WORD $0x8b0a016d // add    x13, x11, x10
LBB0_64:
    WORD $0xa42e4563 // ld1b    { z3.h }, p1/z, [x11, x14]
    WORD $0xe42e45e3 // st1b    { z3.h }, p1, [x15, x14]
    WORD $0x8b0c01ce // add    x14, x14, x12
    WORD $0xeb0e015f // cmp    x10, x14
    BNE LBB0_64
    WORD $0xeb0a013f // cmp    x9, x10
    BNE LBB0_23
    B LBB0_25
LBB0_66:
    WORD $0xaa2a03e9 // mvn    x9, x10
    WORD $0x8b080120 // add    x0, x9, x8
    WORD $0x043f503f // addvl    sp, sp, #1
    WORD $0x910183ff // add    sp, sp, #96
    WORD $0xf84107fd // ldr    fp, [sp], #16
    WORD $0xd65f03c0 // ret
LBB0_67:
    WORD $0x04bf57ca // rdvl    x10, #-2
    WORD $0x04bf5031 // rdvl    x17, #1
    WORD $0x910003ef // mov    x15, sp
    WORD $0xaa1f03ee // mov    x14, xzr
    WORD $0x8a0a012a // and    x10, x9, x10
    WORD $0x8b1101f0 // add    x16, x15, x17
    WORD $0x8b110171 // add    x17, x11, x17
LBB0_68:
    WORD $0xa40e4163 // ld1b    { z3.b }, p0/z, [x11, x14]
    WORD $0xa40e4224 // ld1b    { z4.b }, p0/z, [x17, x14]
    WORD $0xe40e41e3 // st1b    { z3.b }, p0, [x15, x14]
    WORD $0xe40e4204 // st1b    { z4.b }, p0, [x16, x14]
    WORD $0x8b0d01ce // add    x14, x14, x13
    WORD $0xeb0e015f // cmp    x10, x14
    BNE LBB0_68
    WORD $0xeb0a012d // subs    x13, x9, x10
    BEQ LBB0_25
    WORD $0xeb0c01bf // cmp    x13, x12
    BHS LBB0_63
    WORD $0x8b0a016d // add    x13, x11, x10
    B LBB0_23
LBB0_72:
    WORD $0x04623046 // mov    z6.d, z2.d
    WORD $0x04643087 // mov    z7.d, z4.d
    ADR check_special_casestab1, R8
    WORD $0x91000108 // add    x8, x8, :lo12:check_special_cases.tab1
    WORD $0x04623052 // mov    z18.d, z2.d
    WORD $0x04643093 // mov    z19.d, z4.d
    WORD $0x2558e3e1 // ptrue    p1.h
    WORD $0x2538c085 // mov    z5.b, #4
    WORD $0x0420bc94 // movprfx    z20, z4
    WORD $0x045184b4 // lsr    z20.h, p1/m, z20.h, z5.h
    WORD $0x05231c86 // ext    z6.b, z6.b, z4.b, #31
    WORD $0x05231c67 // ext    z7.b, z7.b, z3.b, #31
    WORD $0x0420bcd0 // movprfx    z16, z6
    WORD $0x045184b0 // lsr    z16.h, p1/m, z16.h, z5.h
    WORD $0x0420bcf1 // movprfx    z17, z7
    WORD $0x045184b1 // lsr    z17.h, p1/m, z17.h, z5.h
    WORD $0x05231482 // ext    z2.b, z2.b, z4.b, #29
    WORD $0x05231892 // ext    z18.b, z18.b, z4.b, #30
    WORD $0x2538c000 // mov    z0.b, #0
    WORD $0x05231873 // ext    z19.b, z19.b, z3.b, #30
    WORD $0xa4002115 // ld1rqb    { z21.b }, p0/z, [x8]
    WORD $0x05800470 // and    z16.h, z16.h, #0xf
    WORD $0x05231464 // ext    z4.b, z4.b, z3.b, #29
    ADR check_special_casestab2, R8
    WORD $0x91000108 // add    x8, x8, :lo12:check_special_cases.tab2
    WORD $0x05800471 // and    z17.h, z17.h, #0xf
    WORD $0x2527dde2 // uqsub    z2.b, z2.b, #239
    WORD $0x2527dbf2 // uqsub    z18.b, z18.b, #223
    WORD $0x0520c0c6 // sel    z6.b, p0, z6.b, z0.b
    WORD $0x0520c0e7 // sel    z7.b, p0, z7.b, z0.b
    WORD $0x0520c210 // sel    z16.b, p0, z16.b, z0.b
    WORD $0x2527dbf3 // uqsub    z19.b, z19.b, #223
    WORD $0x2527dde4 // uqsub    z4.b, z4.b, #239
    WORD $0x0520c231 // sel    z17.b, p0, z17.b, z0.b
    WORD $0x04558465 // lsrr    z5.h, p1/m, z5.h, z3.h
    WORD $0x05800474 // and    z20.h, z20.h, #0xf
    WORD $0x0520c0c6 // sel    z6.b, p0, z6.b, z0.b
    WORD $0x0520c0e7 // sel    z7.b, p0, z7.b, z0.b
    WORD $0x05800670 // and    z16.b, z16.b, #0xf
    WORD $0x04180242 // orr    z2.b, p0/m, z2.b, z18.b
    WORD $0xa4002112 // ld1rqb    { z18.b }, p0/z, [x8]
    ADR check_special_casestab3, R8
    WORD $0x91000108 // add    x8, x8, :lo12:check_special_cases.tab3
    WORD $0x05800671 // and    z17.b, z17.b, #0xf
    WORD $0x04180264 // orr    z4.b, p0/m, z4.b, z19.b
    WORD $0x05800465 // and    z5.h, z5.h, #0xf
    WORD $0x05800666 // and    z6.b, z6.b, #0xf
    WORD $0x053032b0 // tbl    z16.b, { z21.b }, z16.b
    WORD $0x24200051 // cmphi    p1.b, p0/z, z2.b, #0
    WORD $0x05800667 // and    z7.b, z7.b, #0xf
    WORD $0x053132a2 // tbl    z2.b, { z21.b }, z17.b
    WORD $0xa4002111 // ld1rqb    { z17.b }, p0/z, [x8]
    ADR LCPI0_0, R8
    WORD $0x24200092 // cmphi    p2.b, p0/z, z4.b, #0
    WORD $0x0520c284 // sel    z4.b, p0, z20.b, z0.b
    WORD $0x0520c0a5 // sel    z5.b, p0, z5.b, z0.b
    WORD $0x05263246 // tbl    z6.b, { z18.b }, z6.b
    WORD $0x05273247 // tbl    z7.b, { z18.b }, z7.b
    WORD $0x25014001 // and    p1.b, p0/z, p0.b, p1.b
    WORD $0x0520c210 // sel    z16.b, p0, z16.b, z0.b
    WORD $0x25024002 // and    p2.b, p0/z, p0.b, p2.b
    WORD $0x0520c042 // sel    z2.b, p0, z2.b, z0.b
    WORD $0x05800664 // and    z4.b, z4.b, #0xf
    WORD $0x05800665 // and    z5.b, z5.b, #0xf
    WORD $0x04263206 // and    z6.d, z16.d, z6.d
    WORD $0x04273042 // and    z2.d, z2.d, z7.d
    WORD $0x05243224 // tbl    z4.b, { z17.b }, z4.b
    WORD $0x05253225 // tbl    z5.b, { z17.b }, z5.b
    WORD $0x05111fe7 // mov    z7.b, p1/z, #-1
    WORD $0x0520c0c6 // sel    z6.b, p0, z6.b, z0.b
    WORD $0x05121ff0 // mov    z16.b, p2/z, #-1
    WORD $0x0520c042 // sel    z2.b, p0, z2.b, z0.b
    WORD $0x0520c060 // mov    z0.b, p0/m, z3.b
    WORD $0x05800e07 // and    z7.b, z7.b, #0x80
    WORD $0x042430c4 // and    z4.d, z6.d, z4.d
    WORD $0x3dc00106 // ldr    q6, [x8, :lo12:.LCPI0_0]
    WORD $0x910103e8 // add    x8, sp, #64
    WORD $0x04253042 // and    z2.d, z2.d, z5.d
    WORD $0x05800e10 // and    z16.b, z16.b, #0x80
    WORD $0x6f07e7e5 // movi    v5.2d, #0xffffffffffffffff
    WORD $0x041900e4 // eor    z4.b, p0/m, z4.b, z7.b
    WORD $0x04190202 // eor    z2.b, p0/m, z2.b, z16.b
    WORD $0xad021be5 // stp    q5, q6, [sp, #64]
    WORD $0x04180082 // orr    z2.b, p0/m, z2.b, z4.b
    WORD $0xa400a104 // ld1b    { z4.b }, p0/z, [x8]
    WORD $0x04180022 // orr    z2.b, p0/m, z2.b, z1.b
    WORD $0x04240410 // sub    z16.b, z0.b, z4.b
    WORD $0x04180050 // orr    z16.b, p0/m, z16.b, z2.b
    WORD $0x24200210 // cmphi    p0.b, p0/z, z16.b, #0
    BMI LBB0_27
LBB0_73:
    WORD $0xaa1f03e0 // mov    x0, xzr
    WORD $0x043f503f // addvl    sp, sp, #1
    WORD $0x910183ff // add    sp, sp, #96
    WORD $0xf84107fd // ldr    fp, [sp], #16
    WORD $0xd65f03c0 // ret
MASK_USE_NUMBER:
    WORD $0x00000002 // .long    2
check_special_casestab1:
    WORD $0x02020202
    WORD $0x02020202
    WORD $0x80808080
    WORD $0x49150121
check_special_casestab2:
    WORD $0x8383A3E7
    WORD $0xCBCBCB8B
    WORD $0xCBCBCBCB
    WORD $0xCBCBDBCB
check_special_casestab3:
    WORD $0x01010101
    WORD $0x01010101
    WORD $0xBABAAEE6
    WORD $0x01010101

TEXT ·__validate_utf8_fast(SB), NOSPLIT, $0-16
	NO_LOCAL_POINTERS

_entry:
	MOVD 16(g), R16
	SUB $112, RSP, R17
	CMP  R16, R17
	BLS  _stack_grow

_validate_utf8_fast:
	MOVD s+0(FP), R0
	MOVD ·_subr__validate_utf8_fast(SB), R11
	WORD $0x1000005e // adr x30, .+8
	JMP (R11)
	MOVD R0, ret+8(FP)
	RET

_stack_grow:
	MOVD R30, R3
	CALL runtime·morestack_noctxt<>(SB)
	JMP  _entry
