// +build !noasm !appengine
// Code generated by asm2asm_tool, DO NOT EDIT.

package neon

import (
    `github.com/bytedance/sonic/loader`
)

const (
    _entry__value = 0
)

const (
    _stack__value = 144
)

const (
    _size__value = 27644
)

var (
    _pcsp__value = [][2]uint32{
        {0x1, 0},
        {0x144, 144},
        {0x148, 0},
        {0x6bfc, 144},
    }
)

var _cfunc_value = []loader.CFunc{
    {"_value_entry", 0, _entry__value, 0, nil},
    {"_value", _entry__value, _size__value, _stack__value, _pcsp__value},
}
