name: Pull Request Check

on: pull_request

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Check Branch
        run: ./check_branch_name.sh ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Benchmark
        run: sh bench.sh
